2017/13xxx/CVE-2017-13077.json

First of multiple CVE ID assignments for krack.

CVE-2017-13077

---

2017/13xxx/CVE-2017-13083.json

JSON created using https://vulnogram.github.io/, contains a good deal more than the CVE_JSON_4.0_min.schema.
Don't really need commit 1acef0c00cc226d3570ac3b0ecec63c94d97bb31, still working out git integration on our end.

CVE-2017-13083 is CERT/CC VU#403768 Rufus

---

2017/10xxx/CVE-2017-10955.json

https://zerodayinitiative.com/advisories/ZDI-17-812

assigns CVE-2017-10955

---

2017/2xxx/CVE-2017-2131.json
2017/2xxx/CVE-2017-2132.json
2017/2xxx/CVE-2017-2133.json

First time trying out phase 2.
Please let me know if there are any issues.
-taki

jpcert20171020 batch

---

CONTRIBUTING.md

Totally optional, do with it what you will. I have some other suggested tweaks to this document to make it easier for those new to git/github. If you're interested in those I can submit them in another PR another day.

adds an ascii git flow diagram to CONTRIBUTING.md

---

2016/3xxx/CVE-2016-3049.json
2017/1xxx/CVE-2017-1209.json
2017/1xxx/CVE-2017-1210.json
2017/1xxx/CVE-2017-1211.json
2017/1xxx/CVE-2017-1212.json
2017/1xxx/CVE-2017-1375.json
2017/1xxx/CVE-2017-1523.json
2017/1xxx/CVE-2017-1583.json

Added CVE-2016-3049, CVE-2017-1209, CVE-2017-1210, CVE-2017-1211, CVE-2017-1212, CVE-2017-1375, CVE-2017-1523, CVE-2017-1583.

IBM20171024

---

2017/1xxx/CVE-2017-1164.json
2017/1xxx/CVE-2017-1169.json
2017/1xxx/CVE-2017-1241.json
2017/1xxx/CVE-2017-1295.json
2017/1xxx/CVE-2017-1363.json

Added CVE-2017-1164, CVE-2017-1169, CVE-2017-1241, CVE-2017-1295, CVE-2017-1363.

IBM20171024b

---

2017/7xxx/CVE-2017-7335.json
2017/7xxx/CVE-2017-7341.json
2017/7xxx/CVE-2017-7732.json

Fortinet new CVEs

---

2017/1xxx/CVE-2017-1220.json
2017/1xxx/CVE-2017-1222.json
2017/1xxx/CVE-2017-1225.json
2017/1xxx/CVE-2017-1226.json
2017/1xxx/CVE-2017-1228.json
2017/1xxx/CVE-2017-1230.json
2017/1xxx/CVE-2017-1232.json
2017/1xxx/CVE-2017-1521.json

Added CVE-2017-1220, CVE-2017-1222, CVE-2017-1225, CVE-2017-1226, CVE-2017-1228, CVE-2017-1230, CVE-2017-1232, CVE-2017-1521.

IBM20171026

---

2017/14xxx/CVE-2017-14182.json
2017/7xxx/CVE-2017-7733.json

2017/14xxx/CVE-2017-14182.json (92%)
2017/7xxx/CVE-2017-7733.json

Add 2 CVEs for Fortinet

---

2017/10xxx/CVE-2017-10955.json

There was already a NOTE about the dispute.  Just adding the ** DISPUTED ** at the beginning.

Update CVE-2017-10955 with disputed tag.

---

2017/10xxx/CVE-2017-10940.json
2017/10xxx/CVE-2017-10941.json
2017/10xxx/CVE-2017-10942.json
2017/10xxx/CVE-2017-10943.json
2017/10xxx/CVE-2017-10944.json
2017/10xxx/CVE-2017-10945.json
2017/10xxx/CVE-2017-10946.json
2017/10xxx/CVE-2017-10947.json
2017/10xxx/CVE-2017-10948.json
2017/10xxx/CVE-2017-10953.json
2017/10xxx/CVE-2017-10954.json

These assignments are slightly dated, we are still refining the process
CVE-2017-10940
CVE-2017-10941
CVE-2017-10942
CVE-2017-10943
CVE-2017-10944
CVE-2017-10945
CVE-2017-10946
CVE-2017-10947
CVE-2017-10948
CVE-2017-10953
CVE-2017-10954

ZDI assigns the following CVEs (slightly old)

---

2016/3xxx/CVE-2016-3048.json
2017/1xxx/CVE-2017-1147.json
2017/1xxx/CVE-2017-1148.json
2017/1xxx/CVE-2017-1290.json
2017/1xxx/CVE-2017-1300.json
2017/1xxx/CVE-2017-1333.json
2017/1xxx/CVE-2017-1340.json
2017/1xxx/CVE-2017-1552.json
2017/1xxx/CVE-2017-1553.json
2017/1xxx/CVE-2017-1554.json

Added CVE-2016-3048, CVE-2017-1147, CVE-2017-1148, CVE-2017-1290, CVE-2017-1300, CVE-2017-1333, CVE-2017-1340, CVE-2017-1552, CVE-2017-1553, CVE-2017-1554.

IBM20171101

---

2017/10xxx/CVE-2017-10825.json
2017/10xxx/CVE-2017-10870.json
2017/10xxx/CVE-2017-10873.json

Here is this week's batch
-taki

jpcert20171102 batch

---

2017/10xxx/CVE-2017-10151.json

modified:   2017/10xxx/CVE-2017-10151.json

Committer: Bill Situ <Bill.Situ@Oracle.Com>

---

2017/1000xxx/CVE-2017-1000131.json
2017/1000xxx/CVE-2017-1000132.json
2017/1000xxx/CVE-2017-1000133.json
2017/1000xxx/CVE-2017-1000134.json
2017/1000xxx/CVE-2017-1000135.json
2017/1000xxx/CVE-2017-1000136.json
2017/1000xxx/CVE-2017-1000137.json
2017/1000xxx/CVE-2017-1000138.json
2017/1000xxx/CVE-2017-1000139.json
2017/1000xxx/CVE-2017-1000140.json
2017/1000xxx/CVE-2017-1000141.json
2017/1000xxx/CVE-2017-1000142.json
2017/1000xxx/CVE-2017-1000143.json
2017/1000xxx/CVE-2017-1000144.json
2017/1000xxx/CVE-2017-1000145.json
2017/1000xxx/CVE-2017-1000146.json
2017/1000xxx/CVE-2017-1000147.json
2017/1000xxx/CVE-2017-1000148.json
2017/1000xxx/CVE-2017-1000149.json
2017/1000xxx/CVE-2017-1000150.json
2017/1000xxx/CVE-2017-1000151.json
2017/1000xxx/CVE-2017-1000152.json
2017/1000xxx/CVE-2017-1000153.json
2017/1000xxx/CVE-2017-1000154.json
2017/1000xxx/CVE-2017-1000155.json
2017/1000xxx/CVE-2017-1000156.json
2017/1000xxx/CVE-2017-1000157.json
2017/1000xxx/CVE-2017-1000171.json

Dwf 2017 11 02 mahara

---

2017/10xxx/CVE-2017-10871.json
2017/10xxx/CVE-2017-10875.json
2017/10xxx/CVE-2017-10885.json

JPCERT batch.
Sorry about the link last time. All should be ok this time.

jpcert20171109 batch

---

2017/1xxx/CVE-2017-1221.json
2017/1xxx/CVE-2017-1229.json
2017/1xxx/CVE-2017-1453.json
2017/1xxx/CVE-2017-1477.json
2017/1xxx/CVE-2017-1710.json

Added CVE-2017-1221, CVE-2017-1229, CVE-2017-1453, CVE-2017-1477, CVE-2017-1710.

IBM20171113

---

2017/10xxx/CVE-2017-10266.json
2017/10xxx/CVE-2017-10267.json
2017/10xxx/CVE-2017-10269.json
2017/10xxx/CVE-2017-10272.json
2017/10xxx/CVE-2017-10278.json

modified:   2017/10xxx/CVE-2017-10266.json
modified:   2017/10xxx/CVE-2017-10267.json
modified:   2017/10xxx/CVE-2017-10269.json
modified:   2017/10xxx/CVE-2017-10272.json
modified:   2017/10xxx/CVE-2017-10278.json

 Committer: Bill Situ <Bill.Situ@Oracle.com>

---

2017/10xxx/CVE-2017-10886.json
2017/10xxx/CVE-2017-10887.json
2017/10xxx/CVE-2017-10888.json
2017/10xxx/CVE-2017-10889.json
2017/10xxx/CVE-2017-10890.json

jpcert20171117 batch

---

2016/6xxx/CVE-2016-6024.json
2017/1xxx/CVE-2017-1240.json
2017/1xxx/CVE-2017-1251.json
2017/1xxx/CVE-2017-1283.json
2017/1xxx/CVE-2017-1461.json
2017/1xxx/CVE-2017-1484.json
2017/1xxx/CVE-2017-1560.json
2017/1xxx/CVE-2017-1570.json
2017/1xxx/CVE-2017-1593.json
2017/1xxx/CVE-2017-1607.json
2017/1xxx/CVE-2017-1628.json
2017/1xxx/CVE-2017-1650.json
2017/1xxx/CVE-2017-1678.json
2017/1xxx/CVE-2017-1688.json
2017/1xxx/CVE-2017-1689.json

Added CVE-2016-6024, CVE-2017-1240, CVE-2017-1251, CVE-2017-1283, CVE-2017-1461, CVE-2017-1484, CVE-2017-1560, CVE-2017-1570, CVE-2017-1593, CVE-2017-1607, CVE-2017-1628, CVE-2017-1650, CVE-2017-1678, CVE-2017-1688, CVE-2017-1689.

IBM20171127

---

2017/1000xxx/CVE-2017-1000384.json
2017/1000xxx/CVE-2017-1000385.json
2017/1000xxx/CVE-2017-1000386.json
2017/1000xxx/CVE-2017-1000387.json
2017/1000xxx/CVE-2017-1000388.json
2017/1000xxx/CVE-2017-1000389.json
2017/1000xxx/CVE-2017-1000390.json
2017/1000xxx/CVE-2017-1000391.json
2017/1000xxx/CVE-2017-1000392.json
2017/1000xxx/CVE-2017-1000393.json
2017/1000xxx/CVE-2017-1000394.json
2017/1000xxx/CVE-2017-1000395.json
2017/1000xxx/CVE-2017-1000396.json
2017/1000xxx/CVE-2017-1000397.json
2017/1000xxx/CVE-2017-1000398.json
2017/1000xxx/CVE-2017-1000399.json
2017/1000xxx/CVE-2017-1000400.json
2017/1000xxx/CVE-2017-1000401.json
2017/1000xxx/CVE-2017-1000402.json
2017/1000xxx/CVE-2017-1000403.json
2017/1000xxx/CVE-2017-1000404.json

Dwf 2017 11 22 01

---

2017/10xxx/CVE-2017-10861.json
2017/10xxx/CVE-2017-10874.json
2017/10xxx/CVE-2017-10891.json
2017/10xxx/CVE-2017-10892.json
2017/10xxx/CVE-2017-10894.json
2017/10xxx/CVE-2017-10895.json
2017/10xxx/CVE-2017-10898.json
2017/10xxx/CVE-2017-10899.json
2017/10xxx/CVE-2017-10900.json
2017/10xxx/CVE-2017-10901.json
2017/10xxx/CVE-2017-10902.json
2017/10xxx/CVE-2017-10903.json

jpcert20171201 batch

---

2017/1xxx/CVE-2017-1271.json
2017/1xxx/CVE-2017-1336.json
2017/1xxx/CVE-2017-1341.json
2017/1xxx/CVE-2017-1342.json
2017/1xxx/CVE-2017-1353.json
2017/1xxx/CVE-2017-1354.json
2017/1xxx/CVE-2017-1355.json
2017/1xxx/CVE-2017-1356.json
2017/1xxx/CVE-2017-1433.json
2017/1xxx/CVE-2017-1465.json
2017/1xxx/CVE-2017-1481.json
2017/1xxx/CVE-2017-1482.json
2017/1xxx/CVE-2017-1487.json
2017/1xxx/CVE-2017-1497.json
2017/1xxx/CVE-2017-1498.json

Added CVE-2017-1271, CVE-2017-1336, CVE-2017-1341, CVE-2017-1342, CVE-2017-1353, CVE-2017-1354, CVE-2017-1355, CVE-2017-1356, CVE-2017-1433, CVE-2017-1465, CVE-2017-1481, CVE-2017-1482, CVE-2017-1487, CVE-2017-1498, CVE-2017-1498.

IBM20171207

---

2017/10xxx/CVE-2017-10893.json
2017/10xxx/CVE-2017-10896.json
2017/10xxx/CVE-2017-10897.json
2017/10xxx/CVE-2017-10906.json

jpcert20171208 batch

---

2017/1xxx/CVE-2017-1507.json
2017/1xxx/CVE-2017-1536.json
2017/1xxx/CVE-2017-1548.json
2017/1xxx/CVE-2017-1549.json
2017/1xxx/CVE-2017-1550.json
2017/1xxx/CVE-2017-1606.json
2017/1xxx/CVE-2017-1613.json
2017/1xxx/CVE-2017-1632.json
2017/1xxx/CVE-2017-1683.json
2017/1xxx/CVE-2017-1760.json

Added CVE-2017-1507, CVE-2017-1536, CVE-2017-1548, CVE-2017-1549, CVE-2017-1550, CVE-2017-1606, CVE-2017-1613, CVE-2017-1632, CVE-2017-1683, CVE-2017-1760.

IBM20171211

---

2017/1xxx/CVE-2017-1421.json
2017/1xxx/CVE-2017-1546.json
2017/1xxx/CVE-2017-1558.json
2017/1xxx/CVE-2017-1635.json
2017/1xxx/CVE-2017-1716.json

Added CVE-2017-1421, CVE-2017-1546, CVE-2017-1558, CVE-2017-1635, CVE-2017-1716.

IBM20171213

---

2017/5xxx/CVE-2017-5264.json

Release CVE-2017-5264

---

2006/6xxx/CVE-2006-6440.json
2017/3xxx/CVE-2017-3184.json
2017/3xxx/CVE-2017-3185.json
2017/3xxx/CVE-2017-3186.json
2017/3xxx/CVE-2017-3190.json
2017/3xxx/CVE-2017-3191.json
2017/3xxx/CVE-2017-3192.json
2017/3xxx/CVE-2017-3193.json
2017/3xxx/CVE-2017-3194.json
2017/3xxx/CVE-2017-3195.json
2017/3xxx/CVE-2017-3196.json

Clean attempt, CERT/CC backlog and trivial typo in CVE-2006-6440

---

2017/10xxx/CVE-2017-10904.json
2017/10xxx/CVE-2017-10905.json

jpcert20171215 batch

---

2017/1xxx/CVE-2017-1257.json
2017/1xxx/CVE-2017-1261.json
2017/1xxx/CVE-2017-1262.json
2017/1xxx/CVE-2017-1266.json
2017/1xxx/CVE-2017-1270.json
2017/1xxx/CVE-2017-1423.json
2017/1xxx/CVE-2017-1494.json
2017/1xxx/CVE-2017-1595.json
2017/1xxx/CVE-2017-1596.json
2017/1xxx/CVE-2017-1598.json
2017/1xxx/CVE-2017-1600.json
2017/1xxx/CVE-2017-1631.json
2017/1xxx/CVE-2017-1694.json
2017/1xxx/CVE-2017-1696.json
2017/1xxx/CVE-2017-1746.json
2017/1xxx/CVE-2017-1751.json
2017/1xxx/CVE-2017-1757.json

Added CVE-2017-1257, CVE-2017-1261, CVE-2017-1262, CVE-2017-1266, CVE-2017-1270, CVE-2017-1423, CVE-2017-1494, CVE-2017-1595, CVE-2017-1596, CVE-2017-1598, CVE-2017-1600, CVE-2017-1631, CVE-2017-1694, CVE-2017-1696, CVE-2017-1746, CVE-2017-1751, CVE-2017-1757.

IBM20171220

---

2017/17xxx/CVE-2017-17408.json
2017/17xxx/CVE-2017-17409.json
2017/17xxx/CVE-2017-17410.json
2017/17xxx/CVE-2017-17411.json

M  2017/17xxx/CVE-2017-17408.json
M  2017/17xxx/CVE-2017-17409.json
M  2017/17xxx/CVE-2017-17410.json
M  2017/17xxx/CVE-2017-17411.json

ZDI assigns the following CVEs:

---

2017/14xxx/CVE-2017-14363.json

Adding CVE-2017-14363 (XSS)

---

2017/10xxx/CVE-2017-10868.json
2017/10xxx/CVE-2017-10869.json
2017/10xxx/CVE-2017-10872.json
2017/10xxx/CVE-2017-10907.json
2017/10xxx/CVE-2017-10908.json
2017/10xxx/CVE-2017-10909.json
2017/17xxx/CVE-2017-17010.json

jpcert20171222 batch

---

2017/1xxx/CVE-2017-1191.json
2017/1xxx/CVE-2017-1365.json
2017/1xxx/CVE-2017-1698.json

Added CVE-2017-1191, CVE-2017-1365, CVE-2017-1698.

IBM20171226

---

2017/10xxx/CVE-2017-10910.json

jpcert20171227 batch

---

2017/1xxx/CVE-2017-1557.json

IBM20180102

---

2017/1xxx/CVE-2017-1664.json
2017/1xxx/CVE-2017-1665.json
2017/1xxx/CVE-2017-1669.json
2017/1xxx/CVE-2017-1672.json
2017/1xxx/CVE-2017-1673.json
2017/1xxx/CVE-2017-1699.json
2017/1xxx/CVE-2017-1727.json

Added CVE-2017-1664, CVE-2017-1665, CVE-2017-1669, CVE-2017-1672, CVE-2017-1673, CVE-2017-1699, CVE-2017-1727.

IBM20180104

---

2017/1xxx/CVE-2017-1493.json
2017/1xxx/CVE-2017-1612.json
2017/1xxx/CVE-2017-1666.json
2017/1xxx/CVE-2017-1668.json
2017/1xxx/CVE-2017-1670.json
2017/1xxx/CVE-2017-1671.json

Added CVE-2017-1493, CVE-2017-1612, CVE-2017-1666, CVE-2017-1668, CVE-2017-1670, CVE-2017-1671.

IBM20180109

---

2017/10xxx/CVE-2017-10352.json

On branch cna/oracle/oct2017cpuv8
(use "git reset HEAD <file>..." to unstage)
modified:   2017/10xxx/CVE-2017-10352.json

 Submitter: Bill Situ <Bill.Situ@oracle.com>

---

2016/9xxx/CVE-2016-9722.json
2017/1xxx/CVE-2017-1459.json
2017/1xxx/CVE-2017-1533.json
2017/1xxx/CVE-2017-1534.json
2017/1xxx/CVE-2017-1623.json

Added CVE-2016-9722, CVE-2017-1459, CVE-2017-1533, CVE-2017-1534, CVE-2017-1623.

IBM20180110

---

2018/0xxx/CVE-2018-0001.json
2018/0xxx/CVE-2018-0002.json
2018/0xxx/CVE-2018-0003.json
2018/0xxx/CVE-2018-0004.json
2018/0xxx/CVE-2018-0005.json
2018/0xxx/CVE-2018-0006.json
2018/0xxx/CVE-2018-0007.json
2018/0xxx/CVE-2018-0008.json
2018/0xxx/CVE-2018-0009.json
2018/0xxx/CVE-2018-0010.json
2018/0xxx/CVE-2018-0011.json
2018/0xxx/CVE-2018-0012.json
2018/0xxx/CVE-2018-0013.json
2018/0xxx/CVE-2018-0014.json

CVE assignments in Juniper Security Advisories for Jan 2018 (for CVE-2018-0001 to 0014)

CVE assignments in Juniper Security Advisories for Jan 2018

---

2017/1xxx/CVE-2017-1478.json
2017/1xxx/CVE-2017-1681.json
2017/1xxx/CVE-2017-1739.json
2017/1xxx/CVE-2017-1740.json
2018/1xxx/CVE-2018-1361.json

Added CVE-2017-1478, CVE-2017-1681, CVE-2017-1739, CVE-2017-1740, CVE-2018-1361.

IBM20180111

---

2017/2xxx/CVE-2017-2158.json

jpcert20180112 batch

---

2017/1xxx/CVE-2017-1693.json
2018/1xxx/CVE-2018-1362.json

Added CVE-2017-1693, CVE-2018-13362.

IBM20180119

---

2017/1xxx/CVE-2017-1769.json

IBM20180124

---

2017/2xxx/CVE-2017-2166.json
2018/0xxx/CVE-2018-0506.json
2018/0xxx/CVE-2018-0507.json

jpcert20180126 batch

---

2016/2xxx/CVE-2016-2983.json
2017/1xxx/CVE-2017-1204.json
2017/1xxx/CVE-2017-1279.json
2017/1xxx/CVE-2017-1506.json
2017/1xxx/CVE-2017-1515.json
2017/1xxx/CVE-2017-1516.json
2017/1xxx/CVE-2017-1532.json
2017/1xxx/CVE-2017-1540.json
2017/1xxx/CVE-2017-1545.json
2017/1xxx/CVE-2017-1563.json
2017/1xxx/CVE-2017-1567.json
2017/1xxx/CVE-2017-1653.json

Added CVE-2016-2983, CVE-2017-1204, CVE-2017-1279, CVE-2017-1506, CVE-2017-1515, CVE-2017-1516, CVE-2017-1532, CVE-2017-1540, CVE-2017-1545, CVE-2017-1563, CVE-2017-1567, CVE-2017-1653.

IBM20180126

---

CONTRIBUTING.md

Signed-off-by: David Black <dblack@atlassian.com>

Update the how to use `jsonschema` instructions and the location of the v4 schema.

---

2017/1xxx/CVE-2017-1779.json
2017/1xxx/CVE-2017-1783.json
2017/1xxx/CVE-2017-1784.json
2018/1xxx/CVE-2018-1364.json

Added CVE-2017-1779, CVE-2017-1783, CVE-2017-1784, CVE-2018-1364.

IBM20180129

---

2017/1000xxx/CVE-2017-1000141.json

As per 
https://github.com/CVEProject/cvelist/pull/37
https://github.com/CVEProject/cvelist/pull/38

this was supposed to be rejected

---

2018/0xxx/CVE-2018-0508.json
2018/0xxx/CVE-2018-0509.json
2018/0xxx/CVE-2018-0510.json
2018/0xxx/CVE-2018-0511.json

jpcert20180201 batch

---

2017/1xxx/CVE-2017-1692.json
2017/1xxx/CVE-2017-1785.json
2018/1xxx/CVE-2018-1366.json
2018/1xxx/CVE-2018-1382.json
2018/1xxx/CVE-2018-1388.json

Added CVE-2017-1692, CVE-2017-1785, CVE-2018-1366, CVE-2018-1382, CVE-2018-1388.

IBM20180207

---

2018/0xxx/CVE-2018-0512.json
2018/0xxx/CVE-2018-0513.json
2018/0xxx/CVE-2018-0514.json
2018/0xxx/CVE-2018-0517.json

jpcert20180208 batch

---

2017/1xxx/CVE-2017-1761.json
2018/1xxx/CVE-2018-1368.json
2018/1xxx/CVE-2018-1401.json

Added CVE-2017-1761, CVE-2018-1368, CVE-2018-1401.

IBM20180209

---

2017/1xxx/CVE-2017-1711.json
2017/1xxx/CVE-2017-1714.json
2017/1xxx/CVE-2017-1720.json
2018/1xxx/CVE-2018-1383.json

Added CVE-2017-1711, CVE-2017-1714, CVE-2017-1720, CVE-2018-1383.

IBM20180213

---

2017/1xxx/CVE-2017-1499.json
2017/1xxx/CVE-2017-1682.json

Added CVE-2017-1499, CVE-2017-1682.

IBM20180214

---

2017/10xxx/CVE-2017-10271.json

On branch cna/oracle/oct2017cpuv10
modified:   2017/10xxx/CVE-2017-10271.json

Bill Situ <Bill.Situ@gmail.com>

---

2017/2xxx/CVE-2017-2252.json
2018/0xxx/CVE-2018-0515.json
2018/0xxx/CVE-2018-0516.json

This week's entries.
Includes an update to a previous entry.

jpcert20180216 batch

---

2018/1xxx/CVE-2018-1409.json
2018/1xxx/CVE-2018-1410.json
2018/1xxx/CVE-2018-1411.json

Added CVE-2018-1409, CVE-2018-1410, CVE-2018-1411.

IBM20180217

---

2017/1xxx/CVE-2017-1462.json
2017/1xxx/CVE-2017-1604.json
2017/1xxx/CVE-2017-1758.json

CVE-2017-1462, CVE-2017-1604, CVE-2017-1758.

IBM20180221

---

2017/5xxx/CVE-2017-5249.json
2017/5xxx/CVE-2017-5250.json
2017/5xxx/CVE-2017-5251.json

Published these back in September, and apparently never updated the CVEs. So here you go!

Wink and Insteon CVEs from Rapid7

---

2017/1xxx/CVE-2017-1758.json
2018/1xxx/CVE-2018-1391.json
2018/1xxx/CVE-2018-1392.json
2018/1xxx/CVE-2018-1414.json
2018/1xxx/CVE-2018-1415.json
2018/1xxx/CVE-2018-1417.json

Added CVE-2018-1391, CVE-2018-1392, CVE-2018-1414. CVE-2018-1415, CVE-2018-1417.
Updated CVE-2017-1758 with more platforms and references.

IBM20180222

---

2018/0xxx/CVE-2018-0015.json

Juniper 2018-02 updates

---

2018/0xxx/CVE-2018-0518.json
2018/0xxx/CVE-2018-0519.json
2018/0xxx/CVE-2018-0520.json

jpcert20180223 batch

---

2018/1xxx/CVE-2018-1372.json
2018/1xxx/CVE-2018-1399.json
2018/1xxx/CVE-2018-1416.json
2018/1xxx/CVE-2018-1425.json

Added CVE-2018-1372, CVE-2018-1399, CVE-2018-1416, CVE-2018-1425.

IBM20180227

---

2017/1xxx/CVE-2017-1654.json
2017/1xxx/CVE-2017-1787.json
2018/1xxx/CVE-2018-1373.json

Added CVE-2017-1654, CVE-2017-1787, CVE-2018-1373.

IBM20180302

---

2017/1xxx/CVE-2017-1625.json
2018/1xxx/CVE-2018-1387.json
2018/1xxx/CVE-2018-1442.json
2018/1xxx/CVE-2018-1443.json

Added CVE-2017-1625, CVE-2018-1387, CVE-2018-1442, CVE-2018-1443.

IBM20180307

---

2018/2xxx/CVE-2018-2575.json

On branch cna/oracle/CPU2018JanRev6
modified:   2018/2xxx/CVE-2018-2575.json

 Bill Situ <Bill.Situ@oracle.com>

---

2017/1xxx/CVE-2017-1741.json
2018/1xxx/CVE-2018-1386.json
2018/1xxx/CVE-2018-1435.json
2018/1xxx/CVE-2018-1437.json
2018/1xxx/CVE-2018-1441.json
2018/1xxx/CVE-2018-1444.json

Added CVE-2017-1741, CVE-2018-1386, CVE-2018-1435, CVE-2018-1437, CVE-2017-1441, CVE-2017-1444.

IBM20180313

---

2018/7xxx/CVE-2018-7677.json
2018/7xxx/CVE-2018-7678.json

New vulns published on DocuTrac software by Rapid7

CVE-2018-5551, CVE-2018-5552, DocuTrac

---

2016/9xxx/CVE-2016-9711.json
2017/1xxx/CVE-2017-1571.json
2017/1xxx/CVE-2017-1677.json
2017/1xxx/CVE-2017-1788.json
2017/1xxx/CVE-2017-1789.json
2018/1xxx/CVE-2018-1426.json
2018/1xxx/CVE-2018-1427.json
2018/1xxx/CVE-2018-1428.json
2018/1xxx/CVE-2018-1448.json

Added CVE-2016-9711, CVE-2017-1571, CVE-2017-1677, CVE-2017-1788, CVE-2017-1789, CVE-2018-1426, CVE-2018-1427, CVE-2018-1428, CVE-2018-1448.

IBM20180321

---

2018/0xxx/CVE-2018-0534.json
2018/0xxx/CVE-2018-0535.json
2018/0xxx/CVE-2018-0536.json
2018/0xxx/CVE-2018-0537.json
2018/0xxx/CVE-2018-0538.json
2018/0xxx/CVE-2018-0539.json
2018/0xxx/CVE-2018-0540.json
2018/0xxx/CVE-2018-0541.json
2018/0xxx/CVE-2018-0542.json
2018/0xxx/CVE-2018-0552.json

jpcert20180322 batch

---

2017/1xxx/CVE-2017-1524.json
2017/1xxx/CVE-2017-1602.json
2017/1xxx/CVE-2017-1629.json
2017/1xxx/CVE-2017-1655.json
2017/1xxx/CVE-2017-1762.json
2018/1xxx/CVE-2018-1429.json

Added CVE-2017-1524, CVE-2017-1602, CVE-2017-1629, CVE-2017-1655, CVE-2017-1762, CVE-2018-1429.

IBM20180323

---

2017/1xxx/CVE-2017-1705.json
2017/1xxx/CVE-2017-1747.json
2017/1xxx/CVE-2017-1756.json
2017/1xxx/CVE-2017-1765.json
2017/1xxx/CVE-2017-1766.json
2017/1xxx/CVE-2017-1767.json
2018/1xxx/CVE-2018-1384.json
2018/1xxx/CVE-2018-1390.json

Added CVE-2017-1705, CVE-2017-1747, CVE-2017-1756, CVE-2017-1765, CVE-2017-1766, CVE-2017-1767, CVE-2018-1384, CVE-2018-1390.

IBM20180330

---

2017/4xxx/CVE-2017-4011.json

Changed vendor from Intel to McAfee.

CVE-2017-4011 Changed vendor from Intel to McAfee.

---

2018/6xxx/CVE-2018-6660.json

Please reject this pull request.  Use the new one submitted with correct JSON data.

Update CVE-2018-6660 #2.json

---

2018/6xxx/CVE-2018-6661.json

Please reject pull request "Update CVE-2018-6661 #2.json".  Use this new one submitted with correct JSON data.
"Update CVE-2018-6661 #2.json" was for the wrong CVE ID.  My bad.

Update CVE-2018-6661 #3.json

---

2018/6xxx/CVE-2018-6659.json

Update CVE-2018-6659 #2.json

---

2018/9xxx/CVE-2018-9205.json

I've created the JSON for CVE-2018-9205.

Added CVE-2018-9205

---

2018/1002xxx/CVE-2018-1002150.json

Signed-off-by: Patrick Uiterwijk <patrick@puiterwijk.org>

CVE-2018-1002150 public

---

2018/0xxx/CVE-2018-0545.json
2018/0xxx/CVE-2018-0553.json
2018/0xxx/CVE-2018-0554.json
2018/0xxx/CVE-2018-0555.json
2018/0xxx/CVE-2018-0556.json

This week's batch. I and some other JPCERT members took over the job for Taki.

jpcert20180406 batch

---

2016/9xxx/CVE-2016-9645.json

Signed-off-by: Salvatore Bonaccorso <carnil@debian.org>

Add publication information for CVE-2016-9645

---

2017/2xxx/CVE-2017-2599.json

CVE-2017-2599.json

---

2017/1xxx/CVE-2017-1790.json

IBM20180412

---

2018/0xxx/CVE-2018-0530.json
2018/0xxx/CVE-2018-0531.json
2018/0xxx/CVE-2018-0532.json
2018/0xxx/CVE-2018-0533.json
2018/0xxx/CVE-2018-0548.json
2018/0xxx/CVE-2018-0549.json
2018/0xxx/CVE-2018-0550.json
2018/0xxx/CVE-2018-0551.json
2018/0xxx/CVE-2018-0560.json
2018/0xxx/CVE-2018-0561.json
2018/0xxx/CVE-2018-0562.json

jpcert20180416 batch

---

2018/5xxx/CVE-2018-5429.json
2018/5xxx/CVE-2018-5430.json
2018/5xxx/CVE-2018-5431.json

Three JasperReports-related CVEs.

TIBCO JasperReports Library and Server vulnerabilities.

---

2017/1xxx/CVE-2017-1473.json
2017/1xxx/CVE-2017-1486.json
2017/1xxx/CVE-2017-1701.json
2017/1xxx/CVE-2017-1764.json
2017/1xxx/CVE-2017-1786.json

Added CVE-2017-1473, CVE-2017-1486, CVE-2017-1701, CVE-2017-1764, CVE-2017-1786.

IBM20180423

---

2017/1xxx/CVE-2017-1700.json
2017/1xxx/CVE-2017-1725.json
2017/1xxx/CVE-2017-1734.json

Added CVE-2017-1700, CVE-2017-1725, CVE-2017-1734.  Note: Description does not have version numbers due to large quantity of different affected products.

IBM20180424

---

2017/1xxx/CVE-2017-1750.json
2018/1xxx/CVE-2018-1363.json

Added CVE-2017-1750, CVE-2018-1363.

IBM20180425

---

2017/1xxx/CVE-2017-1721.json
2017/1xxx/CVE-2017-1722.json
2017/1xxx/CVE-2017-1723.json
2017/1xxx/CVE-2017-1724.json
2018/1xxx/CVE-2018-1418.json

Added CVE-2017-1721, CVE-2017-1722, CVE-2017-1723, CVE-2017-1724, CVE-2018-1418.

IBM20180426

---

2016/9xxx/CVE-2016-9601.json

edit CVE-2016-9601

---

2017/1xxx/CVE-2017-1116.json
2018/1xxx/CVE-2018-1471.json
2018/1xxx/CVE-2018-1473.json
2018/1xxx/CVE-2018-1475.json
2018/1xxx/CVE-2018-1479.json

Added CVE-2017-1116, CVE-2018-1471, CVE-2018-1473, CVE-2018-1475, CVE-2018-1479.

IBM20180427

---

2018/1xxx/CVE-2018-1389.json
2018/1xxx/CVE-2018-1430.json

Added CVE-2018-1389, CVE-2018-1430.

IBM20180430

---

2017/5xxx/CVE-2017-5535.json
2017/5xxx/CVE-2017-5536.json

Two CVEs related to TIBCO Software Inc.'s TIBCO DataSynapse GridServer product family.

GridServer advisories.

---

2017/1xxx/CVE-2017-1255.json
2017/1xxx/CVE-2017-1601.json
2018/1xxx/CVE-2018-1468.json

Added CVE-2017-1255, CVE-2017-1601, CVE-2018-1468.

IBM20180502

---

2017/1xxx/CVE-2017-1743.json

IBM20180504

---

2018/1xxx/CVE-2018-1413.json

IBM20180507

---

2018/6xxx/CVE-2018-6510.json
2018/6xxx/CVE-2018-6511.json

This commit adds the now public Puppet Enterprise CVEs.

Add CVE-2018-6510 and CVE-2018-6511

---

2018/8xxx/CVE-2018-8911.json
2018/8xxx/CVE-2018-8912.json

Added CVE-2018-8911 and CVE-2018-8912.

Synology-SA-18:03

---

2018/8xxx/CVE-2018-8914.json

Synology-SA-18:04

---

2018/8xxx/CVE-2018-8910.json

Synology-SA-18:05

---

2018/8xxx/CVE-2018-8915.json

Synology-SA-18:06

---

2018/0xxx/CVE-2018-0568.json
2018/0xxx/CVE-2018-0576.json
2018/0xxx/CVE-2018-0577.json
2018/0xxx/CVE-2018-0578.json
2018/0xxx/CVE-2018-0579.json
2018/0xxx/CVE-2018-0580.json
2018/0xxx/CVE-2018-0581.json
2018/0xxx/CVE-2018-0582.json
2018/0xxx/CVE-2018-0583.json
2018/0xxx/CVE-2018-0585.json
2018/0xxx/CVE-2018-0586.json
2018/0xxx/CVE-2018-0587.json
2018/0xxx/CVE-2018-0588.json
2018/0xxx/CVE-2018-0589.json
2018/0xxx/CVE-2018-0590.json
2018/0xxx/CVE-2018-0591.json

jpcert20180514 batch

---

2018/1xxx/CVE-2018-1433.json
2018/1xxx/CVE-2018-1434.json
2018/1xxx/CVE-2018-1438.json
2018/1xxx/CVE-2018-1461.json
2018/1xxx/CVE-2018-1462.json
2018/1xxx/CVE-2018-1463.json
2018/1xxx/CVE-2018-1464.json
2018/1xxx/CVE-2018-1465.json
2018/1xxx/CVE-2018-1466.json

Added CVE-2018-1433, CVE-2018-1434, CVE-2018-1438, CVE-2018-1461, CVE-2018-1462, CVE-2018-1463, CVE-2018-1464, CVE-2018-1465, CVE-2018-1466.

IBM20180517

---

2018/1xxx/CVE-2018-1583.json

IBM20180521

---

2017/1xxx/CVE-2017-1752.json
2018/1xxx/CVE-2018-1449.json
2018/1xxx/CVE-2018-1450.json
2018/1xxx/CVE-2018-1451.json
2018/1xxx/CVE-2018-1452.json
2018/1xxx/CVE-2018-1459.json
2018/1xxx/CVE-2018-1467.json
2018/1xxx/CVE-2018-1488.json
2018/1xxx/CVE-2018-1515.json
2018/1xxx/CVE-2018-1544.json
2018/1xxx/CVE-2018-1565.json

Added CVE-2017-1752, CVE-2018-1449, CVE-2018-1450, CVE-2018-1451, CVE-2018-1452, CVE-2018-1459, CVE-2018-1467, CVE-2018-1488, CVE-2018-1488, CVE-2018-1515, CVE-2018-1544, CVE-2018-1565.

IBM20180524

---

2017/1xxx/CVE-2017-1768.json
2018/1xxx/CVE-2018-1369.json
2018/1xxx/CVE-2018-1370.json
2018/1xxx/CVE-2018-1375.json
2018/1xxx/CVE-2018-1376.json

Added CVE-2017-1768, CVE-2018-1369, CVE-2018-1370, CVE-2017-1375, and CVE-2018-1376.

IBM20180528

---

2018/8xxx/CVE-2018-8921.json
2018/8xxx/CVE-2018-8922.json

Added CVE-2018-8921 and CVE-2018-8922.

Synology-SA-18:11

---

2017/1xxx/CVE-2017-1748.json
2018/1xxx/CVE-2018-1600.json

Added CVE-2017-1745, CVE-2018-1600.

IBM20180604

---

2018/8xxx/CVE-2018-8923.json

Synology-SA-18:09

---

2018/8xxx/CVE-2018-8924.json

Synology-SA-18:12

---

2017/1xxx/CVE-2017-1350.json
2018/1xxx/CVE-2018-1432.json
2018/1xxx/CVE-2018-1454.json

Added CVE-2017-1350, CVE-2018-1432, CVE-2018-1454.

IBM20180605

---

2017/1xxx/CVE-2017-1474.json
2017/1xxx/CVE-2017-1476.json
2017/1xxx/CVE-2017-1480.json
2018/1xxx/CVE-2018-1456.json

Added CVE-2017-1474, CVE-2017-1476, CVE-2017-1480, and CVE-2018-1456.

IBM20180606

---

2018/1xxx/CVE-2018-1514.json
2018/1xxx/CVE-2018-1547.json

Added CVE-2018-1514 and CVE-2018-1547.

IBM20180607

---

2018/8xxx/CVE-2018-8925.json
2018/8xxx/CVE-2018-8926.json

Added CVE-2018-8925 and CVE-2018-8926.

Synology-SA-18:15

---

2017/12xxx/CVE-2017-12078.json

Synology-SA-17:79

---

2017/1xxx/CVE-2017-1405.json
2018/1xxx/CVE-2018-1453.json

Added CVE-2017-1405 and CVE-2018-1453.

IBM20180608

---

2011/4xxx/CVE-2011-4190.json
2012/0xxx/CVE-2012-0433.json
2013/3xxx/CVE-2013-3703.json
2014/0xxx/CVE-2014-0593.json
2014/0xxx/CVE-2014-0594.json
2014/5xxx/CVE-2014-5220.json

- CVE-2011-4190
- CVE-2012-0433
- CVE-2013-3703
- CVE-2014-0593
- CVE-2014-0594
- CVE-2014-5220

Added JSON data for old CVEs:

---

2018/0xxx/CVE-2018-0732.json

Client DoS due to large DH parameter

Add details for OpenSSL CVE-2018-0732

---

2018/5xxx/CVE-2018-5432.json
2018/5xxx/CVE-2018-5433.json
2018/5xxx/CVE-2018-5434.json

JSON for first publication of CVE-2018-5432, CVE-2018-5433, CVE-2018-5434

Advisories for TIBCO Runtime Agent and TIBCO Administrator - Enterprise Edition

---

2018/1xxx/CVE-2018-1393.json
2018/1xxx/CVE-2018-1431.json

Added CVE-2018-1393, CVE-2018-1431.

IBM20180613

---

2018/8xxx/CVE-2018-8927.json

Synology-SA-18:16

---

2018/1xxx/CVE-2018-1419.json
2018/1xxx/CVE-2018-1460.json

Added CVE-2018-1419, CVE-2018-1460.

IBM20180615

---

2018/8xxx/CVE-2018-8928.json

Synology-SA-18:10

---

2017/16xxx/CVE-2017-16773.json

Synology-SA-18:27

---

2018/8xxx/CVE-2018-8929.json

Synology-SA-18:19

---

2017/1xxx/CVE-2017-1237.json
2017/1xxx/CVE-2017-1238.json
2017/1xxx/CVE-2017-1239.json
2017/1xxx/CVE-2017-1242.json
2017/1xxx/CVE-2017-1248.json
2017/1xxx/CVE-2017-1329.json
2017/1xxx/CVE-2017-1488.json
2017/1xxx/CVE-2017-1509.json
2017/1xxx/CVE-2017-1559.json
2017/1xxx/CVE-2017-1795.json
2018/1xxx/CVE-2018-1494.json
2018/1xxx/CVE-2018-1542.json
2018/1xxx/CVE-2018-1546.json
2018/1xxx/CVE-2018-1555.json
2018/1xxx/CVE-2018-1556.json
2018/1xxx/CVE-2018-1621.json
2018/1xxx/CVE-2018-1676.json

Added CVE-2017-1237, CVE-2017-1238, CVE-2017-1239, CVE-2017-1242, CVE-2017-1248, CVE-2017-1329, CVE-2017-1488, CVE-2017-1509, CVE-2017-1559, CVE-2017-1795, CVE-2018-1494, CVE-2018-1542, CVE-2018-1546, CVE-2018-1555, CVE-2018-1556, CVE-2018-1621, CVE-2018-1676.

Ibm20180706 83226

---

2018/1xxx/CVE-2018-1548.json

Ibm20180708 1787

---

2018/1xxx/CVE-2018-1423.json
2018/1xxx/CVE-2018-1458.json
2018/1xxx/CVE-2018-1487.json
2018/1xxx/CVE-2018-1492.json
2018/1xxx/CVE-2018-1566.json

Added CVE-2018-1423, CVE-2018-1458, CVE-2018-1487, CVE-2018-1492, and CVE-2018-1566.

Ibm20180710 11627

---

2018/1xxx/CVE-2018-1529.json
2018/1xxx/CVE-2018-1535.json
2018/1xxx/CVE-2018-1536.json
2018/1xxx/CVE-2018-1585.json
2018/1xxx/CVE-2018-1587.json

Added CVE-2018-1529, CVE-2018-1535, CVE-2018-1536, CVE-2018-1585, CVE-2018-1587.

Ibm20180719 82725

---

2017/1xxx/CVE-2017-1544.json
2017/1xxx/CVE-2017-1575.json
2017/1xxx/CVE-2017-1633.json
2018/1xxx/CVE-2018-1398.json
2018/1xxx/CVE-2018-1470.json
2018/1xxx/CVE-2018-1563.json
2018/1xxx/CVE-2018-1564.json
2018/1xxx/CVE-2018-1679.json

Added CVE-2017-1544, CVE-2017-1575, CVE-2017-1633, CVE-2018-1398, CVE-2018-1470, CVE-2018-1563, CVE-2018-1564, CVE-2018-1679.

Ibm20180720 84327

---

2018/1xxx/CVE-2018-1503.json
2018/1xxx/CVE-2018-1513.json

Added CVE-2018-1503 and CVE-2018-1513.

Ibm20180722 161622

---

2018/6xxx/CVE-2018-6683.json

Third patch from original as I spotted errors when reviewing prior to pulling.

CVE-2018-6683

---

2018/0xxx/CVE-2018-0607.json
2018/0xxx/CVE-2018-0613.json
2018/0xxx/CVE-2018-0614.json
2018/0xxx/CVE-2018-0617.json
2018/0xxx/CVE-2018-0618.json
2018/0xxx/CVE-2018-0619.json
2018/0xxx/CVE-2018-0620.json
2018/0xxx/CVE-2018-0621.json
2018/0xxx/CVE-2018-0622.json

JPCERT20180726

---

2018/13xxx/CVE-2018-13280.json

Synology-SA-18:39

---

2018/1xxx/CVE-2018-1595.json
2018/1xxx/CVE-2018-1638.json

Added CVE-2018-1595, updated CVSS score in CVE-2018-1638.

Ibm20180801 104250

---

2018/2xxx/CVE-2018-2933.json
2018/3xxx/CVE-2018-3108.json
2018/3xxx/CVE-2018-3109.json

On branch cna/oracle/jul2018cpuv4
modified:   2018/2xxx/CVE-2018-2933.json
modified:   2018/3xxx/CVE-2018-3108.json
modified:   2018/3xxx/CVE-2018-3109.json

Bill Situ <Bill.Situ@oracle.com>

---

2018/1xxx/CVE-2018-1524.json

Ibm20180803 10384

---

2017/1xxx/CVE-2017-1366.json
2017/1xxx/CVE-2017-1368.json
2017/1xxx/CVE-2017-1396.json
2017/1xxx/CVE-2017-1409.json
2017/1xxx/CVE-2017-1411.json
2017/1xxx/CVE-2017-1412.json
2017/1xxx/CVE-2017-1755.json
2018/1xxx/CVE-2018-1422.json
2018/1xxx/CVE-2018-1528.json
2018/1xxx/CVE-2018-1551.json

Added CVE-2017-1366, CVE-2017-1368, CVE-2017-1396, CVE-2017-1409, CVE-2017-1411, CVE-2017-1412, CVE-2017-1755, CVE-2018-1422, CVE-2018-1528, and CVE-2018-1551.

Ibm20180806 83252

---

2018/1xxx/CVE-2018-1690.json

Ibm20180807 6613

---

2014/0xxx/CVE-2014-0085.json

Forgot to sign the previous 2 commits. Sorry about that
Is it possible that you add a line break before "Note:" and before "Previous text:"?
Thanks!

Cve 2014 0085

---

2016/2xxx/CVE-2016-2922.json
2017/1xxx/CVE-2017-1286.json
2017/1xxx/CVE-2017-1749.json

Added CVE-2016-2922, CVE-2017-1286, and CVE-2017-1749.

Ibm20180813 11342

---

2018/1xxx/CVE-2018-1715.json

Ibm20180816 82122

---

2017/1xxx/CVE-2017-1732.json

Ibm20180817 1141

---

2017/1xxx/CVE-2017-1753.json
2018/1xxx/CVE-2018-1394.json
2018/1xxx/CVE-2018-1517.json
2018/1xxx/CVE-2018-1656.json

Added CVE-2017-1753, CVE-2018-1656, CVE-2018-1517, CVE-2018-1394.

Ibm20180820 113643

---

2018/1xxx/CVE-2018-1599.json

Ibm20180822 6387

---

2018/1xxx/CVE-2018-1705.json

Ibm20180828 6158

---

2016/0xxx/CVE-2016-0205.json
2016/0xxx/CVE-2016-0234.json
2016/0xxx/CVE-2016-0373.json

Added CVE-2016-0205, CVE-2016-0373, and CVE-2016-0234.

Ibm20180830 93942

---

2018/0xxx/CVE-2018-0646.json
2018/0xxx/CVE-2018-0656.json
2018/0xxx/CVE-2018-0664.json
2018/0xxx/CVE-2018-0672.json
2018/0xxx/CVE-2018-0674.json
2018/0xxx/CVE-2018-0675.json

- CVE-2018-0646.json
- CVE-2018-0656.json
- CVE-2018-0664.json
- CVE-2018-0672.json
- CVE-2018-0674.json
- CVE-2018-0675.json

jpcert20180903 batch

---

2018/11xxx/CVE-2018-11262.json

Publish CVE-2018-11262 from qualcomm product secutity

---

2018/15xxx/CVE-2018-15910.json
2018/16xxx/CVE-2018-16509.json
2018/16xxx/CVE-2018-16510.json
2018/16xxx/CVE-2018-16511.json

the bugs are still closed, but clearly referenced

added bug numbers

---

2015/CVE-2015-9266.json

CVE-2015-9266

---

2018/11xxx/CVE-2018-11263.json

Publish CVE-2018-11263 from Qualcomm product security team

---

2017/1xxx/CVE-2017-1114.json
2017/1xxx/CVE-2017-1115.json
2018/1xxx/CVE-2018-1567.json
2018/1xxx/CVE-2018-1756.json
2018/1xxx/CVE-2018-1757.json
2018/1xxx/CVE-2018-1789.json

Added CVE-2017-1114, CVE-2017-1115, CVE-2018-1567, CVE-2018-1756, CVE-2018-1757, and CVE-2018-1789.

Ibm20180907 104632

---

2018/1xxx/CVE-2018-1571.json

Ibm20180911 6638

---

2018/1xxx/CVE-2018-1773.json

Ibm20180912 92347

---

2018/1xxx/CVE-2018-1698.json

Ibm20180913 101336

---

2018/1xxx/CVE-2018-1719.json
2018/1xxx/CVE-2018-1791.json

Added CVE-2018-1719 and CVE-2018-1791.

Ibm20180914 73932

---

2018/14xxx/CVE-2018-14320.json

M  2018/14xxx/CVE-2018-14320.json

ZDI assigns the following CVE:

---

2018/11xxx/CVE-2018-11878.json
2018/11xxx/CVE-2018-11883.json
2018/11xxx/CVE-2018-11886.json
2018/11xxx/CVE-2018-11889.json
2018/11xxx/CVE-2018-11891.json
2018/11xxx/CVE-2018-11893.json
2018/11xxx/CVE-2018-11894.json
2018/11xxx/CVE-2018-11895.json
2018/11xxx/CVE-2018-11897.json
2018/11xxx/CVE-2018-11898.json
2018/11xxx/CVE-2018-11902.json
2018/11xxx/CVE-2018-11903.json
2018/11xxx/CVE-2018-11904.json
2018/3xxx/CVE-2018-3573.json
2018/3xxx/CVE-2018-3574.json
2018/5xxx/CVE-2018-5905.json

Qualcomm CVE Publish(9/19/2018)

Qualcomm 9/19/2018 CVE Publish

---

2017/1xxx/CVE-2017-1794.json
2018/1xxx/CVE-2018-1782.json

Added CVE-2017-1794 and CVE-2018-1782.

Ibm20180919 94053

---

2017/18xxx/CVE-2017-18280.json
2017/18xxx/CVE-2017-18301.json
2017/18xxx/CVE-2017-18302.json
2017/18xxx/CVE-2017-18314.json
2018/11xxx/CVE-2018-11267.json
2018/11xxx/CVE-2018-11268.json
2018/11xxx/CVE-2018-11269.json
2018/11xxx/CVE-2018-11277.json
2018/11xxx/CVE-2018-11285.json
2018/11xxx/CVE-2018-11287.json
2018/11xxx/CVE-2018-11290.json
2018/11xxx/CVE-2018-11291.json
2018/11xxx/CVE-2018-11292.json
2018/11xxx/CVE-2018-11982.json
2018/5xxx/CVE-2018-5837.json
2018/5xxx/CVE-2018-5871.json

Qualcomm 9-20-2018 CVE Publish

Qualcomm 9/20/2018 CVE publish

---

2018/1xxx/CVE-2018-1674.json
2018/1xxx/CVE-2018-1800.json

Added CVE-2018-1674 and CVE-2018-1800.

Ibm20180920 102126

---

2018/1xxx/CVE-2018-1685.json
2018/1xxx/CVE-2018-1710.json
2018/1xxx/CVE-2018-1711.json

Added CVE-2018-1685, CVE-2018-1710, and CVE-2018-1711.

Ibm20180921 8153

---

2018/1xxx/CVE-2018-1539.json
2018/1xxx/CVE-2018-1560.json
2018/1xxx/CVE-2018-1588.json
2018/1xxx/CVE-2018-1607.json
2018/1xxx/CVE-2018-1659.json
2018/1xxx/CVE-2018-1664.json
2018/1xxx/CVE-2018-1669.json

Added CVE-2018-1539, CVE-2018-1560, CVE-2018-1588, CVE-2018-1607, CVE-2018-1659, CVE-2018-1664, and CVE-2018-1669.

Ibm20180925 11345

---

2018/1xxx/CVE-2018-1545.json
2018/1xxx/CVE-2018-1550.json
2018/1xxx/CVE-2018-1610.json
2018/1xxx/CVE-2018-1683.json
2018/1xxx/CVE-2018-1768.json
2018/1xxx/CVE-2018-1785.json

Added CVE-2018-1545, CVE-2018-1550, CVE-2018-1610, CVE-2018-1683, CVE-2018-1768, and CVE-2018-1785.

Ibm20180926 103718

---

2018/11xxx/CVE-2018-11073.json
2018/11xxx/CVE-2018-11074.json
2018/11xxx/CVE-2018-11075.json
2018/15xxx/CVE-2018-15764.json
2018/1xxx/CVE-2018-1246.json
2018/1xxx/CVE-2018-1250.json
2018/1xxx/CVE-2018-1251.json

Publish CVE-2018-1246, 1250, 1251, 11073, 11074, 11075, 15764

---

2018/1xxx/CVE-2018-1420.json
2018/1xxx/CVE-2018-1672.json

Added CVE-2018-1420 and CVE-2018-1672.

Ibm20181001 94430

---

2017/1xxx/CVE-2017-1649.json
2018/1xxx/CVE-2018-1395.json
2018/1xxx/CVE-2018-1403.json
2018/1xxx/CVE-2018-1404.json
2018/1xxx/CVE-2018-1405.json
2018/1xxx/CVE-2018-1439.json
2018/1xxx/CVE-2018-1440.json
2018/1xxx/CVE-2018-1498.json
2018/1xxx/CVE-2018-1509.json
2018/1xxx/CVE-2018-1522.json
2018/1xxx/CVE-2018-1557.json
2018/1xxx/CVE-2018-1558.json
2018/1xxx/CVE-2018-1593.json
2018/1xxx/CVE-2018-1601.json
2018/1xxx/CVE-2018-1605.json
2018/1xxx/CVE-2018-1691.json
2018/1xxx/CVE-2018-1692.json

CVE-2017-1649, CVE-2018-1395, CVE-2018-1403, CVE-2018-1404, CVE-2018-1405, CVE-2018-1439, CVE-2018-1440, CVE-2018-1498, CVE-2018-1509, CVE-2018-1522, CVE-2018-1557, CVE-2018-1558, CVE-2018-1593, CVE-2018-1601, CVE-2018-1605, CVE-2018-1691, and CVE-2018-1692.

Ibm20181002 101722

---

2018/12xxx/CVE-2018-12473.json

information for CVE-2018-12473

---

2018/1xxx/CVE-2018-1647.json
2018/1xxx/CVE-2018-1649.json
2018/1xxx/CVE-2018-1686.json
2018/1xxx/CVE-2018-1723.json
2018/1xxx/CVE-2018-1783.json
2018/1xxx/CVE-2018-1795.json
2018/1xxx/CVE-2018-1812.json

Added CVE-2018-1647, CVE-2018-1649, CVE-2018-1686, CVE-2018-1723, CVE-2018-1783, CVE-2018-1795, and CVE-2018-1812.

Ibm20181005 83425

---

2018/0xxx/CVE-2018-0464.json

Adding Cisco CVE  CVE-2018-0464 - Cisco Data Center Network Manager Path Traversal Vulnerability

Adding Cisco CVE-2018-0464

---

2018/0xxx/CVE-2018-0404.json

Adding Cisco CVE-2018-0404 for Cisco RV180W Wireless-N Multifunction VPN Router SQL Injection Vulnerability

Adding Cisco CVE-2018-0404

---

2018/1xxx/CVE-2018-1723.json
2018/1xxx/CVE-2018-1741.json
2018/1xxx/CVE-2018-1742.json
2018/1xxx/CVE-2018-1743.json
2018/1xxx/CVE-2018-1749.json
2018/1xxx/CVE-2018-1750.json
2018/1xxx/CVE-2018-1753.json

Added CVE-2018-1741, CVE-2018-1742, CVE-2018-1743, CVE-2018-1749, CVE-2018-1750, and CVE-2018-1753.  Updated description for CVE-2018-1723.

Ibm20181008 85451

---

2018/1xxx/CVE-2018-1706.json
2018/1xxx/CVE-2018-1708.json
2018/1xxx/CVE-2018-1724.json
2018/1xxx/CVE-2018-1738.json
2018/1xxx/CVE-2018-1745.json

CVE-2018-1706, CVE-2018-1708, CVE-2018-1724, CVE-2018-1738, and CVE-2018-1745.

Ibm20181009 93812

---

2018/1xxx/CVE-2018-1533.json
2018/1xxx/CVE-2018-1534.json
2018/1xxx/CVE-2018-1770.json
2018/1xxx/CVE-2018-1844.json

Added CVE-2018-1533, CVE-2018-1534, CVE-2018-1770, and CVE-2018-1844.

Ibm20181012 65444

---

2018/15xxx/CVE-2018-15378.json

Adding clamAV CVE-2018-15378

---

2018/0xxx/CVE-2018-0388.json

Adding Cisco CVE-2018-0388

---

2018/0xxx/CVE-2018-0416.json

Adding Cisco CVE-2018-0416

---

2018/0xxx/CVE-2018-0395.json

Correcting Cisco CVE-2018-0395

Correcting Cisco CVE-2018-0395

---

2018/0xxx/CVE-2018-0395.json
2018/0xxx/CVE-2018-0456.json

Adding Cisco CVE-2018-0456

---

2018/0xxx/CVE-2018-0395.json
2018/15xxx/CVE-2018-15395.json

Adding Cisco CVE-2018-15395

---

2018/0xxx/CVE-2018-0395.json
2018/15xxx/CVE-2018-15402.json

Adding Cisco CVE-2018-15402

---

2018/0xxx/CVE-2018-0378.json

Adding Cisco CVE-2018-0378

---

2018/0xxx/CVE-2018-0417.json

Adding Cisco CVE-2018-0417

---

2018/0xxx/CVE-2018-0395.json
2018/0xxx/CVE-2018-0420.json

Adding Cisco CVE-2018-0420

---

2018/0xxx/CVE-2018-0395.json
2018/0xxx/CVE-2018-0441.json

Adding Cisco CVE-2018-0441

---

2018/0xxx/CVE-2018-0395.json
2018/0xxx/CVE-2018-0443.json

Adding Cisco CVE-2018-0443

---

2017/18xxx/CVE-2017-18170.json
2017/18xxx/CVE-2017-18171.json
2017/18xxx/CVE-2017-18172.json
2017/18xxx/CVE-2017-18277.json
2017/18xxx/CVE-2017-18282.json
2017/18xxx/CVE-2017-18283.json
2017/18xxx/CVE-2017-18292.json
2017/18xxx/CVE-2017-18293.json
2017/18xxx/CVE-2017-18294.json
2017/18xxx/CVE-2017-18295.json
2017/18xxx/CVE-2017-18296.json
2017/18xxx/CVE-2017-18297.json
2017/18xxx/CVE-2017-18298.json
2017/18xxx/CVE-2017-18299.json
2017/18xxx/CVE-2017-18300.json
2017/18xxx/CVE-2017-18303.json
2017/18xxx/CVE-2017-18304.json
2017/18xxx/CVE-2017-18305.json
2017/18xxx/CVE-2017-18312.json
2017/18xxx/CVE-2017-18313.json

Qualcomm CVE publish

---

2018/15xxx/CVE-2018-15442.json

Adding Cisco CVE-2018-15442: Cisco Webex Meetings Desktop App Update Service Command Injection Vulnerability

Adding Cisco CVE-2018-15442

---

2017/18xxx/CVE-2017-18124.json
2017/18xxx/CVE-2017-18308.json
2017/18xxx/CVE-2017-18309.json
2017/18xxx/CVE-2017-18310.json
2017/18xxx/CVE-2017-18311.json
2018/11xxx/CVE-2018-11305.json
2018/11xxx/CVE-2018-11821.json
2018/11xxx/CVE-2018-11822.json
2018/11xxx/CVE-2018-11824.json
2018/11xxx/CVE-2018-11828.json
2018/11xxx/CVE-2018-11846.json
2018/11xxx/CVE-2018-11849.json
2018/11xxx/CVE-2018-11850.json
2018/11xxx/CVE-2018-11853.json
2018/11xxx/CVE-2018-11854.json
2018/11xxx/CVE-2018-11950.json
2018/11xxx/CVE-2018-11951.json
2018/3xxx/CVE-2018-3588.json
2018/5xxx/CVE-2018-5866.json
2018/5xxx/CVE-2018-5914.json

Qualcomm 10/26/2018 CVE publish

Qualcomm 10/26/2018 CVE publish

---

CONTRIBUTING.md

typo fix epxlicitly to explicitly

---

2017/18xxx/CVE-2017-18281.json
2018/11xxx/CVE-2018-11856.json
2018/11xxx/CVE-2018-11857.json
2018/11xxx/CVE-2018-11858.json
2018/11xxx/CVE-2018-11859.json
2018/11xxx/CVE-2018-11861.json
2018/11xxx/CVE-2018-11862.json
2018/11xxx/CVE-2018-11865.json
2018/11xxx/CVE-2018-11866.json
2018/11xxx/CVE-2018-11867.json
2018/11xxx/CVE-2018-11870.json
2018/11xxx/CVE-2018-11871.json
2018/11xxx/CVE-2018-11872.json
2018/11xxx/CVE-2018-11873.json
2018/11xxx/CVE-2018-11874.json
2018/11xxx/CVE-2018-11875.json
2018/11xxx/CVE-2018-11876.json
2018/11xxx/CVE-2018-11877.json
2018/11xxx/CVE-2018-11879.json
2018/11xxx/CVE-2018-11880.json
2018/11xxx/CVE-2018-11882.json
2018/11xxx/CVE-2018-11884.json

Qualcomm 10/29/2018 CVE publish

Qualcomm 10/29/2018 CVE publish

---

2018/1xxx/CVE-2018-1851.json

Ibm20181031 83213

---

2018/13xxx/CVE-2018-13281.json

Synology-SA-18:36

---

2018/13xxx/CVE-2018-13282.json

Synology-SA-18:37

---

2018/1xxx/CVE-2018-1606.json
2018/1xxx/CVE-2018-1694.json

Added CVE-2018-1694 and CVE-2018-1606.

Ibm20181106 10141

---

2018/0xxx/CVE-2018-0284.json

Adding Cisco CVE-2018-0284

---

2018/15xxx/CVE-2018-15381.json

Adding Cisco CVE-2018-15381

---

2018/15xxx/CVE-2018-15393.json

Adding Cisco CVE-2018-15393

---

2018/15xxx/CVE-2018-15437.json

Adding Cisco CVE-2018-15437

---

2018/15xxx/CVE-2018-15439.json

Adding Cisco CVE-2018-15439

---

2018/15xxx/CVE-2018-15443.json

Adding Cisco CVE-2018-15443

---

2018/15xxx/CVE-2018-15445.json

Adding Cisco CVE-2018-15445

---

2018/15xxx/CVE-2018-15446.json

Adding Cisco CVE-2018-15446

---

2018/15xxx/CVE-2018-15448.json

Adding Cisco CVE-2018-15448

---

2018/15xxx/CVE-2018-15449.json

Adding Cisco CVE-2018-15449

---

2018/15xxx/CVE-2018-15450.json

Adding Cisco CVE-2018-15450

---

2016/9xxx/CVE-2016-9749.json
2017/1xxx/CVE-2017-1119.json
2018/1xxx/CVE-2018-1684.json
2018/1xxx/CVE-2018-1774.json
2018/1xxx/CVE-2018-1780.json
2018/1xxx/CVE-2018-1781.json
2018/1xxx/CVE-2018-1799.json
2018/1xxx/CVE-2018-1802.json
2018/1xxx/CVE-2018-1834.json
2018/1xxx/CVE-2018-1842.json
2018/1xxx/CVE-2018-1857.json

Added CVE-2016-9749, CVE-2017-1119, CVE-2018-1684, CVE-2018-1774, CVE-2018-1780, CVE-2018-1781, CVE-2018-1799, CVE-2018-1802, CVE-2018-1834, CVE-2018-1842, and CVE-2018-1857.

Ibm20181108 181920

---

2018/1xxx/CVE-2018-1872.json

Ibm20181109 105737

---

2018/1xxx/CVE-2018-1786.json
2018/1xxx/CVE-2018-1798.json
2018/1xxx/CVE-2018-1884.json

Added CVE-2018-1786, CVE-2018-1798, and CVE-2018-1884.

Ibm20181112 103316

---

2018/15xxx/CVE-2018-15452.json

Adding Cisco CVE-2018-15452

---

2018/0xxx/CVE-2018-0673.json
2018/0xxx/CVE-2018-0679.json
2018/0xxx/CVE-2018-0680.json
2018/0xxx/CVE-2018-0681.json
2018/0xxx/CVE-2018-0682.json
2018/0xxx/CVE-2018-0683.json
2018/0xxx/CVE-2018-0684.json
2018/0xxx/CVE-2018-0685.json
2018/0xxx/CVE-2018-0686.json
2018/0xxx/CVE-2018-0687.json
2018/0xxx/CVE-2018-0690.json
2018/0xxx/CVE-2018-0691.json
2018/0xxx/CVE-2018-0692.json
2018/0xxx/CVE-2018-0693.json
2018/0xxx/CVE-2018-0694.json
2018/0xxx/CVE-2018-0695.json
2018/0xxx/CVE-2018-0697.json
2018/0xxx/CVE-2018-0699.json
2018/0xxx/CVE-2018-0700.json
2018/0xxx/CVE-2018-0701.json
2018/16xxx/CVE-2018-16160.json
2018/16xxx/CVE-2018-16161.json
2018/16xxx/CVE-2018-16162.json
2018/16xxx/CVE-2018-16163.json

JPCERT20181109

---

2018/1xxx/CVE-2018-1643.json

Ibm20181115 10656

---

2018/1xxx/CVE-2018-1639.json
2018/1xxx/CVE-2018-1797.json

Added CVE-2018-1639 and CVE-2018-1797.

Ibm20181116 1014

---

2018/1xxx/CVE-2018-1841.json

Ibm20181119 81227

---

2018/1xxx/CVE-2018-1779.json

Ibm20181120 75915

---

2018/1xxx/CVE-2018-1843.json

Ibm20181121 9186

---

2017/11xxx/CVE-2017-11078.json
2018/11xxx/CVE-2018-11260.json
2018/11xxx/CVE-2018-11261.json
2018/11xxx/CVE-2018-11266.json
2018/11xxx/CVE-2018-11823.json
2018/11xxx/CVE-2018-11906.json
2018/11xxx/CVE-2018-11907.json
2018/11xxx/CVE-2018-11908.json
2018/11xxx/CVE-2018-11909.json
2018/11xxx/CVE-2018-11910.json
2018/11xxx/CVE-2018-11911.json
2018/11xxx/CVE-2018-11912.json
2018/11xxx/CVE-2018-11913.json
2018/11xxx/CVE-2018-11914.json
2018/11xxx/CVE-2018-11918.json
2018/11xxx/CVE-2018-11919.json
2018/11xxx/CVE-2018-11943.json
2018/11xxx/CVE-2018-11946.json
2018/11xxx/CVE-2018-11956.json
2018/11xxx/CVE-2018-11995.json
2018/5xxx/CVE-2018-5856.json
2018/5xxx/CVE-2018-5861.json
2018/5xxx/CVE-2018-5904.json
2018/5xxx/CVE-2018-5906.json
2018/5xxx/CVE-2018-5908.json
2018/5xxx/CVE-2018-5909.json
2018/5xxx/CVE-2018-5910.json
2018/5xxx/CVE-2018-5919.json

Qualcomm 11-21-18 CVE Publish

---

2017/18xxx/CVE-2017-18315.json
2017/18xxx/CVE-2017-18316.json
2017/18xxx/CVE-2017-18317.json
2017/18xxx/CVE-2017-18318.json
2018/11xxx/CVE-2018-11264.json
2018/11xxx/CVE-2018-11921.json
2018/11xxx/CVE-2018-11994.json
2018/11xxx/CVE-2018-11996.json
2018/5xxx/CVE-2018-5870.json
2018/5xxx/CVE-2018-5877.json
2018/5xxx/CVE-2018-5912.json
2018/5xxx/CVE-2018-5916.json
2018/5xxx/CVE-2018-5917.json
2018/5xxx/CVE-2018-5918.json

Qualcomm 11-28-2018 CVE publish

Qualcomm 11-28-2018 CVE publish

---

2018/15xxx/CVE-2018-15441.json

Adding Cisco CVE-2018-15441

---

2018/1xxx/CVE-2018-1762.json

Ibm20181129 11321

---

2018/1xxx/CVE-2018-1897.json
2018/1xxx/CVE-2018-1927.json
2018/1xxx/CVE-2018-1928.json

Added  CVE-2018-1897, CVE-2018-1927, and CVE-2018-1928.

Ibm20181130 83841

---

2018/6xxx/CVE-2018-6332.json

Publishing details for CVE-2018-6332

Publish details for CVE-2018-6332

---

2018/1xxx/CVE-2018-1840.json

Ibm20181203 9320

---

2018/1002xxx/CVE-2018-1002000.json
2018/1002xxx/CVE-2018-1002001.json
2018/1002xxx/CVE-2018-1002002.json
2018/1002xxx/CVE-2018-1002003.json
2018/1002xxx/CVE-2018-1002004.json
2018/1002xxx/CVE-2018-1002005.json
2018/1002xxx/CVE-2018-1002006.json
2018/1002xxx/CVE-2018-1002007.json
2018/1002xxx/CVE-2018-1002008.json
2018/1002xxx/CVE-2018-1002009.json

manually entering in https://github.com/distributedweaknessfiling/cvelist/pull/21/files

Larry Cashdollar

---

2017/1xxx/CVE-2017-1622.json
2018/1xxx/CVE-2018-1568.json
2018/1xxx/CVE-2018-1648.json
2018/1xxx/CVE-2018-1650.json
2018/1xxx/CVE-2018-1697.json
2018/1xxx/CVE-2018-1728.json
2018/1xxx/CVE-2018-1730.json
2018/1xxx/CVE-2018-1732.json
2018/1xxx/CVE-2018-1941.json

Added CVE-2017-1622, CVE-2018-1568, CVE-2018-1648, CVE-2018-1650, CVE-2018-1697, CVE-2018-1728, CVE-2018-1730, CVE-2018-1732, and CVE-2018-1941.

Ibm20181205 113429

---

2017/14xxx/CVE-2017-14888.json
2017/15xxx/CVE-2017-15835.json
2018/11xxx/CVE-2018-11905.json

Qualcomm 12-7-2018 CVE publish

Qualcomm 12-7-2018 CVE publish

---

2018/1xxx/CVE-2018-1671.json
2018/1xxx/CVE-2018-1957.json

Added CVE-2018-1957 and CVE-2018-1671.

Ibm20181210 82835

---

2016/10xxx/CVE-2016-10502.json

Qualcomm-12-10-2018 CVE publish

Qualcomm-12-10-2018 CVE publish

---

2017/5xxx/CVE-2017-5133.json
2018/17xxx/CVE-2018-17480.json
2018/17xxx/CVE-2018-17481.json
2018/18xxx/CVE-2018-18335.json
2018/18xxx/CVE-2018-18336.json
2018/18xxx/CVE-2018-18337.json
2018/18xxx/CVE-2018-18338.json
2018/18xxx/CVE-2018-18339.json
2018/18xxx/CVE-2018-18340.json
2018/18xxx/CVE-2018-18341.json
2018/18xxx/CVE-2018-18342.json
2018/18xxx/CVE-2018-18343.json
2018/18xxx/CVE-2018-18344.json
2018/18xxx/CVE-2018-18345.json
2018/18xxx/CVE-2018-18346.json
2018/18xxx/CVE-2018-18347.json
2018/18xxx/CVE-2018-18348.json
2018/18xxx/CVE-2018-18349.json
2018/18xxx/CVE-2018-18350.json
2018/18xxx/CVE-2018-18351.json
2018/18xxx/CVE-2018-18352.json
2018/18xxx/CVE-2018-18353.json
2018/18xxx/CVE-2018-18354.json
2018/18xxx/CVE-2018-18355.json
2018/18xxx/CVE-2018-18356.json
2018/18xxx/CVE-2018-18357.json
2018/18xxx/CVE-2018-18358.json
2018/18xxx/CVE-2018-18359.json

A few more to follow. Also includes a typo fix for CVE-2017-5133

CVE descriptions for Chrome Release-0-M71

---

2018/1xxx/CVE-2018-1833.json

Ibm20181218 94711

---

2017/9xxx/CVE-2017-9704.json
2018/11xxx/CVE-2018-11960.json
2018/11xxx/CVE-2018-11961.json
2018/11xxx/CVE-2018-11963.json
2018/11xxx/CVE-2018-11964.json
2018/11xxx/CVE-2018-11965.json
2018/11xxx/CVE-2018-11983.json
2018/11xxx/CVE-2018-11984.json
2018/11xxx/CVE-2018-11985.json
2018/11xxx/CVE-2018-11986.json
2018/11xxx/CVE-2018-11987.json
2018/11xxx/CVE-2018-11988.json

Qualcomm_12-20-2018 CVE publish

Qualcomm_12-20-2018 CVE publish

---

2018/0xxx/CVE-2018-0197.json
2018/15xxx/CVE-2018-15465.json

Adding Cisco CVE-2018-15465

---

2018/8xxx/CVE-2018-8918.json

Synology-SA-18:25

---

2018/8xxx/CVE-2018-8917.json
2018/8xxx/CVE-2018-8919.json
2018/8xxx/CVE-2018-8920.json

Added CVE-2018-8917, CVE-2018-8919, and CVE-2018-8920.

Synology-SA-18:14

---

2018/6xxx/CVE-2018-6337.json
2018/6xxx/CVE-2018-6340.json
2018/6xxx/CVE-2018-6341.json
2018/6xxx/CVE-2018-6342.json
2018/6xxx/CVE-2018-6343.json
2018/6xxx/CVE-2018-6344.json

Uploading the latest batch for review.

Publish more 2018 CVEs from the Facebook CNA

---

2017/11xxx/CVE-2017-11004.json
2017/18xxx/CVE-2017-18141.json
2017/18xxx/CVE-2017-18319.json
2017/18xxx/CVE-2017-18320.json
2017/18xxx/CVE-2017-18321.json
2017/18xxx/CVE-2017-18322.json
2017/18xxx/CVE-2017-18323.json
2017/18xxx/CVE-2017-18324.json
2017/18xxx/CVE-2017-18326.json
2017/18xxx/CVE-2017-18327.json
2017/18xxx/CVE-2017-18328.json
2017/18xxx/CVE-2017-18329.json
2017/18xxx/CVE-2017-18330.json

Qualcomm_1-3-2019 CVE publish

---

2018/0xxx/CVE-2018-0282.json

Adding Cisco CVE-2018-0282

---

2018/0xxx/CVE-2018-0449.json

Adding Cisco CVE-2018-0449

---

2018/0xxx/CVE-2018-0461.json

Adding Cisco CVE-2018-0461

---

2018/0xxx/CVE-2018-0474.json

Adding Cisco CVE-2018-0474

---

2018/0xxx/CVE-2018-0482.json

Adding Cisco CVE-2018-0482

---

2018/0xxx/CVE-2018-0483.json

Adding Cisco CVE-2018-0483

---

2018/0xxx/CVE-2018-0484.json

Adding Cisco CVE-2018-0484

---

2018/15xxx/CVE-2018-15453.json

Adding Cisco CVE-2018-15453

---

2018/15xxx/CVE-2018-15456.json

Adding Cisco CVE-2018-15456

---

2018/15xxx/CVE-2018-15457.json

Adding Cisco CVE-2018-15457

---

2018/15xxx/CVE-2018-15458.json

Adding Cisco CVE-2018-15458

---

2018/15xxx/CVE-2018-15460.json

Adding Cisco CVE-2018-15460

---

2018/15xxx/CVE-2018-15461.json

Adding Cisco CVE-2018-15461

---

2018/15xxx/CVE-2018-15466.json

Adding Cisco CVE-2018-15466

---

2018/15xxx/CVE-2018-15467.json

Adding Cisco CVE-2018-15467

---

2018/1xxx/CVE-2018-1772.json

Ibm20190115 122341

---

2018/15xxx/CVE-2018-15440.json

Adding Cisco CVE-2018-15440

---

2018/15xxx/CVE-2018-15463.json

Adding Cisco CVE-2018-15463

---

2017/18xxx/CVE-2017-18160.json
2017/18xxx/CVE-2017-18331.json
2017/18xxx/CVE-2017-18332.json
2017/8xxx/CVE-2017-8276.json
2018/11xxx/CVE-2018-11279.json
2018/11xxx/CVE-2018-11284.json
2018/11xxx/CVE-2018-11288.json
2018/11xxx/CVE-2018-11993.json
2018/11xxx/CVE-2018-11998.json
2018/11xxx/CVE-2018-11999.json
2018/3xxx/CVE-2018-3595.json
2018/5xxx/CVE-2018-5867.json
2018/5xxx/CVE-2018-5868.json
2018/5xxx/CVE-2018-5869.json
2018/5xxx/CVE-2018-5879.json
2018/5xxx/CVE-2018-5880.json
2018/5xxx/CVE-2018-5881.json
2018/5xxx/CVE-2018-5915.json

Qualcomm_1-17-2019 CVE publish

Qualcomm_1-17-2019 CVE publish

---

2019/3xxx/CVE-2019-3587.json

Security bulletin due to be released late on 22 Jan or early 23 Jan

First publishing of CVE-2019-3587

---

2019/3xxx/CVE-2019-3584.json

McAfee publishing Security Bulletin late on 22 January or early 23 January

First publish of CVE-2019-3854

---

2018/0xxx/CVE-2018-0187.json

Adding Cisco CVE-2018-0187

---

2018/15xxx/CVE-2018-15459.json

Adding Cisco CVE-2018-15459

---

2019/1xxx/CVE-2019-1636.json

Adding Cisco CVE-2019-1636

---

2019/1xxx/CVE-2019-1637.json

Adding Cisco CVE-2019-1637

---

2019/1xxx/CVE-2019-1638.json

Adding Cisco CVE-2019-1638

---

2019/1xxx/CVE-2019-1640.json

Adding Cisco CVE-2019-1640

---

2019/1xxx/CVE-2019-1641.json

Adding Cisco CVE-2019-1641

---

2019/1xxx/CVE-2019-1642.json

Adding Cisco CVE-2019-1642

---

2019/1xxx/CVE-2019-1643.json

Adding Cisco CVE-2019-1643

---

2019/1xxx/CVE-2019-1644.json

Adding Cisco CVE-2019-1644

---

2019/1xxx/CVE-2019-1645.json

Adding Cisco CVE-2019-1645

---

2019/1xxx/CVE-2019-1647.json

Adding Cisco CVE-2019-1647

---

2019/1xxx/CVE-2019-1648.json

Adding Cisco CVE-2019-1648

---

2019/1xxx/CVE-2019-1650.json

Adding Cisco CVE-2019-1650

---

2019/1xxx/CVE-2019-1651.json

Adding Cisco CVE-2019-1651

---

2019/1xxx/CVE-2019-1652.json

Adding Cisco CVE-2019-1652

---

2019/1xxx/CVE-2019-1653.json

Adding Cisco CVE-2019-1653

---

2019/1xxx/CVE-2019-1655.json

Adding Cisco CVE-2019-1655

---

2019/1xxx/CVE-2019-1657.json

Adding Cisco CVE-2019-1657

---

2019/1xxx/CVE-2019-1658.json

Adding Cisco CVE-2019-1658

---

2019/1xxx/CVE-2019-1668.json

Adding Cisco CVE-2019-1668

---

2019/1xxx/CVE-2019-1669.json

Adding Cisco CVE-2019-1669

---

2018/1xxx/CVE-2018-1959.json

Ibm20190124 10513

---

2019/3xxx/CVE-2019-3593.json

First publication of 3593 - related TS going our 28 Jan

Publish request - 3593

---

2018/1xxx/CVE-2018-1668.json
2018/1xxx/CVE-2018-1733.json
2018/1xxx/CVE-2018-1976.json

Added CVE-2018-1668, CVE-2018-1733, and CVE-2018-1976.

Ibm20190129 10142

---

2019/3xxx/CVE-2019-3604.json

Publishing 2019-3604

---

2017/1xxx/CVE-2017-1177.json
2017/1xxx/CVE-2017-1198.json
2017/1xxx/CVE-2017-1200.json
2017/1xxx/CVE-2017-1202.json

Added CVE-2017-1200, CVE-2017-1198, CVE-2017-1177, and CVE-2017-1202.

Ibm20190205 122450

---

2016/5xxx/CVE-2016-5393.json
2017/9xxx/CVE-2017-9798.json
2017/9xxx/CVE-2017-9805.json

Remove version numbers incorrectly polluting the product_name field

---

2018/1xxx/CVE-2018-1666.json
2019/4xxx/CVE-2019-4008.json

Added CVE-2018-1666 and CVE-2019-4008.

Ibm20190207 95152

---

2019/1xxx/CVE-2019-1660.json

Adding Cisco CVE-2019-1660

---

2019/1xxx/CVE-2019-1661.json

Adding Cisco CVE-2019-1661

---

2019/1xxx/CVE-2019-1670.json

Adding Cisco CVE-2019-1670

---

2019/1xxx/CVE-2019-1671.json

Adding Cisco CVE-2019-1671

---

2018/16xxx/CVE-2018-16099.json
2018/16xxx/CVE-2018-16100.json
2018/16xxx/CVE-2018-16101.json
2018/16xxx/CVE-2018-16102.json
2018/16xxx/CVE-2018-16103.json
2018/16xxx/CVE-2018-16104.json
2018/16xxx/CVE-2018-16105.json
2018/16xxx/CVE-2018-16106.json
2018/16xxx/CVE-2018-16107.json
2018/16xxx/CVE-2018-16108.json
2018/16xxx/CVE-2018-16109.json
2018/16xxx/CVE-2018-16110.json
2018/16xxx/CVE-2018-16111.json
2018/16xxx/CVE-2018-16112.json
2018/16xxx/CVE-2018-16113.json

2018 CVE Rejections

---

2019/1xxx/CVE-2019-1688.json

Adding Cisco CVE-2019-1688

---

2019/3xxx/CVE-2019-3610.json

the TS will go live around 3pm UK time on 13 Feb 2019

Publishing CVE-2019-3610

---

2018/0xxx/CVE-2018-0696.json
2018/16xxx/CVE-2018-16189.json
2018/16xxx/CVE-2018-16190.json
2019/5xxx/CVE-2019-5909.json
2019/5xxx/CVE-2019-5910.json
2019/5xxx/CVE-2019-5911.json
2019/5xxx/CVE-2019-5912.json
2019/5xxx/CVE-2019-5913.json
2019/5xxx/CVE-2019-5914.json
2019/5xxx/CVE-2019-5915.json
2019/5xxx/CVE-2019-5916.json

- CVE-2018-0696
- CVE-2018-16189
- CVE-2018-16190
- CVE-2019-5909
- CVE-2019-5910
- CVE-2019-5911
- CVE-2019-5912
- CVE-2019-5913
- CVE-2019-5914
- CVE-2019-5915
- CVE-2019-5916

JPCERT 2019-02-13 batch

---

2019/5xxx/CVE-2019-5754.json
2019/5xxx/CVE-2019-5755.json
2019/5xxx/CVE-2019-5756.json
2019/5xxx/CVE-2019-5757.json
2019/5xxx/CVE-2019-5758.json
2019/5xxx/CVE-2019-5759.json
2019/5xxx/CVE-2019-5760.json
2019/5xxx/CVE-2019-5761.json
2019/5xxx/CVE-2019-5762.json
2019/5xxx/CVE-2019-5763.json
2019/5xxx/CVE-2019-5764.json
2019/5xxx/CVE-2019-5765.json
2019/5xxx/CVE-2019-5766.json
2019/5xxx/CVE-2019-5767.json
2019/5xxx/CVE-2019-5768.json
2019/5xxx/CVE-2019-5769.json
2019/5xxx/CVE-2019-5770.json
2019/5xxx/CVE-2019-5771.json
2019/5xxx/CVE-2019-5772.json
2019/5xxx/CVE-2019-5773.json
2019/5xxx/CVE-2019-5774.json
2019/5xxx/CVE-2019-5775.json
2019/5xxx/CVE-2019-5776.json
2019/5xxx/CVE-2019-5777.json
2019/5xxx/CVE-2019-5778.json
2019/5xxx/CVE-2019-5779.json
2019/5xxx/CVE-2019-5780.json
2019/5xxx/CVE-2019-5781.json
2019/5xxx/CVE-2019-5782.json
2019/5xxx/CVE-2019-5783.json

Submitting now we've rolled out to 100%

Info for CVEs issued for Chrome Browser Release-0-M72

---

2019/3xxx/CVE-2019-3474.json
2019/3xxx/CVE-2019-3475.json

Publish CVE-2019-3474 and CVE-2019-3475

Publish CVE-2019-3474 and CVE-2019-3475

---

2018/15xxx/CVE-2018-15380.json

Adding Cisco CVE-2018-15380

---

2018/6xxx/CVE-2018-6687.json

Our Security Bulletin is being published before noon Central US time.

Late publishing of CVE-2018-6687

---

2019/1xxx/CVE-2019-1659.json

Adding Cisco CVE-2019-1659

---

2019/1xxx/CVE-2019-1662.json

Adding Cisco CVE-2019-1662

---

2018/1xxx/CVE-2018-1944.json
2018/1xxx/CVE-2018-1945.json
2018/1xxx/CVE-2018-1946.json
2018/1xxx/CVE-2018-1947.json
2018/1xxx/CVE-2018-1948.json
2018/1xxx/CVE-2018-1949.json
2018/1xxx/CVE-2018-1950.json
2018/2xxx/CVE-2018-2006.json

Added CVE-2018-1944, CVE-2018-1945, CVE-2018-1946, CVE-2018-1947, CVE-2018-1948, CVE-2018-1949, CVE-2018-1950, and CVE-2018-2006.

Ibm20190221 11716

---

2019/1xxx/CVE-2019-1664.json

Adding Cisco CVE-2019-1664

---

2019/1xxx/CVE-2019-1665.json

Adding Cisco CVE-2019-1665

---

2019/1xxx/CVE-2019-1666.json

Adding Cisco CVE-2019-1666

---

2019/1xxx/CVE-2019-1667.json

Adding Cisco CVE-2019-1667

---

2019/1xxx/CVE-2019-1681.json

Adding Cisco CVE-2019-1681

---

2019/1xxx/CVE-2019-1684.json

Adding Cisco CVE-2019-1684

---

2019/1xxx/CVE-2019-1685.json

Adding Cisco CVE-2019-1685

---

2019/1xxx/CVE-2019-1691.json

Adding Cisco CVE-2019-1691

---

2019/1xxx/CVE-2019-1698.json

Adding Cisco CVE-2019-1698

---

2019/1xxx/CVE-2019-1700.json

Adding Cisco CVE-2019-1700

---

2019/1xxx/CVE-2019-1683.json

Adding Cisco CVE-2019-1683

---

2019/1xxx/CVE-2019-1689.json

Adding Cisco CVE-2019-1689

---

2018/1xxx/CVE-2018-1775.json
2019/4xxx/CVE-2019-4061.json

Added CVE-2018-1775 and CVE-2019-4061.

Ibm20190226 93758

---

2019/3xxx/CVE-2019-3598.json

Publishing CVE-2019-3598

---

2019/3xxx/CVE-2019-3599.json

Publishing CVE-2019-3599

---

2019/1xxx/CVE-2019-1663.json

Adding Cisco CVE-2019-1663

---

2019/1xxx/CVE-2019-1674.json

Adding Cisco CVE-2019-1674

---

2019/1xxx/CVE-2019-1543.json

ChaCha20-Poly1305 with long nonces

Add OpenSSL CVE-2019-1543

---

2019/1xxx/CVE-2019-1585.json

Adding Cisco CVE-2019-1585

---

2019/1xxx/CVE-2019-1588.json

Adding Cisco CVE-2019-1588

---

2019/1xxx/CVE-2019-1591.json

Adding Cisco CVE-2019-1591

---

2019/1xxx/CVE-2019-1593.json

Adding Cisco CVE-2019-1593

---

2019/1xxx/CVE-2019-1594.json

Adding Cisco CVE-2019-1594

---

2019/1xxx/CVE-2019-1595.json

Adding Cisco CVE-2019-1595

---

2019/1xxx/CVE-2019-1596.json

Adding Cisco CVE-2019-1596

---

2019/1xxx/CVE-2019-1597.json

Adding Cisco CVE-2019-1597

---

2019/1xxx/CVE-2019-1598.json

Adding Cisco CVE-2019-1598

---

2019/1xxx/CVE-2019-1599.json

Adding Cisco CVE-2019-1599

---

2019/1xxx/CVE-2019-1600.json

Adding Cisco CVE-2019-1600

---

2019/1xxx/CVE-2019-1602.json

Adding Cisco CVE-2019-1602

---

2019/1xxx/CVE-2019-1603.json

Adding Cisco CVE-2019-1603

---

2019/1xxx/CVE-2019-1604.json

Adding Cisco CVE-2019-1604

---

2019/1xxx/CVE-2019-1605.json

Adding Cisco CVE-2019-1605

---

2019/1xxx/CVE-2019-1606.json

Adding Cisco CVE-2019-1606

---

2019/1xxx/CVE-2019-1607.json

Adding Cisco CVE-2019-1607

---

2019/1xxx/CVE-2019-1608.json

Adding Cisco CVE-2019-1608

---

2019/1xxx/CVE-2019-1609.json

Adding Cisco CVE-2019-1609

---

2019/1xxx/CVE-2019-1610.json

Adding Cisco CVE-2019-1610

---

2019/1xxx/CVE-2019-1611.json

Adding Cisco CVE-2019-1611

---

2019/1xxx/CVE-2019-1612.json

Adding Cisco CVE-2019-1612

---

2019/1xxx/CVE-2019-1614.json

Adding Cisco CVE-2019-1614

---

2019/1xxx/CVE-2019-1615.json

Adding Cisco CVE-2019-1615

---

2019/1xxx/CVE-2019-1616.json

Adding Cisco CVE-2019-1616

---

2019/1xxx/CVE-2019-1617.json

Adding Cisco CVE-2019-1617

---

2019/1xxx/CVE-2019-1618.json

Adding Cisco CVE-2019-1618

---

2019/1xxx/CVE-2019-1690.json

Adding Cisco CVE-2019-1690

---

2019/1xxx/CVE-2019-1702.json

Adding Cisco CVE-2019-1702

---

2019/1xxx/CVE-2019-1707.json

Adding Cisco CVE-2019-1707

---

2019/5xxx/CVE-2019-5917.json
2019/5xxx/CVE-2019-5918.json
2019/5xxx/CVE-2019-5919.json
2019/5xxx/CVE-2019-5920.json
2019/5xxx/CVE-2019-5921.json
2019/5xxx/CVE-2019-5922.json
2019/5xxx/CVE-2019-5923.json
2019/5xxx/CVE-2019-5924.json
2019/5xxx/CVE-2019-5925.json

- CVE-2019-5917.json
- CVE-2019-5918.json
- CVE-2019-5919.json
- CVE-2019-5920.json
- CVE-2019-5921.json
- CVE-2019-5922.json
- CVE-2019-5923.json
- CVE-2019-5924.json
- CVE-2019-5925.json

JPCERT 2019-03-12 batch

---

2019/3xxx/CVE-2019-3615.json

Bulletin going live around 10am CST.

Publish CVE-2019-3615

---

2019/1xxx/CVE-2019-1723.json

Adding Cisco CVE-2019-1723

---

2018/1xxx/CVE-2018-1658.json
2018/1xxx/CVE-2018-1688.json
2018/1xxx/CVE-2018-1759.json
2018/1xxx/CVE-2018-1761.json
2018/1xxx/CVE-2018-1763.json
2018/1xxx/CVE-2018-1764.json
2018/1xxx/CVE-2018-1823.json
2018/1xxx/CVE-2018-1824.json
2018/1xxx/CVE-2018-1825.json
2018/1xxx/CVE-2018-1829.json

Added CVE-2018-1658, CVE-2018-1688, CVE-2018-1759, CVE-2018-1761, CVE-2018-1763, CVE-2018-1764, CVE-2018-1823, CVE-2018-1824, CVE-2018-1825, and CVE-2018-1829.

Ibm20190314 101123

---

2018/1xxx/CVE-2018-1908.json
2018/1xxx/CVE-2018-1910.json
2018/1xxx/CVE-2018-1914.json
2018/1xxx/CVE-2018-1916.json
2018/1xxx/CVE-2018-1929.json
2018/1xxx/CVE-2018-1952.json
2018/1xxx/CVE-2018-1982.json
2018/1xxx/CVE-2018-1983.json
2018/1xxx/CVE-2018-1984.json
2019/4xxx/CVE-2019-4034.json

Added CVE-2018-1908, CVE-2018-1910, CVE-2018-1914, CVE-2018-1916, CVE-2018-1929, CVE-2018-1952, CVE-2018-1982, CVE-2018-1983, CVE-2018-1984, and CVE-2019-4034.

Ibm20190314 102130

---

2019/4xxx/CVE-2019-4035.json
2019/4xxx/CVE-2019-4052.json

Added CVE-2019-4035 and CVE-2019-4052.

Ibm20190322 114650

---

2019/4xxx/CVE-2019-4046.json

Ibm20190325 14858

---

2018/16xxx/CVE-2018-16207.json
2019/5xxx/CVE-2019-5926.json
2019/5xxx/CVE-2019-5927.json

* CVE-2018-16207
* CVE-2019-5926
* CVE-2019-5927

jpcert20190327 batch.

---

2018/12xxx/CVE-2018-12546.json
2018/12xxx/CVE-2018-12550.json
2018/12xxx/CVE-2018-12551.json

CVE-2018-12546
CVE-2018-12550
CVE-2018-12551

Eclipse Mosquitto CVEs

---

2019/1xxx/CVE-2019-1752.json

Adding Cisco CVE-2019-1752

---

2019/1xxx/CVE-2019-1753.json

Adding Cisco CVE-2019-1753

---

2019/1xxx/CVE-2019-1756.json

Adding Cisco CVE-2019-1756

---

2019/1xxx/CVE-2019-1755.json

Adding Cisco CVE-2019-1755

---

2019/1xxx/CVE-2019-1754.json

Adding Cisco CVE-2019-1754

---

2019/1xxx/CVE-2019-1758.json

Adding Cisco CVE-2019-1758

---

2019/1xxx/CVE-2019-1757.json

Adding Cisco CVE-2019-1757

---

2019/1xxx/CVE-2019-1761.json

Adding Cisco CVE-2019-1761

---

2019/1xxx/CVE-2019-1760.json

Adding Cisco CVE-2019-1760

---

2019/1xxx/CVE-2019-1759.json

Adding Cisco CVE-2019-1759

---

2019/1xxx/CVE-2019-1762.json

Adding Cisco CVE-2019-1762

---

2019/1002xxx/CVE-2019-1002100.json
2019/1002xxx/CVE-2019-1002101.json

Updating with CVEs allocated from the Kubernetes DWF block

Sync kubernetes CVEs

---

2018/8xxx/CVE-2018-8913.json

Synology-SA-18:29

---

2017/16xxx/CVE-2017-16774.json

Synology-SA-18:26

---

2017/16xxx/CVE-2017-16775.json

Synology-SA-18:28

---

2018/13xxx/CVE-2018-13283.json

Synology-SA-18:30

---

2018/13xxx/CVE-2018-13284.json
2018/13xxx/CVE-2018-13286.json

Added CVE-2018-13284 and CVE-2018-13286.

Synology-SA-18:33

---

2018/13xxx/CVE-2018-13285.json
2018/13xxx/CVE-2018-13287.json

Added CVE-2018-13285 and CVE-2018-13287.

Synology-SA-18:34

---

2018/13xxx/CVE-2018-13288.json

Synology-SA-18:35

---

2018/13xxx/CVE-2018-13289.json
2018/13xxx/CVE-2018-13290.json
2018/13xxx/CVE-2018-13292.json

Added CVE-2018-13289, CVE-2018-13290, and CVE-2018-13292.

Synology-SA-18:48

---

2018/13xxx/CVE-2018-13291.json
2018/13xxx/CVE-2018-13293.json

Added CVE-2018-13291 and CVE-2018-13293.

Synology-SA-18:51

---

2018/13xxx/CVE-2018-13294.json
2018/13xxx/CVE-2018-13295.json

Added CVE-2018-13294 and CVE-2018-13295.

Synology-SA-18:40

---

2018/13xxx/CVE-2018-13296.json

Synology-SA-18:43

---

2018/13xxx/CVE-2018-13297.json

Synology-SA-18:50

---

2018/13xxx/CVE-2018-13298.json

Synology-SA-18:52

---

2018/13xxx/CVE-2018-13299.json

Synology-SA-18:54

---

2018/1xxx/CVE-2018-1731.json
2018/1xxx/CVE-2018-1913.json
2018/1xxx/CVE-2018-1936.json
2019/4xxx/CVE-2019-4014.json

Added CVE-2018-1731, CVE-2018-1913, CVE-2018-1936, and CVE-2019-4014.

Ibm20190403 93956

---

2019/1xxx/CVE-2019-1827.json

Adding Cisco CVE-2019-1827

---

2019/1xxx/CVE-2019-1828.json

Adding Cisco CVE-2019-1828

---

2019/1xxx/CVE-2019-1786.json

Adding ClamAV CVE-2019-1786

---

2019/1xxx/CVE-2019-1785.json

Adding ClamAV CVE-2019-1785

---

2019/1xxx/CVE-2019-1787.json

Adding ClamAV CVE-2019-1787

---

2019/1xxx/CVE-2019-1788.json

Adding ClamAV CVE-2019-1788

---

2019/1xxx/CVE-2019-1798.json

Adding ClamAV CVE-2019-1798

---

2018/15xxx/CVE-2018-15631.json
2018/15xxx/CVE-2018-15635.json
2018/15xxx/CVE-2018-15640.json

Hi, here is the first git-based submission from Odoo SA, for our batch of CVE ODOO-SA-2018-11-28, including:
- CVE-2018-15631
- CVE-2018-15635
- CVE-2018-15640
Thanks!

Odoo: ODOO-SA-2018-11-28

---

2018/1xxx/CVE-2018-1903.json
2018/1xxx/CVE-2018-1994.json
2019/4xxx/CVE-2019-4013.json

Added CVE-2018-1903, CVE-2018-1994, and CVE-2019-4013.

Ibm20190410 10810

---

2019/6xxx/CVE-2019-6154.json
2019/6xxx/CVE-2019-6156.json

CVEs for 4/4/19 Lenovo advisories

4-4-19 Lenovo Advisories

---

2019/0xxx/CVE-2019-0008.json
2019/0xxx/CVE-2019-0019.json
2019/0xxx/CVE-2019-0028.json
2019/0xxx/CVE-2019-0031.json
2019/0xxx/CVE-2019-0032.json
2019/0xxx/CVE-2019-0033.json
2019/0xxx/CVE-2019-0034.json
2019/0xxx/CVE-2019-0035.json
2019/0xxx/CVE-2019-0036.json
2019/0xxx/CVE-2019-0037.json
2019/0xxx/CVE-2019-0038.json
2019/0xxx/CVE-2019-0039.json
2019/0xxx/CVE-2019-0040.json
2019/0xxx/CVE-2019-0041.json
2019/0xxx/CVE-2019-0042.json
2019/0xxx/CVE-2019-0043.json
2019/0xxx/CVE-2019-0044.json

CVE IDs assigned in Juniper Security Advisories for April 2019.

CVE IDs assigned in Juniper Security Advisories for April 2019.

---

2018/1xxx/CVE-2018-1925.json
2019/4xxx/CVE-2019-4012.json
2019/4xxx/CVE-2019-4178.json
2019/4xxx/CVE-2019-4202.json
2019/4xxx/CVE-2019-4203.json

Added  CVE-2018-1925, CVE-2019-4012, CVE-2019-4178, CVE-2019-4202, and CVE-2019-4203.

Ibm20190415 104958

---

2019/10xxx/CVE-2019-10300.json
2019/10xxx/CVE-2019-10301.json
2019/10xxx/CVE-2019-10302.json
2019/10xxx/CVE-2019-10303.json
2019/10xxx/CVE-2019-10304.json
2019/10xxx/CVE-2019-10305.json
2019/10xxx/CVE-2019-10306.json

https://jenkins.io/security/advisory/2019-04-17/

Jenkins 2019-04-17 security advisory

---

2019/11xxx/CVE-2019-11035.json

Should be https://bugs.php.net/bug.php?id=77831 as in source.

Fix incorrect bug reference

---

2018/1xxx/CVE-2018-1729.json
2019/4xxx/CVE-2019-4055.json

Added CVE-2018-1729 and CVE-2019-4055.

Ibm20190419 121520

---

2019/6xxx/CVE-2019-6155.json
2019/6xxx/CVE-2019-6157.json

Adding details for advisories posted 4-18-19.

4-18-19 Advisories

---

2011/1xxx/CVE-2011-1830.json
2011/3xxx/CVE-2011-3145.json
2011/3xxx/CVE-2011-3147.json
2011/3xxx/CVE-2011-3151.json
2014/1xxx/CVE-2014-1426.json
2014/1xxx/CVE-2014-1427.json
2014/1xxx/CVE-2014-1428.json
2015/1xxx/CVE-2015-1316.json
2015/1xxx/CVE-2015-1320.json
2015/1xxx/CVE-2015-1326.json
2015/1xxx/CVE-2015-1327.json
2015/1xxx/CVE-2015-1340.json
2015/1xxx/CVE-2015-1341.json
2015/1xxx/CVE-2015-1343.json
2016/1xxx/CVE-2016-1573.json
2016/1xxx/CVE-2016-1579.json
2016/1xxx/CVE-2016-1584.json
2016/1xxx/CVE-2016-1585.json
2016/1xxx/CVE-2016-1586.json
2016/1xxx/CVE-2016-1587.json

Hello, here's a first run through of some of the CVEs that Ubuntu has assigned. Our apologies for letting these become stale.
I believe we still have these CVEs outstanding, they will come in a future pull request:
CVE-2012-0945
CVE-2012-0951
CVE-2012-0952
CVE-2012-0953
CVE-2012-0955
CVE-2013-1053
CVE-2013-1054
CVE-2013-1055
CVE-2014-1420
CVE-2014-1422
CVE-2014-1423
CVE-2015-7946
Thanks

Some historical overlooked Ubuntu-assigned CVEs

---

2019/7xxx/CVE-2019-7303.json
2019/7xxx/CVE-2019-7304.json

snapd seccomp ioctl TIOCSTI issue found by Jann Horn
snapd socket issue found by Chris Moberly

Two snapd issues

---

2018/1xxx/CVE-2018-1961.json
2018/2xxx/CVE-2018-2004.json
2018/2xxx/CVE-2018-2007.json
2019/4xxx/CVE-2019-4047.json

Added CVE-2018-1961, CVE-2018-2004, CVE-2018-2007, and CVE-2019-4047.

Ibm20190429 123247

---

2019/10xxx/CVE-2019-10307.json
2019/10xxx/CVE-2019-10308.json
2019/10xxx/CVE-2019-10309.json
2019/10xxx/CVE-2019-10310.json
2019/10xxx/CVE-2019-10311.json
2019/10xxx/CVE-2019-10312.json
2019/10xxx/CVE-2019-10313.json
2019/10xxx/CVE-2019-10314.json
2019/10xxx/CVE-2019-10315.json
2019/10xxx/CVE-2019-10316.json
2019/10xxx/CVE-2019-10317.json
2019/10xxx/CVE-2019-10318.json

https://jenkins.io/security/advisory/2019-04-30/

Add CVEs for 2019-04-30 Jenkins security advisory

---

2019/4xxx/CVE-2019-4166.json

Ibm20190430 102126

---

2019/2xxx/CVE-2019-2699.json
2019/5xxx/CVE-2019-5624.json

Add CVE-2019-5624

---

2018/1xxx/CVE-2018-1608.json
2018/1xxx/CVE-2018-1933.json
2019/4xxx/CVE-2019-4258.json

Added CVE-2018-1608, CVE-2018-1933, and CVE-2019-4258.

Ibm20190501 1179

---

2018/2xxx/CVE-2018-2015.json

Ibm20190502 115426

---

2018/15xxx/CVE-2018-15388.json

Adding Cisco CVE-2018-15388

---

2018/15xxx/CVE-2018-15462.json

Adding Cisco CVE-2018-15462

---

2019/11xxx/CVE-2019-11036.json
2019/11xxx/CVE-2019-11037.json

Issues for PHP May 2019 release.

Php may2019

---

2018/15xxx/CVE-2018-15631.json

Added disclosure link by CERT-XLM, the original reporter.

Odoo: CVE-2018-15631: update ref urls

---

2019/3xxx/CVE-2019-3552.json
2019/3xxx/CVE-2019-3558.json
2019/3xxx/CVE-2019-3559.json
2019/3xxx/CVE-2019-3564.json
2019/3xxx/CVE-2019-3565.json

Independently fixable, so one per language containing issues / fixes.

Add CVEs for Facebook Thrift iteration issues

---

2018/2xxx/CVE-2018-2001.json
2018/2xxx/CVE-2018-2008.json
2019/4xxx/CVE-2019-4207.json
2019/4xxx/CVE-2019-4208.json

Added CVE-2018-2001, CVE-2018-2008, CVE-2019-4207, and CVE-2019-4208.

Ibm20190507 142822

---

2019/11xxx/CVE-2019-11820.json

Synology-SA-19:21

---

2019/4xxx/CVE-2019-4071.json
2019/4xxx/CVE-2019-4072.json

Added CVE-2019-4071 and CVE-2019-4072.

Ibm20190509 103326

---

2019/1xxx/CVE-2019-1867.json

Adding Cisco CVE-2019-1867

---

2019/4xxx/CVE-2019-4259.json

Ibm20190513 114659

---

2018/16xxx/CVE-2018-16556.json
2018/16xxx/CVE-2018-16557.json
2018/4xxx/CVE-2018-4843.json
2019/10xxx/CVE-2019-10916.json
2019/10xxx/CVE-2019-10917.json
2019/10xxx/CVE-2019-10918.json
2019/10xxx/CVE-2019-10919.json
2019/10xxx/CVE-2019-10920.json
2019/10xxx/CVE-2019-10921.json
2019/10xxx/CVE-2019-10922.json
2019/10xxx/CVE-2019-10924.json
2019/6xxx/CVE-2019-6568.json
2019/6xxx/CVE-2019-6572.json
2019/6xxx/CVE-2019-6574.json
2019/6xxx/CVE-2019-6575.json
2019/6xxx/CVE-2019-6576.json
2019/6xxx/CVE-2019-6577.json
2019/6xxx/CVE-2019-6578.json

Signed-off-by: Siemens ProductCERT <productcert@siemens.com>

CVE updates for Siemens AD-2019-05

---

2018/1xxx/CVE-2018-1975.json

Ibm20190516 104258

---

2019/4xxx/CVE-2019-4119.json
2019/4xxx/CVE-2019-4279.json

Added CVE-2019-4119 and CVE-2019-4279.

Ibm20190517 103930

---

2018/2xxx/CVE-2018-2005.json
2019/4xxx/CVE-2019-4011.json
2019/4xxx/CVE-2019-4058.json
2019/4xxx/CVE-2019-4293.json

Added CVE-2019-4058, CVE-2019-4011, CVE-2018-2005, and CVE-2019-4293.

Ibm20190520 131246

---

2018/1xxx/CVE-2018-1991.json

Ibm20190522 103044

---

2019/4xxx/CVE-2019-4039.json
2019/4xxx/CVE-2019-4078.json

Added CVE-2019-4039 and CVE-2019-4078.

Ibm20190523 9654

---

2019/10xxx/CVE-2019-10321.json
2019/10xxx/CVE-2019-10322.json
2019/10xxx/CVE-2019-10323.json
2019/10xxx/CVE-2019-10324.json
2019/10xxx/CVE-2019-10325.json
2019/10xxx/CVE-2019-10326.json
2019/10xxx/CVE-2019-10327.json
2019/10xxx/CVE-2019-10328.json
2019/10xxx/CVE-2019-10329.json
2019/10xxx/CVE-2019-10330.json

https://jenkins.io/security/advisory/2019-05-31/

CVEs for Jenkins 2019-05-31 security advisory

---

2019/6xxx/CVE-2019-6736.json
2019/6xxx/CVE-2019-6737.json
2019/6xxx/CVE-2019-6738.json

M  2019/6xxx/CVE-2019-6736.json
M  2019/6xxx/CVE-2019-6737.json
M  2019/6xxx/CVE-2019-6738.json

ZDI assigns the following Bitdefender CVEs:

---

2019/6xxx/CVE-2019-6739.json

M  2019/6xxx/CVE-2019-6739.json

ZDI assigns the following Malwarebytes CVE:

---

2019/6xxx/CVE-2019-6746.json
2019/6xxx/CVE-2019-6747.json
2019/6xxx/CVE-2019-6748.json
2019/6xxx/CVE-2019-6749.json
2019/6xxx/CVE-2019-6750.json
2019/6xxx/CVE-2019-6751.json
2019/6xxx/CVE-2019-6752.json
2019/6xxx/CVE-2019-6753.json
2019/6xxx/CVE-2019-6754.json
2019/6xxx/CVE-2019-6755.json
2019/6xxx/CVE-2019-6756.json
2019/6xxx/CVE-2019-6757.json
2019/6xxx/CVE-2019-6758.json
2019/6xxx/CVE-2019-6759.json
2019/6xxx/CVE-2019-6760.json
2019/6xxx/CVE-2019-6761.json
2019/6xxx/CVE-2019-6762.json
2019/6xxx/CVE-2019-6763.json
2019/6xxx/CVE-2019-6764.json
2019/6xxx/CVE-2019-6765.json
2019/6xxx/CVE-2019-6766.json
2019/6xxx/CVE-2019-6767.json
2019/6xxx/CVE-2019-6768.json
2019/6xxx/CVE-2019-6769.json
2019/6xxx/CVE-2019-6770.json
2019/6xxx/CVE-2019-6771.json
2019/6xxx/CVE-2019-6772.json
2019/6xxx/CVE-2019-6773.json

M  2019/6xxx/CVE-2019-6746.json
M  2019/6xxx/CVE-2019-6747.json
M  2019/6xxx/CVE-2019-6748.json
M  2019/6xxx/CVE-2019-6749.json
M  2019/6xxx/CVE-2019-6750.json
M  2019/6xxx/CVE-2019-6751.json
M  2019/6xxx/CVE-2019-6752.json
M  2019/6xxx/CVE-2019-6753.json
M  2019/6xxx/CVE-2019-6754.json
M  2019/6xxx/CVE-2019-6755.json
M  2019/6xxx/CVE-2019-6756.json
M  2019/6xxx/CVE-2019-6757.json
M  2019/6xxx/CVE-2019-6758.json
M  2019/6xxx/CVE-2019-6759.json
M  2019/6xxx/CVE-2019-6760.json
M  2019/6xxx/CVE-2019-6761.json
M  2019/6xxx/CVE-2019-6762.json
M  2019/6xxx/CVE-2019-6763.json
M  2019/6xxx/CVE-2019-6764.json
M  2019/6xxx/CVE-2019-6765.json
M  2019/6xxx/CVE-2019-6766.json
M  2019/6xxx/CVE-2019-6767.json
M  2019/6xxx/CVE-2019-6768.json
M  2019/6xxx/CVE-2019-6769.json
M  2019/6xxx/CVE-2019-6770.json …

ZDI assigns the following Foxit CVEs:

---

2019/6xxx/CVE-2019-6740.json
2019/6xxx/CVE-2019-6741.json
2019/6xxx/CVE-2019-6742.json

M  2019/6xxx/CVE-2019-6740.json
M  2019/6xxx/CVE-2019-6741.json
M  2019/6xxx/CVE-2019-6742.json

ZDI assigns the following Samsung CVEs:

---

2019/6xxx/CVE-2019-6743.json

M  2019/6xxx/CVE-2019-6743.json

ZDI assigns the following Xiaomi CVE:

---

2019/3xxx/CVE-2019-3567.json

Publish CVE-2019-3567

---

2019/1xxx/CVE-2019-1842.json

Adding Cisco CVE-2019-1842

---

2019/10xxx/CVE-2019-10323.json

References:
* https://github.com/jenkinsci/artifactory-plugin/commit/bae102c85558ea7daea32a411700076f1b7f8bb7
* https://www.jfrog.com/jira/browse/HAP-1195

CVE-2019-10323 was only fixed in version 3.2.4

---

2019/4xxx/CVE-2019-4161.json
2019/4xxx/CVE-2019-4162.json
2019/4xxx/CVE-2019-4217.json
2019/4xxx/CVE-2019-4218.json
2019/4xxx/CVE-2019-4219.json
2019/4xxx/CVE-2019-4257.json

Added CVE-2019-4161, CVE-2019-4162, CVE-2019-4217, CVE-2019-4218, CVE-2019-4219, and CVE-2019-4257.

Ibm20190606 155829

---

2019/4xxx/CVE-2019-4066.json
2019/4xxx/CVE-2019-4067.json
2019/4xxx/CVE-2019-4068.json
2019/4xxx/CVE-2019-4069.json
2019/4xxx/CVE-2019-4070.json

Added CVE-2019-4066, CVE-2019-4067,  CVE-2019-4068, CVE-2019-4069, and CVE-2019-4070.

Ibm20190607 102528

---

2019/10xxx/CVE-2019-10160.json

I've edited the affected versions and also added upstream commits to the references

edit versions

---

2019/10xxx/CVE-2019-10331.json
2019/10xxx/CVE-2019-10332.json
2019/10xxx/CVE-2019-10333.json
2019/10xxx/CVE-2019-10334.json
2019/10xxx/CVE-2019-10335.json
2019/10xxx/CVE-2019-10336.json
2019/10xxx/CVE-2019-10337.json
2019/10xxx/CVE-2019-10338.json
2019/10xxx/CVE-2019-10339.json

https://jenkins.io/security/advisory/2019-06-11/

CVEs for 2019-06-11 Jenkins security advisory

---

2017/8xxx/CVE-2017-8252.json
2018/11xxx/CVE-2018-11819.json
2018/11xxx/CVE-2018-11929.json
2018/11xxx/CVE-2018-11934.json
2018/11xxx/CVE-2018-11939.json
2018/11xxx/CVE-2018-11942.json
2018/11xxx/CVE-2018-11947.json
2018/11xxx/CVE-2018-11955.json
2018/13xxx/CVE-2018-13898.json
2018/13xxx/CVE-2018-13901.json
2018/13xxx/CVE-2018-13902.json
2018/13xxx/CVE-2018-13906.json
2018/13xxx/CVE-2018-13907.json
2018/13xxx/CVE-2018-13908.json
2018/13xxx/CVE-2018-13909.json
2018/13xxx/CVE-2018-13910.json
2018/13xxx/CVE-2018-13911.json
2018/13xxx/CVE-2018-13919.json
2018/3xxx/CVE-2018-3583.json
2018/5xxx/CVE-2018-5883.json
2018/5xxx/CVE-2018-5903.json
2018/5xxx/CVE-2018-5911.json
2018/5xxx/CVE-2018-5912.json
2018/5xxx/CVE-2018-5913.json
2019/2xxx/CVE-2019-2255.json
2019/2xxx/CVE-2019-2256.json
2019/2xxx/CVE-2019-2257.json
2019/2xxx/CVE-2019-2259.json

Quacomm_6-14-2019

---

2018/20xxx/CVE-2018-20655.json
2018/6xxx/CVE-2018-6339.json
2018/6xxx/CVE-2018-6349.json
2018/6xxx/CVE-2018-6350.json

These are 2018 CVEs which we allocated for issues fixed then but which were not properly published. Apologies for the delay here!

Add CVEs for WhatsApp mobile apps

---

2018/1xxx/CVE-2018-1845.json
2019/4xxx/CVE-2019-4103.json
2019/4xxx/CVE-2019-4136.json
2019/4xxx/CVE-2019-4173.json
2019/4xxx/CVE-2019-4174.json
2019/4xxx/CVE-2019-4176.json
2019/4xxx/CVE-2019-4177.json

Added CVE-2018-1845, CVE-2019-4103, CVE-2019-4136, CVE-2019-4173, CVE-2019-4174, CVE-2019-4176, and CVE-2019-4177.

Ibm20190617 105141

---

2019/4xxx/CVE-2019-4142.json

Ibm20190618 102746

---

2019/11xxx/CVE-2019-11038.json
2019/11xxx/CVE-2019-11039.json
2019/11xxx/CVE-2019-11040.json

CVE-2019-11038, CVE-2019-11039, CVE-2019-11040

New PHP release vulnerabilities for June

---

2017/1xxx/CVE-2017-1107.json
2019/4xxx/CVE-2019-4303.json
2019/4xxx/CVE-2019-4364.json
2019/4xxx/CVE-2019-4384.json
2019/4xxx/CVE-2019-4385.json

Added CVE-2017-1107, CVE-2019-4303, CVE-2019-4364, CVE-2019-4384, and CVE-2019-4385.

Ibm20190619 91425

---

2018/1xxx/CVE-2018-1858.json
2018/2xxx/CVE-2018-2011.json
2018/2xxx/CVE-2018-2013.json
2019/4xxx/CVE-2019-4135.json
2019/4xxx/CVE-2019-4145.json
2019/4xxx/CVE-2019-4150.json
2019/4xxx/CVE-2019-4151.json
2019/4xxx/CVE-2019-4152.json
2019/4xxx/CVE-2019-4153.json
2019/4xxx/CVE-2019-4156.json
2019/4xxx/CVE-2019-4157.json
2019/4xxx/CVE-2019-4158.json
2019/4xxx/CVE-2019-4377.json
2019/4xxx/CVE-2019-4382.json

Added CVE-2018-1858, CVE-2018-2011, CVE-2018-2013, CVE-2019-4135, CVE-2019-4145, CVE-2019-4150, CVE-2019-4151, CVE-2019-4152, CVE-2019-4153, CVE-2019-4156, CVE-2019-4157, CVE-2019-4158, CVE-2019-4377, and CVE-2019-4382.

Ibm20190625 11215

---

2019/11xxx/CVE-2019-11272.json

Signed-off-by: Ramkumar Vengadakrishnan <rvengadakrishnan@pivotal.io>

Adding Pivotal CVE-2019-11272

---

2019/6xxx/CVE-2019-6163.json
2019/6xxx/CVE-2019-6166.json
2019/6xxx/CVE-2019-6167.json
2019/6xxx/CVE-2019-6168.json
2019/6xxx/CVE-2019-6169.json

Lenovo_Advisories_6-25-19

---

2019/4xxx/CVE-2019-4224.json
2019/4xxx/CVE-2019-4225.json
2019/4xxx/CVE-2019-4234.json
2019/4xxx/CVE-2019-4235.json
2019/4xxx/CVE-2019-4241.json

Added CVE-2019-4224, CVE-2019-4225, CVE-2019-4234, CVE-2019-4235, and CVE-2019-4241.

Ibm20190626 102750

---

2018/1xxx/CVE-2018-1734.json
2018/1xxx/CVE-2018-1758.json
2018/1xxx/CVE-2018-1760.json
2018/1xxx/CVE-2018-1826.json
2018/1xxx/CVE-2018-1827.json
2018/1xxx/CVE-2018-1828.json
2018/1xxx/CVE-2018-1892.json
2018/1xxx/CVE-2018-1893.json
2019/4xxx/CVE-2019-4083.json
2019/4xxx/CVE-2019-4084.json
2019/4xxx/CVE-2019-4249.json
2019/4xxx/CVE-2019-4250.json
2019/4xxx/CVE-2019-4252.json

Added CVE-2018-1734, CVE-2018-1758, CVE-2018-1760, CVE-2018-1826, CVE-2018-1827, CVE-2018-1828, CVE-2018-1892, CVE-2018-1893, CVE-2019-4083, CVE-2019-4084, CVE-2019-4249, CVE-2019-4250, and CVE-2019-4252.

Ibm20190627 9023

---

2019/3xxx/CVE-2019-3628.json

Publish 2019-3628

---

2019/3xxx/CVE-2019-3629.json

Publishing 2019-3629

---

2019/3xxx/CVE-2019-3630.json

Publish 2019-3630

---

2019/3xxx/CVE-2019-3632.json

Publish 2019-3632

---

2019/4xxx/CVE-2019-4269.json
2019/4xxx/CVE-2019-4369.json

Added CVE-2019-4269 and CVE-2019-4369.

Ibm20190628 121211

---

2019/11xxx/CVE-2019-11826.json

Synology-SA-19:05

---

2019/11xxx/CVE-2019-11825.json

Synology-SA-19:04

---

2019/11xxx/CVE-2019-11821.json
2019/11xxx/CVE-2019-11822.json

Added CVE-2019-11821 and CVE-2019-11822.

Synology-SA-19:01

---

2019/11xxx/CVE-2019-11829.json

Synology-SA-19:12

---

2019/11xxx/CVE-2019-11828.json

Synology-SA-19:11

---

2019/11xxx/CVE-2019-11827.json

Synology-SA-19:08

---

2019/4xxx/CVE-2019-4057.json
2019/4xxx/CVE-2019-4101.json
2019/4xxx/CVE-2019-4102.json
2019/4xxx/CVE-2019-4154.json
2019/4xxx/CVE-2019-4237.json
2019/4xxx/CVE-2019-4295.json
2019/4xxx/CVE-2019-4296.json
2019/4xxx/CVE-2019-4297.json
2019/4xxx/CVE-2019-4298.json
2019/4xxx/CVE-2019-4299.json
2019/4xxx/CVE-2019-4322.json
2019/4xxx/CVE-2019-4336.json
2019/4xxx/CVE-2019-4337.json
2019/4xxx/CVE-2019-4357.json
2019/4xxx/CVE-2019-4383.json
2019/4xxx/CVE-2019-4386.json
2019/4xxx/CVE-2019-4410.json

Added CVE-2019-4057, CVE-2019-4101, CVE-2019-4102, CVE-2019-4154, CVE-2019-4237, CVE-2019-4295, CVE-2019-4296, CVE-2019-4297, CVE-2019-4298, CVE-2019-4299, CVE-2019-4322, CVE-2019-4336, CVE-2019-4337, CVE-2019-4357, CVE-2019-4383, CVE-2019-4386, and CVE-2019-4410.

Ibm20190701 11220

---

2019/4xxx/CVE-2019-4087.json
2019/4xxx/CVE-2019-4088.json
2019/4xxx/CVE-2019-4129.json
2019/4xxx/CVE-2019-4134.json
2019/4xxx/CVE-2019-4140.json
2019/4xxx/CVE-2019-4260.json
2019/4xxx/CVE-2019-4292.json

Added CVE-2019-4087, CVE-2019-4088, CVE-2019-4129, CVE-2019-4134, CVE-2019-4140, CVE-2019-4260, and CVE-2019-4292.

Ibm20190702 10596

---

2019/3xxx/CVE-2019-3619.json

Publish 2019-3619

---

2019/5xxx/CVE-2019-5960.json
2019/5xxx/CVE-2019-5961.json
2019/5xxx/CVE-2019-5962.json
2019/5xxx/CVE-2019-5963.json
2019/5xxx/CVE-2019-5964.json
2019/5xxx/CVE-2019-5965.json
2019/5xxx/CVE-2019-5966.json
2019/5xxx/CVE-2019-5967.json
2019/5xxx/CVE-2019-5968.json
2019/5xxx/CVE-2019-5969.json
2019/5xxx/CVE-2019-5970.json
2019/5xxx/CVE-2019-5971.json
2019/5xxx/CVE-2019-5972.json
2019/5xxx/CVE-2019-5973.json
2019/5xxx/CVE-2019-5974.json
2019/5xxx/CVE-2019-5979.json
2019/5xxx/CVE-2019-5980.json
2019/5xxx/CVE-2019-5981.json
2019/5xxx/CVE-2019-5982.json
2019/5xxx/CVE-2019-5983.json
2019/5xxx/CVE-2019-5984.json

CVE-2019-5960,CVE-2019-5961,CVE-2019-5962,CVE-2019-5963,CVE-2019-5964,CVE-2019-5965,CVE-2019-5966,CVE-2019-5967,CVE-2019-5968,CVE-2019-5969,
CVE-2019-5970,CVE-2019-5971,CVE-2019-5972,CVE-2019-5973,CVE-2019-5974,CVE-2019-5979,
CVE-2019-5980,CVE-2019-5981,CVE-2019-5982,CVE-2019-5983,CVE-2019-5984

jpcert20190704 batch.

---

2019/10xxx/CVE-2019-10340.json
2019/10xxx/CVE-2019-10341.json
2019/10xxx/CVE-2019-10342.json
2019/10xxx/CVE-2019-10346.json
2019/10xxx/CVE-2019-10347.json
2019/10xxx/CVE-2019-10348.json
2019/10xxx/CVE-2019-10349.json
2019/10xxx/CVE-2019-10350.json
2019/10xxx/CVE-2019-10351.json

https://jenkins.io/security/advisory/2019-07-11/

Add CVEs for Jenkins 2019-07-11 security advisory

---

2019/11xxx/CVE-2019-11268.json

Signed-off-by: William Brandon <wbrandon@pivotal.io>

add CVE-2019-11268

---

2019/5xxx/CVE-2019-5629.json

Ready for review!
https://help.rapid7.com/insightagent/release-notes/archive/2019/05/#20190529
https://bogner.sh/2019/06/local-privilege-escalation-in-rapid7s-windows-insight-idr-agent/

CVE-2019-5629 content

---

2019/10xxx/CVE-2019-10352.json
2019/10xxx/CVE-2019-10353.json
2019/10xxx/CVE-2019-10354.json

https://jenkins.io/security/advisory/2019-07-17/

CVEs for 2019-07-17 Jenkins security advisory

---

2019/3xxx/CVE-2019-3592.json

Publish 2019 - 3592

---

2018/2xxx/CVE-2018-2024.json
2019/4xxx/CVE-2019-4236.json
2019/4xxx/CVE-2019-4267.json

Added CVE-2018-2024, CVE-2019-4236, and CVE-2019-4267.

Ibm20190722 9297

---

2019/3xxx/CVE-2019-3595.json

Publish 2019-3595

---

2019/3xxx/CVE-2019-3591.json

Publish 2019-3591

---

2019/6xxx/CVE-2019-6002.json

JPCERT/CC 2019-07-26

---

2019/4xxx/CVE-2019-4062.json
2019/4xxx/CVE-2019-4285.json
2019/4xxx/CVE-2019-4456.json

Added CVE-2019-4062, CVE-2019-4285, and CVE-2019-4456.

Ibm20190730 9233

---

2019/10xxx/CVE-2019-10343.json
2019/10xxx/CVE-2019-10344.json
2019/10xxx/CVE-2019-10345.json
2019/10xxx/CVE-2019-10355.json
2019/10xxx/CVE-2019-10356.json
2019/10xxx/CVE-2019-10357.json
2019/10xxx/CVE-2019-10358.json
2019/10xxx/CVE-2019-10359.json
2019/10xxx/CVE-2019-10360.json
2019/10xxx/CVE-2019-10361.json
2019/10xxx/CVE-2019-10362.json
2019/10xxx/CVE-2019-10363.json
2019/10xxx/CVE-2019-10364.json
2019/10xxx/CVE-2019-10365.json
2019/10xxx/CVE-2019-10366.json

https://jenkins.io/security/advisory/2019-07-31/

Add 2019-07-31 Jenkins security advisory

---

2019/4xxx/CVE-2019-4163.json
2019/4xxx/CVE-2019-4165.json

Added CVE-2019-4163 and CVE-2019-4165.

Ibm20190731 121914

---

2018/1xxx/CVE-2018-1987.json
2019/4xxx/CVE-2019-4275.json

Added CVE-2018-1987 and CVE-2019-4275.

Ibm20190802 10710

---

2019/4xxx/CVE-2019-4261.json
2019/4xxx/CVE-2019-4284.json
2019/4xxx/CVE-2019-4473.json

Added CVE-2019-4261, CVE-2019-4284, and CVE-2019-4473.

Ibm20190805 93830

---

2019/5xxx/CVE-2019-5994.json
2019/5xxx/CVE-2019-5995.json
2019/5xxx/CVE-2019-5998.json
2019/5xxx/CVE-2019-5999.json
2019/6xxx/CVE-2019-6000.json
2019/6xxx/CVE-2019-6001.json

- CVE-2019-5994
- CVE-2019-5995
- CVE-2019-5998
- CVE-2019-5999
- CVE-2019-6000
- CVE-2019-6001

JPCERT/CC 2019-08-06

---

2019/10xxx/CVE-2019-10367.json
2019/10xxx/CVE-2019-10368.json
2019/10xxx/CVE-2019-10369.json
2019/10xxx/CVE-2019-10370.json
2019/10xxx/CVE-2019-10371.json
2019/10xxx/CVE-2019-10372.json
2019/10xxx/CVE-2019-10373.json
2019/10xxx/CVE-2019-10374.json
2019/10xxx/CVE-2019-10375.json
2019/10xxx/CVE-2019-10376.json
2019/10xxx/CVE-2019-10377.json
2019/10xxx/CVE-2019-10378.json
2019/10xxx/CVE-2019-10379.json
2019/10xxx/CVE-2019-10380.json
2019/10xxx/CVE-2019-10381.json
2019/10xxx/CVE-2019-10382.json
2019/10xxx/CVE-2019-10385.json
2019/10xxx/CVE-2019-10386.json
2019/10xxx/CVE-2019-10387.json
2019/10xxx/CVE-2019-10388.json
2019/10xxx/CVE-2019-10389.json

https://jenkins.io/security/advisory/2019-08-07/

Jenkins 2019-08-07 security advisory

---

2019/11xxx/CVE-2019-11207.json

Publish JSON data for TIBCO LogLogic LMI vulnerabilities.

---

2019/3xxx/CVE-2019-3635.json

Publish CVE-2019-3635

---

2019/3xxx/CVE-2019-3639.json

Publish CVE-2019-3639

---

2019/3xxx/CVE-2019-3637.json

Publish 2019-3637

---

2019/6xxx/CVE-2019-6159.json
2019/6xxx/CVE-2019-6165.json
2019/6xxx/CVE-2019-6171.json

Lenovo_8-8-19_CVEs

---

2019/14xxx/CVE-2019-14684.json
2019/14xxx/CVE-2019-14687.json

CVE-2019-14684 and 14687 from Trend Micro on 08192019

CVE-2019-14684 and 14687 from Trend Micro

---

2018/1xxx/CVE-2018-1630.json
2018/1xxx/CVE-2018-1631.json
2018/1xxx/CVE-2018-1632.json
2018/1xxx/CVE-2018-1633.json
2018/1xxx/CVE-2018-1634.json
2018/1xxx/CVE-2018-1635.json
2018/1xxx/CVE-2018-1636.json
2018/1xxx/CVE-2018-1796.json
2019/4xxx/CVE-2019-4253.json

Added CVE-2018-1630, CVE-2018-1631, CVE-2018-1632, CVE-2018-1633, CVE-2018-1634, CVE-2018-1635, CVE-2018-1636, CVE-2018-1796, and CVE-2019-4253.

Ibm20190820 144438

---

2019/4xxx/CVE-2019-4120.json
2019/4xxx/CVE-2019-4167.json
2019/4xxx/CVE-2019-4338.json
2019/4xxx/CVE-2019-4340.json
2019/4xxx/CVE-2019-4424.json
2019/4xxx/CVE-2019-4437.json
2019/4xxx/CVE-2019-4482.json

Added CVE-2019-4120, CVE-2019-4167, CVE-2019-4338, CVE-2019-4340, CVE-2019-4424, CVE-2019-4437, and CVE-2019-4482.

Ibm20190820 152425

---

2019/3xxx/CVE-2019-3633.json

Publish CVE-2019-3633

---

2019/3xxx/CVE-2019-3634.json

Publish CVE-2019-3634

---

2019/14xxx/CVE-2019-14685.json
2019/14xxx/CVE-2019-14686.json

CVE-2019-14685 and CVE-2019-14686 on 08212019 from Trend Micro

CVE-2019-14685 and CVE-2019-14686

---

2019/4xxx/CVE-2019-4132.json
2019/4xxx/CVE-2019-4133.json
2019/4xxx/CVE-2019-4536.json

Added CVE-2019-4132, CVE-2019-4133, and CVE-2019-4536.

Ibm20190829 105534

---

2019/6xxx/CVE-2019-6179.json
2019/6xxx/CVE-2019-6180.json
2019/6xxx/CVE-2019-6181.json
2019/6xxx/CVE-2019-6182.json

populating CVE data for LEN-27805

CVE submission for LEN-27805

---

2019/11xxx/CVE-2019-11061.json
2019/11xxx/CVE-2019-11063.json

Add CVSS 3.0 score and vector to CVE-2019-11061 and CVE-2019-11063.

Update CVE-2019-11061 11063

---

2019/4xxx/CVE-2019-4149.json
2019/4xxx/CVE-2019-4186.json
2019/4xxx/CVE-2019-4321.json

Added Added CVE-2019-4186, CVE-2019-4149, and CVE-2019-4321.

Ibm20190905 104720

---

2019/1xxx/CVE-2019-1547.json
2019/1xxx/CVE-2019-1549.json
2019/1xxx/CVE-2019-1563.json

CVE-2019-1547 ECDSA remote timing attack
CVE-2019-1549 Fork Protection
CVE-2019-1563 Padding Oracle in PKCS7_dataDecode and CMS_decrypt_set1_pkey

Add OpenSSL CVEs

---

2019/6xxx/CVE-2019-6745.json

ZDI rejects CVE-2019-6745

---

2019/9xxx/CVE-2019-9488.json

CVE-2019-9488 Publish from Trend Micro

Publish CVE-2019-9488 from Trend Micro

---

2019/4xxx/CVE-2019-4086.json
2019/4xxx/CVE-2019-4171.json
2019/4xxx/CVE-2019-4175.json
2019/4xxx/CVE-2019-4183.json
2019/4xxx/CVE-2019-4268.json
2019/4xxx/CVE-2019-4270.json
2019/4xxx/CVE-2019-4271.json
2019/4xxx/CVE-2019-4342.json
2019/4xxx/CVE-2019-4442.json
2019/4xxx/CVE-2019-4477.json

Added CVE-2019-4086, CVE-2019-4171, CVE-2019-4175, CVE-2019-4183, CVE-2019-4268, CVE-2019-4270, CVE-2019-4271, CVE-2019-4342, CVE-2019-4442, and CVE-2019-4477.

Ibm20190917 15237

---

2018/1xxx/CVE-2018-1847.json

Ibm20190918 11541

---

2019/6xxx/CVE-2019-6010.json

JPCERT/CC 2019-09-19

---

2019/4xxx/CVE-2019-4505.json
2019/4xxx/CVE-2019-4565.json

Added CVE-2019-4505 and CVE-2019-4565.

Ibm20190920 114618

---

2019/4xxx/CVE-2019-4515.json
2019/4xxx/CVE-2019-4566.json

Added CVE-2019-4515 and CVE-2019-4566.

Ibm20190924 9461

---

2019/10xxx/CVE-2019-10401.json
2019/10xxx/CVE-2019-10402.json
2019/10xxx/CVE-2019-10403.json
2019/10xxx/CVE-2019-10404.json
2019/10xxx/CVE-2019-10405.json
2019/10xxx/CVE-2019-10406.json
2019/10xxx/CVE-2019-10407.json
2019/10xxx/CVE-2019-10408.json
2019/10xxx/CVE-2019-10409.json
2019/10xxx/CVE-2019-10410.json
2019/10xxx/CVE-2019-10411.json
2019/10xxx/CVE-2019-10412.json
2019/10xxx/CVE-2019-10413.json
2019/10xxx/CVE-2019-10414.json
2019/10xxx/CVE-2019-10415.json
2019/10xxx/CVE-2019-10416.json
2019/10xxx/CVE-2019-10417.json
2019/10xxx/CVE-2019-10418.json
2019/10xxx/CVE-2019-10419.json
2019/10xxx/CVE-2019-10420.json
2019/10xxx/CVE-2019-10421.json
2019/10xxx/CVE-2019-10422.json
2019/10xxx/CVE-2019-10423.json
2019/10xxx/CVE-2019-10424.json
2019/10xxx/CVE-2019-10425.json
2019/10xxx/CVE-2019-10426.json
2019/10xxx/CVE-2019-10427.json
2019/10xxx/CVE-2019-10428.json
2019/10xxx/CVE-2019-10429.json
2019/10xxx/CVE-2019-10430.json

https://jenkins.io/security/advisory/2019-09-25/

Add CVEs for 2019-09-25 Jenkins security advisory

---

2019/4xxx/CVE-2019-4571.json

Ibm20190925 155937

---

2019/4xxx/CVE-2019-4262.json
2019/4xxx/CVE-2019-4378.json

Added CVE-2019-4378 and CVE-2019-4262.

Ibm20190926 104317

---

2019/4xxx/CVE-2019-4141.json

Ibm20190927 95731

---

2019/4xxx/CVE-2019-4106.json
2019/4xxx/CVE-2019-4109.json
2019/4xxx/CVE-2019-4112.json
2019/4xxx/CVE-2019-4115.json
2019/4xxx/CVE-2019-4280.json
2019/4xxx/CVE-2019-4304.json
2019/4xxx/CVE-2019-4305.json
2019/4xxx/CVE-2019-4423.json

Added CVE-2019-4106, CVE-2019-4109, CVE-2019-4112, CVE-2019-4115, CVE-2019-4280, CVE-2019-4304, CVE-2019-4305, and CVE-2019-4423.

Ibm20190930 111444

---

2019/10xxx/CVE-2019-10489.json
2019/10xxx/CVE-2019-10492.json
2019/10xxx/CVE-2019-10497.json
2019/10xxx/CVE-2019-10498.json
2019/10xxx/CVE-2019-10499.json
2019/10xxx/CVE-2019-10501.json
2019/10xxx/CVE-2019-10506.json
2019/10xxx/CVE-2019-10507.json
2019/10xxx/CVE-2019-10508.json
2019/10xxx/CVE-2019-10509.json
2019/10xxx/CVE-2019-10510.json
2019/10xxx/CVE-2019-10538.json
2019/10xxx/CVE-2019-10539.json
2019/10xxx/CVE-2019-10540.json
2019/2xxx/CVE-2019-2252.json
2019/2xxx/CVE-2019-2284.json
2019/2xxx/CVE-2019-2294.json
2019/2xxx/CVE-2019-2333.json
2019/2xxx/CVE-2019-2341.json

Qualcomm-9-30-2019-CVE-Publish

Qualcomm-9-30-2019

---

2019/4xxx/CVE-2019-4246.json
2019/4xxx/CVE-2019-4494.json
2019/4xxx/CVE-2019-4495.json
2019/4xxx/CVE-2019-4497.json

Added CVE-2019-4246, CVE-2019-4494, CVE-2019-4495, and CVE-2019-4497.

Ibm20191001 102611

---

2019/7xxx/CVE-2019-7618.json

Elastic 2019-10-01 security advisory

Elastic 2019-10-01 security advisory

---

2019/4xxx/CVE-2019-4520.json
2019/4xxx/CVE-2019-4538.json
2019/4xxx/CVE-2019-4539.json
2019/4xxx/CVE-2019-4542.json
2019/4xxx/CVE-2019-4549.json

Added CVE-2019-4520, CVE-2019-4538, CVE-2019-4539, CVE-2019-4542, and CVE-2019-4549.

Ibm20191002 104125

---

2019/4xxx/CVE-2019-4422.json
2019/4xxx/CVE-2019-4441.json

Added CVE-2019-4441, and CVE-2019-4422.

Ibm20191003 10045

---

2019/4xxx/CVE-2019-4227.json
2019/4xxx/CVE-2019-4514.json
2019/4xxx/CVE-2019-4564.json

Added CVE-2019-4514, CVE-2019-4227, and CVE-2019-4564.

Ibm20191004 10315

---

2019/3xxx/CVE-2019-3652.json

Publish CVE-2019-3652

---

2019/4xxx/CVE-2019-4512.json
2019/4xxx/CVE-2019-4558.json

Added CVE-2019-4512 and CVE-2019-4558.

Ibm20191009 105523

---

2019/0xxx/CVE-2019-0047.json
2019/0xxx/CVE-2019-0050.json
2019/0xxx/CVE-2019-0051.json
2019/0xxx/CVE-2019-0054.json
2019/0xxx/CVE-2019-0055.json
2019/0xxx/CVE-2019-0056.json
2019/0xxx/CVE-2019-0057.json
2019/0xxx/CVE-2019-0058.json
2019/0xxx/CVE-2019-0059.json
2019/0xxx/CVE-2019-0060.json
2019/0xxx/CVE-2019-0061.json
2019/0xxx/CVE-2019-0062.json
2019/0xxx/CVE-2019-0063.json
2019/0xxx/CVE-2019-0064.json
2019/0xxx/CVE-2019-0065.json
2019/0xxx/CVE-2019-0066.json
2019/0xxx/CVE-2019-0067.json
2019/0xxx/CVE-2019-0068.json
2019/0xxx/CVE-2019-0069.json
2019/0xxx/CVE-2019-0070.json
2019/0xxx/CVE-2019-0071.json
2019/0xxx/CVE-2019-0072.json
2019/0xxx/CVE-2019-0073.json
2019/0xxx/CVE-2019-0074.json
2019/0xxx/CVE-2019-0075.json

for more information see https://advisory.juniper.net

juniper-2019-10-09 CVE publications

---

2019/10xxx/CVE-2019-10436.json
2019/10xxx/CVE-2019-10437.json
2019/10xxx/CVE-2019-10438.json
2019/10xxx/CVE-2019-10439.json
2019/10xxx/CVE-2019-10440.json
2019/10xxx/CVE-2019-10441.json
2019/10xxx/CVE-2019-10442.json
2019/10xxx/CVE-2019-10443.json
2019/10xxx/CVE-2019-10444.json
2019/10xxx/CVE-2019-10445.json
2019/10xxx/CVE-2019-10446.json
2019/10xxx/CVE-2019-10447.json
2019/10xxx/CVE-2019-10448.json
2019/10xxx/CVE-2019-10449.json
2019/10xxx/CVE-2019-10450.json
2019/10xxx/CVE-2019-10451.json
2019/10xxx/CVE-2019-10452.json
2019/10xxx/CVE-2019-10453.json
2019/10xxx/CVE-2019-10454.json
2019/10xxx/CVE-2019-10455.json
2019/10xxx/CVE-2019-10456.json
2019/10xxx/CVE-2019-10457.json
2019/10xxx/CVE-2019-10458.json

https://jenkins.io/security/advisory/2019-10-16/

Add CVEs for Jenkins 2019-10-16 security advisory

---

2019/6xxx/CVE-2019-6472.json
2019/6xxx/CVE-2019-6473.json
2019/6xxx/CVE-2019-6474.json

This will clear out half of our remaining backlog.

[ISC] Update information for 3 Kea CVEs from August 2019

---

2019/11xxx/CVE-2019-11253.json

Kubernetes updates

---

2019/15xxx/CVE-2019-15626.json
2019/15xxx/CVE-2019-15627.json

Trend Micro CVE-2019-15626 and CVE-2019-15627 submission

Trend Micro CVE-2019-15626 and CVE-2019-15627 submission

---

2019/6xxx/CVE-2019-6475.json
2019/6xxx/CVE-2019-6476.json

[ISC] 2 BIND9 Vulns made public

---

2019/10xxx/CVE-2019-10215.json

Reverts CVEProject/cvelist#2667

Revert "CVE-2019-10215 init"

---

2019/9xxx/CVE-2019-9491.json

Trend Micro publish CVE-2019-9491

Trend Micro publish CVE-2019-9491

---

2019/10xxx/CVE-2019-10459.json
2019/10xxx/CVE-2019-10460.json
2019/10xxx/CVE-2019-10461.json
2019/10xxx/CVE-2019-10462.json
2019/10xxx/CVE-2019-10463.json
2019/10xxx/CVE-2019-10464.json
2019/10xxx/CVE-2019-10465.json
2019/10xxx/CVE-2019-10466.json
2019/10xxx/CVE-2019-10467.json
2019/10xxx/CVE-2019-10468.json
2019/10xxx/CVE-2019-10469.json
2019/10xxx/CVE-2019-10470.json
2019/10xxx/CVE-2019-10471.json
2019/10xxx/CVE-2019-10472.json
2019/10xxx/CVE-2019-10473.json
2019/10xxx/CVE-2019-10474.json
2019/10xxx/CVE-2019-10475.json
2019/10xxx/CVE-2019-10476.json

https://jenkins.io/security/advisory/2019-10-23/

Add CVEs for 2019-10-23 Jenkins security advisory

---

2019/4xxx/CVE-2019-4397.json
2019/4xxx/CVE-2019-4398.json
2019/4xxx/CVE-2019-4459.json
2019/4xxx/CVE-2019-4486.json

Added Added CVE-2019-4459, CVE-2019-4397, CVE-2019-4398, and CVE-2019-4486.

Ibm20191024 75625

---

2019/4xxx/CVE-2019-4036.json
2019/4xxx/CVE-2019-4394.json
2019/4xxx/CVE-2019-4395.json
2019/4xxx/CVE-2019-4396.json
2019/4xxx/CVE-2019-4399.json
2019/4xxx/CVE-2019-4400.json
2019/4xxx/CVE-2019-4461.json

Added  CVE-2019-4400, CVE-2019-4394, CVE-2019-4399, CVE-2019-4461, CVE-2019-4036, CVE-2019-4396, and CVE-2019-4395.

Ibm20191025 122815

---

2019/17xxx/CVE-2019-17138.json
2019/17xxx/CVE-2019-17139.json
2019/17xxx/CVE-2019-17140.json
2019/17xxx/CVE-2019-17141.json
2019/17xxx/CVE-2019-17142.json
2019/17xxx/CVE-2019-17143.json
2019/17xxx/CVE-2019-17144.json
2019/17xxx/CVE-2019-17145.json

A  2019/17xxx/CVE-2019-17138.json
A  2019/17xxx/CVE-2019-17139.json
A  2019/17xxx/CVE-2019-17140.json
A  2019/17xxx/CVE-2019-17141.json
A  2019/17xxx/CVE-2019-17142.json
A  2019/17xxx/CVE-2019-17143.json
A  2019/17xxx/CVE-2019-17144.json
A  2019/17xxx/CVE-2019-17145.json

ZDI assigns the following Foxit CVEs

---

2019/18xxx/CVE-2019-18187.json
2019/18xxx/CVE-2019-18188.json
2019/18xxx/CVE-2019-18189.json

Trend Micro CVE-2019-18187, 18188, 18189 submissions

Trend Micro CVE-2019-18187, 18188, 18189 submissions

---

2019/4xxx/CVE-2019-4306.json
2019/4xxx/CVE-2019-4307.json
2019/4xxx/CVE-2019-4309.json
2019/4xxx/CVE-2019-4311.json
2019/4xxx/CVE-2019-4314.json
2019/4xxx/CVE-2019-4329.json
2019/4xxx/CVE-2019-4330.json
2019/4xxx/CVE-2019-4339.json
2019/4xxx/CVE-2019-4546.json
2019/4xxx/CVE-2019-4600.json

Added CVE-2019-4309, CVE-2019-4330, CVE-2019-4339, CVE-2019-4600, CVE-2019-4311, CVE-2019-4546, CVE-2019-4306, CVE-2019-4314, CVE-2019-4307,  and CVE-2019-4329.

Ibm20191028 193230

---

2019/18xxx/CVE-2019-18189.json

Fixing windows-1252 encoded quote character

Fixing windows-1252 encoded quote character

---

2019/6xxx/CVE-2019-6470.json

This is the last of our PBR entries.

[ISC] Update information for CVE-2019-6470

---

2018/0xxx/CVE-2018-0178.json

Withdraw Cisco CVE-2018-0178

---

2019/12xxx/CVE-2019-12625.json

Adding ClamAV CVE-2019-12625

---

2019/14xxx/CVE-2019-14847.json

Hello Leonardo,
Thank you for the suggestion, I have changed the version and description accordingly. Also +1 for the wait period on MR, it's easier that way for contributors as well.

CVE-2019-14847 version adjustment

---

2019/4xxx/CVE-2019-4652.json

Ibm20191112 101445

---

2019/6xxx/CVE-2019-6170.json
2019/6xxx/CVE-2019-6172.json
2019/6xxx/CVE-2019-6188.json

nov 12 publications

---

2019/3xxx/CVE-2019-3648.json

Publish 2019-3648

---

2019/3xxx/CVE-2019-3641.json

Updated CVE-2019-3641

---

2019/16xxx/CVE-2019-16761.json

Adding this advisory: https://github.com/simpleledger/slp-validate/security/advisories/GHSA-wmx6-vxcf-c3gr
This has been assigned CVE-2019-16761 by the GitHub CNA

add CVE-2019-16761

---

2019/16xxx/CVE-2019-16762.json

Adding this advisory: GHSA-425c-ccf3-3jrr
This has been assigned CVE-2019-16762 by the GitHub CNA

add CVE-2019-16762

---

2019/16xxx/CVE-2019-16538.json
2019/16xxx/CVE-2019-16539.json
2019/16xxx/CVE-2019-16540.json
2019/16xxx/CVE-2019-16541.json
2019/16xxx/CVE-2019-16542.json
2019/16xxx/CVE-2019-16543.json
2019/16xxx/CVE-2019-16544.json
2019/16xxx/CVE-2019-16545.json
2019/16xxx/CVE-2019-16546.json
2019/16xxx/CVE-2019-16547.json
2019/16xxx/CVE-2019-16548.json

https://jenkins.io/security/advisory/2019-11-21/

Add CVEs for 2019-11-21 Jenkins security advisory

---

2019/4xxx/CVE-2019-4214.json
2019/4xxx/CVE-2019-4215.json
2019/4xxx/CVE-2019-4216.json
2019/4xxx/CVE-2019-4243.json
2019/4xxx/CVE-2019-4569.json
2019/4xxx/CVE-2019-4570.json

Added CVE-2019-4214, CVE-2019-4215, CVE-2019-4216, CVE-2019-4243, CVE-2019-4569, and CVE-2019-4570.

Ibm20191122 101457

---

2019/16xxx/CVE-2019-16764.json

add CVE-2019-16764 for https://github.com/pow-auth/pow_assent/security/advisories/GHSA-368c-xvrv-x986

add CVE-2019-16764.json

---

2019/16xxx/CVE-2019-16765.json

add CVE-2019-16765 for https://github.com/github/vscode-codeql/security/advisories/GHSA-wf4x-8mpj-r42q

add CVE-2019-16765

---

2019/15xxx/CVE-2019-15629.json

Trend Micro CVE-2019-15629

---

2019/17xxx/CVE-2019-17632.json

CVE-2019-17632

---

2019/4xxx/CVE-2019-4387.json

Ibm20191126 104437

---

2019/16xxx/CVE-2019-16767.json

add CVE-2019-16767 for https://github.com/Inist-CNRS/ezmaster/security/advisories/GHSA-g654-5qjf-g6cx

add CVE-2019-16767

---

2019/15xxx/CVE-2019-15628.json

Trend Micro CVE-2019-15628

---

2019/3xxx/CVE-2019-3666.json

CVE-2019-3666

---

2019/3xxx/CVE-2019-3665.json

CVE-2019-3665

---

2019/11xxx/CVE-2019-11923.json
2019/11xxx/CVE-2019-11937.json

Publishing two CVEs for Mcrouter (https://github.com/facebook/mcrouter/)

CVEs for Mcrouter

---

2019/11xxx/CVE-2019-11930.json
2019/11xxx/CVE-2019-11934.json
2019/11xxx/CVE-2019-11935.json
2019/11xxx/CVE-2019-11936.json

Publishing CVEs relevant to HHVM's latest release.

HHVM CVEs for latest release

---

2019/11xxx/CVE-2019-11940.json

Documenting a CVE for a previously addressed issue in Proxygen.

New CVE for Proxygen

---

2019/17xxx/CVE-2019-17437.json
2019/1xxx/CVE-2019-1581.json

A new advisory published with a CVE assignment, and updating text of an existing advisory to match the description on our advisory.

PANW updates on 2019-12-04

---

2018/1002xxx/CVE-2018-1002102.json
2019/11xxx/CVE-2019-11255.json

* CVE-2018-1002102
* CVE-2019-11255

Sync Kubernetes branch for 12/2019

---

2019/16xxx/CVE-2019-16769.json

add CVE-2019-16769 for https://github.com/advisories/GHSA-h9rv-jmmf-4pgx

add CVE-2019-16769 for GHSA-h9rv-jmmf-4pgx

---

2019/16xxx/CVE-2019-16770.json

add CVE-2019-16770 for GHSA-7xx3-m584-x994

add CVE-2019-16770 for GHSA-7xx3-m584-x994

---

2019/16xxx/CVE-2019-16768.json

add CVE-2019-16768 for GHSA-3r8j-pmch-5j2h

add CVE-2019-16768 for GHSA-3r8j-pmch-5j2h

---

2019/16xxx/CVE-2019-16769.json

Updating the description on the CVE so it specifies the package name for the CVE (we are still refining our process and tools for getting this data populated 😁 )

update CVE-2019-16769 with description that specifies package name

---

2019/16xxx/CVE-2019-16768.json

update CVE-2019-16768 with description that specifies package name

update CVE-2019-16768 with description that specifies package name

---

2019/16xxx/CVE-2019-16770.json

update CVE-2019-16770 with improved description that specifies the fixed version.

update CVE-2019-16770 with improved description

---

2019/1xxx/CVE-2019-1551.json

rsaz_512_sqr overflow bug on x86_64

OpenSSL CVE-2019-1551

---

2019/16xxx/CVE-2019-16771.json

add CVE-2019-16771 for GHSA-35fr-h7jr-hh86

add CVE-2019-16771 for GHSA-35fr-h7jr-hh86

---

2019/16xxx/CVE-2019-16772.json

add CVE-2019-16772 for GHSA-3fjq-93xj-3f3f

add CVE-2019-16772 for GHSA-3fjq-93xj-3f3f

---

2019/18xxx/CVE-2019-18190.json

Trend Micro CVE-2019-18190

---

2019/4xxx/CVE-2019-4095.json
2019/4xxx/CVE-2019-4244.json
2019/4xxx/CVE-2019-4521.json
2019/4xxx/CVE-2019-4663.json

Added CVE-2019-4095, CVE-2019-4244, CVE-2019-4521, and CVE-2019-4663.

Ibm20191210 11419

---

2019/3xxx/CVE-2019-3667.json

CVE-2019-3667

---

2019/10xxx/CVE-2019-10484.json

Updated CVE-2019-10484 description

Qualcomm_12-12-2019_2

---

2019/4xxx/CVE-2019-4606.json

Ibm20191212 11296

---

2019/16xxx/CVE-2019-16774.json

add add CVE-2019-16774 for GHSA-484f-743f-6jx2

add CVE-2019-16774 for GHSA-484f-743f-6jx2

---

2019/16xxx/CVE-2019-16775.json
2019/16xxx/CVE-2019-16776.json

Add CVE-2019-16776 for GHSA-x8qc-rrcw-4r46

Add CVE-2019-16776 for GHSA-x8qc-rrcw-4r46

---

2019/16xxx/CVE-2019-16775.json

Add CVE-2019-16775 for GHSA-m6cx-g6qm-p2cx

Add CVE-2019-16775 for GHSA-m6cx-g6qm-p2cx

---

2019/16xxx/CVE-2019-16777.json

Add CVE-2019-16777 for GHSA-4328-8hgf-7wjr

Add CVE-2019-16777 for GHSA-4328-8hgf-7wjr

---

2019/4xxx/CVE-2019-4444.json
2019/4xxx/CVE-2019-4560.json

Added CVE-2019-4560 and CVE-2019-4444.

Ibm20191216 104021

---

2019/16xxx/CVE-2019-16779.json

add CVE-2019-16779 for GHSA-q58g-455p-8vw9

add CVE-2019-16779 for GHSA-q58g-455p-8vw9

---

2019/16xxx/CVE-2019-16778.json

add CVE-2019-16778 for GHSA-844w-j86r-4x2j

add CVE-2019-16778 for GHSA-844w-j86r-4x2j

---

2019/18xxx/CVE-2019-18191.json

CVE-2019-18191 Trend Micro

---

2019/16xxx/CVE-2019-16549.json
2019/16xxx/CVE-2019-16550.json
2019/16xxx/CVE-2019-16551.json
2019/16xxx/CVE-2019-16552.json
2019/16xxx/CVE-2019-16553.json
2019/16xxx/CVE-2019-16554.json
2019/16xxx/CVE-2019-16555.json
2019/16xxx/CVE-2019-16556.json
2019/16xxx/CVE-2019-16557.json
2019/16xxx/CVE-2019-16558.json
2019/16xxx/CVE-2019-16559.json
2019/16xxx/CVE-2019-16560.json
2019/16xxx/CVE-2019-16561.json
2019/16xxx/CVE-2019-16562.json
2019/16xxx/CVE-2019-16563.json
2019/16xxx/CVE-2019-16564.json
2019/16xxx/CVE-2019-16565.json
2019/16xxx/CVE-2019-16566.json
2019/16xxx/CVE-2019-16567.json
2019/16xxx/CVE-2019-16568.json
2019/16xxx/CVE-2019-16569.json
2019/16xxx/CVE-2019-16570.json
2019/16xxx/CVE-2019-16571.json
2019/16xxx/CVE-2019-16572.json
2019/16xxx/CVE-2019-16573.json
2019/16xxx/CVE-2019-16574.json
2019/16xxx/CVE-2019-16575.json
2019/16xxx/CVE-2019-16576.json

https://jenkins.io/security/advisory/2019-12-17/

Add 2019-12-17 Jenkins security advisory

---

2019/16xxx/CVE-2019-16782.json

add CVE-2019-16782 for GHSA-hrqr-hxpp-chr3

add CVE-2019-16782 for GHSA-hrqr-hxpp-chr3

---

2019/7xxx/CVE-2019-7482.json
2019/7xxx/CVE-2019-7483.json
2019/7xxx/CVE-2019-7484.json
2019/7xxx/CVE-2019-7485.json
2019/7xxx/CVE-2019-7486.json
2019/7xxx/CVE-2019-7487.json

SonicWall Multiple Vulnerabilities in SMA100 and SonicOS.

SonicWall Multiple Vulns in SMA100 & SonicOS

---

2019/11xxx/CVE-2019-11780.json

Hi, here is a git-based submission from Odoo SA, for our security advisory ODOO-SA-2019-10-25, including:
- CVE-2019-11780
Thanks!

Odoo: ODOO-SA-2019-10-25

---

2019/17xxx/CVE-2019-17633.json

CVE-2019-17633

---

2019/16xxx/CVE-2019-16787.json

add CVE-2019-16787 for GHSA-3cm7-rgh5-9pq5

add CVE-2019-16787 for GHSA-3cm7-rgh5-9pq5

---

2019/16xxx/CVE-2019-16785.json

add CVE-2019-16785 for GHSA-pg36-wpm5-g57p

add CVE-2019-16785 for GHSA-pg36-wpm5-g57p

---

2019/7xxx/CVE-2019-7488.json
2019/7xxx/CVE-2019-7489.json

SonicWall Email Security Vulnerability for authetication and RCE

SonicWall ES Vuln

---

2019/6xxx/CVE-2019-6008.json
2019/6xxx/CVE-2019-6011.json
2019/6xxx/CVE-2019-6012.json
2019/6xxx/CVE-2019-6013.json
2019/6xxx/CVE-2019-6014.json
2019/6xxx/CVE-2019-6015.json
2019/6xxx/CVE-2019-6016.json
2019/6xxx/CVE-2019-6017.json
2019/6xxx/CVE-2019-6018.json
2019/6xxx/CVE-2019-6019.json
2019/6xxx/CVE-2019-6020.json
2019/6xxx/CVE-2019-6021.json
2019/6xxx/CVE-2019-6022.json
2019/6xxx/CVE-2019-6023.json
2019/6xxx/CVE-2019-6024.json
2019/6xxx/CVE-2019-6025.json
2019/6xxx/CVE-2019-6026.json
2019/6xxx/CVE-2019-6027.json
2019/6xxx/CVE-2019-6029.json
2019/6xxx/CVE-2019-6030.json
2019/6xxx/CVE-2019-6031.json
2019/6xxx/CVE-2019-6032.json
2019/6xxx/CVE-2019-6033.json
2019/6xxx/CVE-2019-6034.json
2019/6xxx/CVE-2019-6035.json

- CVE-2019-6008
- CVE-2019-6011
- CVE-2019-6012
- CVE-2019-6013
- CVE-2019-6014
- CVE-2019-6015
- CVE-2019-6016
- CVE-2019-6017
- CVE-2019-6018
- CVE-2019-6019
- CVE-2019-6020
- CVE-2019-6021
- CVE-2019-6022
- CVE-2019-6023
- CVE-2019-6024
- CVE-2019-6025
- CVE-2019-6026
- CVE-2019-6027
- CVE-2019-6029
- CVE-2019-6030
- CVE-2019-6031
- CVE-2019-6032
- CVE-2019-6033
- CVE-2019-6034
- CVE-2019-6035

JPCERT/CC 2019-12-26 batch

---

2019/16xxx/CVE-2019-16789.json

add CVE-2019-16789 for GHSA-m5ff-3wj3-8ph4

add CVE-2019-16789 for GHSA-m5ff-3wj3-8ph4

---

2019/16xxx/CVE-2019-16780.json

add CVE-2019-16780 for GHSA-x3wp-h3qx-9w94

add CVE-2019-16780 for GHSA-x3wp-h3qx-9w94

---

2019/16xxx/CVE-2019-16781.json

Add CVE-2019-16781 for GHSA-pg4x-64rh-3c9v

Add CVE-2019-16781 for GHSA-pg4x-64rh-3c9v

---

2019/16xxx/CVE-2019-16790.json

add CVE-2019-16790 for GHSA-w72h-v37j-rrwr

add CVE-2019-16790 for GHSA-w72h-v37j-rrwr

---

2019/7xxx/CVE-2019-7479.json

Vulnerability in read-only admin SonicWall SonicOS and SonicOSV.

SonicWall SonicOS & SonicOSv read-only admin vuln

---

2019/17xxx/CVE-2019-17151.json

updates description, CWE, and CVSS

ZDI updates CVE-2019-17151 for accuracy

---

2019/16xxx/CVE-2019-16773.json

add CVE-2019-16773 for GHSA-xvg2-m2f4-83m7

add CVE-2019-16773 for GHSA-xvg2-m2f4-83m7

---

2020/5xxx/CVE-2020-5205.json

add CVE-2020-5205 for GHSA-v2wf-c3j6-wpvw

add CVE-2020-5205 for GHSA-v2wf-c3j6-wpvw

---

2019/16xxx/CVE-2019-16788.json

add CVE-2019-16788 for GHSA-g7rg-hchx-c2gw

add CVE-2019-16788 for GHSA-g7rg-hchx-c2gw

---

2019/4xxx/CVE-2019-4508.json
2019/4xxx/CVE-2019-4559.json

Added CVE-2019-4508 and CVE-2019-4559.

Ibm20200110 103312

---

2019/16xxx/CVE-2019-16784.json

add CVE-2019-16784 for GHSA-7fcj-pq9j-wh2r

add CVE-2019-16784 for GHSA-7fcj-pq9j-wh2r

---

2019/17xxx/CVE-2019-17149.json
2019/17xxx/CVE-2019-17150.json

A  2019/17xxx/CVE-2019-17149.json
A  2019/17xxx/CVE-2019-17150.json
accidental usage

ZDI rejects the following CVEs:

---

2020/2xxx/CVE-2020-2090.json
2020/2xxx/CVE-2020-2091.json
2020/2xxx/CVE-2020-2092.json
2020/2xxx/CVE-2020-2093.json
2020/2xxx/CVE-2020-2094.json
2020/2xxx/CVE-2020-2095.json
2020/2xxx/CVE-2020-2096.json
2020/2xxx/CVE-2020-2097.json
2020/2xxx/CVE-2020-2098.json

https://jenkins.io/security/advisory/2020-01-15/

Add Jenkins 2020-01-15 CVEs

---

2018/0xxx/CVE-2018-0719.json
2018/0xxx/CVE-2018-0721.json

as title
add cvss score information

modify security advisory of NAS-201809-20

---

2019/17xxx/CVE-2019-17634.json
2019/17xxx/CVE-2019-17635.json

Two vulnerability reports for Eclipse Memory Analyzer

---

2019/16xxx/CVE-2019-16791.json

add CVE-2019-16791 for GHSA-h92m-42h4-82f6

add CVE-2019-16791 for GHSA-h92m-42h4-82f6

---

2019/16xxx/CVE-2019-16792.json

add CVE-2019-16792 for GHSA-4ppp-gpcr-7qf6

add CVE-2019-16792 for GHSA-4ppp-gpcr-7qf6

---

2020/5xxx/CVE-2020-5221.json

add CVE-2020-5221 for GHSA-wmx8-v7mx-6x9h

add CVE-2020-5221 for GHSA-wmx8-v7mx-6x9h

---

2020/5xxx/CVE-2020-5223.json

add CVE-2020-5223 for GHSA-8j72-p2wm-6738

add CVE-2020-5223 for GHSA-8j72-p2wm-6738

---

2020/5xxx/CVE-2020-5217.json

add CVE-2020-5217 for GHSA-xq52-rv6w-397c

add CVE-2020-5217 for GHSA-xq52-rv6w-397c

---

2020/5xxx/CVE-2020-5216.json

add CVE-2020-5216 for GHSA-w978-rmpf-qmwg

add CVE-2020-5216 for GHSA-w978-rmpf-qmwg

---

2020/5xxx/CVE-2020-5219.json

add CVE-2020-5219 for GHSA-hxhm-96pp-2m43

add CVE-2020-5219 for GHSA-hxhm-96pp-2m43

---

2020/5xxx/CVE-2020-5224.json

add CVE-2020-5224 for GHSA-5fq8-3q2f-4m5g

add CVE-2020-5224 for GHSA-5fq8-3q2f-4m5g

---

2018/8xxx/CVE-2018-8654.json
2019/1xxx/CVE-2019-1349.json
2019/1xxx/CVE-2019-1350.json
2019/1xxx/CVE-2019-1351.json
2019/1xxx/CVE-2019-1352.json
2019/1xxx/CVE-2019-1354.json
2019/1xxx/CVE-2019-1414.json
2019/1xxx/CVE-2019-1454.json
2019/1xxx/CVE-2019-1460.json

Updates to previous CVE's

---

2020/5xxx/CVE-2020-5225.json

add CVE-2020-5225 for GHSA-6gc6-m364-85ww

add CVE-2020-5225 for GHSA-6gc6-m364-85ww

---

2020/5xxx/CVE-2020-5226.json

add CVE-2020-5226 for GHSA-mj9p-v2r8-wf8w

add CVE-2020-5226 for GHSA-mj9p-v2r8-wf8w

---

2020/5xxx/CVE-2020-5220.json

add CVE-2020-5220 for GHSA-8vp7-j5cj-vvm2

add CVE-2020-5220 for GHSA-8vp7-j5cj-vvm2

---

2020/5xxx/CVE-2020-5218.json

add CVE-2020-5218 for GHSA-prg5-hg25-8grq

add CVE-2020-5218 for GHSA-prg5-hg25-8grq

---

2020/5xxx/CVE-2020-5210.json

add CVE-2020-5210 for GHSA-v5pg-hpjg-9rpp

add CVE-2020-5210 for GHSA-v5pg-hpjg-9rpp

---

2020/5xxx/CVE-2020-5209.json

add CVE-2020-5209 for GHSA-fw72-r8xm-45p8

add CVE-2020-5209 for GHSA-fw72-r8xm-45p8

---

2020/5xxx/CVE-2020-5214.json

add CVE-2020-5214 for GHSA-p8fw-rq89-xqx6

add CVE-2020-5214 for GHSA-p8fw-rq89-xqx6

---

2020/5xxx/CVE-2020-5213.json

add CVE-2020-5213 for GHSA-rr25-4v34-pr7v

add CVE-2020-5213 for GHSA-rr25-4v34-pr7v

---

2020/5xxx/CVE-2020-5212.json

add CVE-2020-5212 for GHSA-g89f-m829-4m56

add CVE-2020-5212 for GHSA-g89f-m829-4m56

---

2020/5xxx/CVE-2020-5211.json

add CVE-2020-5211 for GHSA-r788-4jf4-r9f7

add CVE-2020-5211 for GHSA-r788-4jf4-r9f7

---

2020/5xxx/CVE-2020-5215.json

add CVE-2020-5215 for GHSA-977j-xj7q-2jr9

add CVE-2020-5215 for GHSA-977j-xj7q-2jr9

---

2020/5xxx/CVE-2020-5227.json

add CVE-2020-5227 for GHSA-g8q7-xv52-hf9f

add CVE-2020-5227 for GHSA-g8q7-xv52-hf9f

---

2020/2xxx/CVE-2020-2099.json
2020/2xxx/CVE-2020-2100.json
2020/2xxx/CVE-2020-2101.json
2020/2xxx/CVE-2020-2102.json
2020/2xxx/CVE-2020-2103.json
2020/2xxx/CVE-2020-2104.json
2020/2xxx/CVE-2020-2105.json
2020/2xxx/CVE-2020-2106.json
2020/2xxx/CVE-2020-2107.json
2020/2xxx/CVE-2020-2108.json

https://jenkins.io/security/advisory/2020-01-29/

Add Jenkins 2019-01-29 CVEs

---

2020/5xxx/CVE-2020-5233.json

add CVE-2020-5233 for GHSA-qqxw-m5fj-f7gv

add CVE-2020-5233 for GHSA-qqxw-m5fj-f7gv

---

2020/5xxx/CVE-2020-5228.json

add CVE-2020-5228 for GHSA-6f54-3qr9-pjgj

add CVE-2020-5228 for GHSA-6f54-3qr9-pjgj

---

2020/5xxx/CVE-2020-5229.json

add CVE-2020-5229 for GHSA-h362-m8f2-5x7c

add CVE-2020-5229 for GHSA-h362-m8f2-5x7c

---

2020/5xxx/CVE-2020-5222.json

add CVE-2020-5222 for GHSA-mh8g-hprg-8363

add CVE-2020-5222 for GHSA-mh8g-hprg-8363

---

2020/5xxx/CVE-2020-5230.json

add CVE-2020-5230 for GHSA-w29m-fjp4-qhmq

add CVE-2020-5230 for GHSA-w29m-fjp4-qhmq

---

2019/20xxx/CVE-2019-20358.json

CVE-2019-20358 Trend Micro

---

2020/5xxx/CVE-2020-5231.json

add CVE-2020-5231 for GHSA-94qw-r73x-j7hg

add CVE-2020-5231 for GHSA-94qw-r73x-j7hg

---

2020/5xxx/CVE-2020-5206.json

add CVE-2020-5206 for GHSA-vmm6-w4cf-7f3x

add CVE-2020-5206 for GHSA-vmm6-w4cf-7f3x

---

2020/5xxx/CVE-2020-5232.json

add CVE-2020-5232 for GHSA-8f9f-pc5v-9r5h

add CVE-2020-5232 for GHSA-8f9f-pc5v-9r5h
