- 2017/5xxx/CVE-2017-5254.json
- 2017/5xxx/CVE-2017-5255.json
- 2017/5xxx/CVE-2017-5256.json
- 2017/5xxx/CVE-2017-5257.json
- 2017/5xxx/CVE-2017-5258.json
- 2017/5xxx/CVE-2017-5259.json
- 2017/5xxx/CVE-2017-5260.json
- 2017/5xxx/CVE-2017-5261.json
- 2017/5xxx/CVE-2017-5262.json
- 2017/5xxx/CVE-2017-5263.json
Update for 10 CVEs assigned to the most recent set of vulnerabilities on Cambium Networks, disclosed by Rapid7, discovered by @juushya.
> Set of Cambium Networks vulns from Rapid7

- 2017/16xxx/CVE-2017-16590.json
- 2017/16xxx/CVE-2017-16591.json
- 2017/16xxx/CVE-2017-16592.json
- 2017/16xxx/CVE-2017-16593.json
- 2017/16xxx/CVE-2017-16594.json
- 2017/16xxx/CVE-2017-16595.json
- 2017/16xxx/CVE-2017-16596.json
- 2017/16xxx/CVE-2017-16597.json
- 2017/16xxx/CVE-2017-16598.json
- 2017/16xxx/CVE-2017-16599.json
- 2017/16xxx/CVE-2017-16600.json
- 2017/16xxx/CVE-2017-16601.json
- 2017/16xxx/CVE-2017-16602.json
- 2017/16xxx/CVE-2017-16603.json
- 2017/16xxx/CVE-2017-16604.json
- 2017/16xxx/CVE-2017-16605.json
- 2017/16xxx/CVE-2017-16606.json
- 2017/16xxx/CVE-2017-16607.json
- 2017/16xxx/CVE-2017-16608.json
- 2017/16xxx/CVE-2017-16609.json
- 2017/16xxx/CVE-2017-16610.json
- 2017/17xxx/CVE-2017-17406.json
- 2017/17xxx/CVE-2017-17407.json
M  2017/16xxx/CVE-2017-16590.json
M  2017/16xxx/CVE-2017-16591.json
M  2017/16xxx/CVE-2017-16592.json
M  2017/16xxx/CVE-2017-16593.json
M  2017/16xxx/CVE-2017-16594.json
M  2017/16xxx/CVE-2017-16595.json
M  2017/16xxx/CVE-2017-16596.json
M  2017/16xxx/CVE-2017-16597.json
M  2017/16xxx/CVE-2017-16598.json
M  2017/16xxx/CVE-2017-16599.json
M  2017/16xxx/CVE-2017-16600.json
M  2017/16xxx/CVE-2017-16601.json
M  2017/16xxx/CVE-2017-16602.json
M  2017/16xxx/CVE-2017-16603.json
M  2017/16xxx/CVE-2017-16604.json
M  2017/16xxx/CVE-2017-16605.json
M  2017/16xxx/CVE-2017-16606.json
M  2017/16xxx/CVE-2017-16607.json
M  2017/16xxx/CVE-2017-16608.json
M  2017/16xxx/CVE-2017-16609.json
M  2017/16xxx/CVE-2017-16610.json
M  2017/17xxx/CVE-2017-17406.json
M  2017/17xxx/CVE-2017-17407.json
> supersedes #137: ZDI assigns the following CVEs:

- 2017/3xxx/CVE-2017-3737.json
First test of using github cvelist, make a small update to CVE-2017-3737 with a link to the official commit that fixed this issue.
> Add github link to patch for CVE-2017-3737

- 2017/14xxx/CVE-2017-14177.json
- 2017/14xxx/CVE-2017-14178.json
- 2017/14xxx/CVE-2017-14179.json
- 2017/14xxx/CVE-2017-14180.json
These are the remaining CVE assignments, made by Canonical, from 2017.
> Canonical CVE assignments from 2017

- 2017/3xxx/CVE-2017-3730.json
- 2017/3xxx/CVE-2017-3731.json
- 2017/3xxx/CVE-2017-3732.json
- 2017/3xxx/CVE-2017-3733.json
- 2017/3xxx/CVE-2017-3735.json
- 2017/3xxx/CVE-2017-3736.json
- 2017/3xxx/CVE-2017-3738.json
(This is a good excuse to make sure signing commits and doing it not via an organisational fork works)
> Add github references for patches for 2017 OpenSSL vulnerabilities

- 2018/0xxx/CVE-2018-0015.json
- 2018/0xxx/CVE-2018-0016.json
- 2018/0xxx/CVE-2018-0017.json
- 2018/0xxx/CVE-2018-0018.json
- 2018/0xxx/CVE-2018-0019.json
- 2018/0xxx/CVE-2018-0020.json
- 2018/0xxx/CVE-2018-0021.json
- 2018/0xxx/CVE-2018-0022.json
- 2018/0xxx/CVE-2018-0023.json
CVEs assigned in Juniper Security Advisories for April (CVE-2018-0016 to CVE-2018-0023) plus update CVE-2018-0015.
> Juniper Security Advisories for April plus updates

- 2016/9xxx/CVE-2016-9646.json
- 2017/0xxx/CVE-2017-0356.json
- 2017/0xxx/CVE-2017-0357.json
- 2017/0xxx/CVE-2017-0358.json
Add some update from the MITRE ping from 20180326 regarding public bust still reserved CVEs.
> Add CVE updates from Debian for 20180326 ping

- 2018/0xxx/CVE-2018-0737.json
OpenSSL: Cache timing vulnerability in RSA Key Generation
> Add CVE details for CVE-2018-0737

- 2018/6xxx/CVE-2018-6552.json
CVE-2018-6552 from the range allocated to Canonical was assigned to apport and made public today.
> New CVE assignment for CVE-2018-6552 from Canonical

- 2017/7xxx/CVE-2017-7654.json
A Memory Leak vulnerability was found within the Mosquitto Broker.
Unauthenticated clients can send crafted CONNECT packets which could
cause a denial of service in the Mosquitto Broker.
> CVE-2017-7654

- 2017/7xxx/CVE-2017-7653.json
The Mosquitto broker up to version 1.4.15 does not reject strings that
are not valid UTF-8. A malicious client could cause other clients that
do reject invalid UTF-8 strings to disconnect themselves from the broker
by sending a topic string which is not valid UTF-8, and so cause a
denial of service for the clients.
> CVE-2017-7653

- 2018/6xxx/CVE-2018-6552.json
Update the CVE to show that Ubuntu 14.04 was also affected. The matching USN was already added.
> Updates to CVE to show that Ubuntu 14.04 was also affected

- CONTRIBUTING.md
It's not clear whether the restrictions in https://github.com/CVEProject/cvelist/blob/master/CONTRIBUTING.md#how-to-contribute apply to minor contributions to the few non-CVE parts of this repo, but I figured it's easy enough to close and reject a PR if you don't want this.
If it matters, I've previously accepted the CVE ToS as CVE requester for the Jenkins project.
> Fix formatting

- 2017/7xxx/CVE-2017-7656.json
The version range is a little complicated on this one. I reviewed the documentation, and scanned a bunch of existing records to come to what I have here. I think that it makes sense.
> CVE-2017-7656

- 2018/5xxx/CVE-2018-5435.json
- 2018/5xxx/CVE-2018-5437.json
Listed one product too many in our original announcement.
> Corrected errors in the initial Spotfire release.

- 2017/15xxx/CVE-2017-15097.json
I have intentionally not put a version to the description, as this was present in all postgresql init scripts in Red Hat postgresql, and we don't bump the version numbers for patching.
> CVE-2017-15097.json

- 2018/9xxx/CVE-2018-9866.json
CVE-2018-9866 is in regarding to SonicWall Global Management System (GMS) 8.1 (and earlier releases) XML-RPC vulnerability which allowed user to execute arbitrary code.
> CVE-2018-9866

- 2018/1xxx/CVE-2018-1258.json
The affected version is only 5.0.5, not all versions prior to 5.0.6.
> Correction on version affected for CVE-2018-1258

- 2016/4xxx/CVE-2016-4975.json
Note this was originally a Red Hat CNA CVE that was given to Apache before Apache was a CNA.  (This is actually the last remaining Red Hat CVE with this status).  I represent both the Red Hat CNA and Apache in this request (as I gave the name to myself at Apache in 2016)
> Add CVE-2016-4975

- 2018/6xxx/CVE-2018-6554.json
- 2018/6xxx/CVE-2018-6555.json
CVEs assigned by Canonical for issues in the IRDA subsystem of the Linux kernel.
> CVE-2018-6554 and CVE-2018-6555

- 2018/14xxx/CVE-2018-14624.json
Upstream has not been patched yet, 1.4.0.16 is the latest version.
> CVE-2018-14624

- 2018/0xxx/CVE-2018-0503.json
- 2018/0xxx/CVE-2018-0504.json
- 2018/0xxx/CVE-2018-0505.json
- 2018/13xxx/CVE-2018-13258.json
This pull request adds the CVE information for the recent mediawiki CVEs (assigned from the Debian pool) and which are CVE-2018-13258, CVE-2018-0505, CVE-2018-0504 and CVE-2018-0503.
https://www.debian.org/security/2018/dsa-4301
> Add mediawiki assignments from Debian

- 2018/0xxx/CVE-2018-0405.json
Adding Cisco CVE-2018-0405 for Cisco RV180W Wireless-N Multifunction VPN Router Directory Path Traversal Vulnerability and correcting validation error.
> Adding Cisco CVE-2018-0405

- 2018/12xxx/CVE-2018-12541.json
- 2018/12xxx/CVE-2018-12542.json
- 2018/12xxx/CVE-2018-12544.json
2018/12xxx/CVE-2018-12541.json
2018/12xxx/CVE-2018-12542.json
2018/12xxx/CVE-2018-12544.json
> Three CVEs related to Eclipse Vert.x

- 2018/15xxx/CVE-2018-15435.json
Adding Cisco CVE-2018-15435 : A vulnerability in the web-based management interface of Cisco SocialMiner could allow an unauthenticated, remote attacker to conduct a stored cross-site scripting (XSS) attack against a user of the web-based management interface. The vulnerability is due to insufficient validation of user-supplied input by the web-based management interface of an affected device. An attacker could exploit this vulnerability by persuading a user of the interface to click a crafted link. A successful exploit could allow the attacker to execute arbitrary script code in the context of the interface or allow the attacker to access sensitive browser-based information.
> Adding Cisco CVE-2018-15435

- 2018/15xxx/CVE-2018-15438.json
Adding Cisco CVE-2018-15438 : A vulnerability in the web-based management interface of Cisco Prime Collaboration Assurance could allow an unauthenticated, remote attacker to conduct a cross-site request forgery (CSRF) attack and perform arbitrary actions on an affected system. The vulnerability is due to insufficient CSRF protections for the web-based management interface of the affected software. An attacker could exploit this vulnerability by persuading a user of the interface to follow a malicious link. A successful exploit could allow the attacker to use a web browser to perform arbitrary actions with the privileges of the user on an affected system.
> Adding Cisco CVE-2018-15438

- 2018/15xxx/CVE-2018-15686.json
- 2018/15xxx/CVE-2018-15687.json
- 2018/15xxx/CVE-2018-15688.json
Hello, Ubuntu has assigned three CVEs to systemd issues that were discovered by Jann Horn and Felix Wilhelm.
This is my first time using the merge/pull mechanism, feedback gratefully accepted. (I checked with jsonschema -- excellent suggestion there, some spurious clicks on vulnogram caused some invalid json output.)
Thanks
> systemd issues reported by Jann Horn and Felix Wilhelm

- 2018/0xxx/CVE-2018-0735.json
OpenSSL - Timing attack against ECDSA signature generation
> Add CVE-2018-0735

- 2018/0xxx/CVE-2018-0734.json
Note that the security advisory name has been incorrectly spelt on the OpenSSL website. See:
https://github.com/openssl/web/pull/91
The advisory URL as it stands in this PR is the correct one and the OpenSSL website will be shortly updated to match.
> Add OpenSSL CVE-2018-0734

- 2018/15xxx/CVE-2018-15454.json
Adding Cisco CVE-2018-15454 - A vulnerability in the Session Initiation Protocol (SIP) inspection engine of Cisco Adaptive Security Appliance (ASA) Software and Cisco Firepower Threat Defense (FTD) Software could allow an unauthenticated, remote attacker to cause an affected device to reload or trigger high CPU, resulting in a denial of service (DoS) condition.  The vulnerability is due to improper handling of SIP traffic. An attacker could exploit this vulnerability by sending SIP requests designed to specifically trigger this issue at a high rate across an affected device. Software updates that address this vulnerability are not yet available.
> Adding Cisco CVE-2018-15454

- 2018/6xxx/CVE-2018-6346.json
- 2018/6xxx/CVE-2018-6347.json
Cut a release today which included fixes for these two CVEs.
> CVEs from Facebook CNA: Proxygen v2018.12.31.00

- 2018/6xxx/CVE-2018-6345.json
- 2018/6xxx/CVE-2018-6346.json
- 2019/3xxx/CVE-2019-3554.json
- 2019/3xxx/CVE-2019-3557.json
- Two CVEs from an HHVM release yesterday: https://hhvm.com/blog/2019/01/14/hhvm-3.30.2.html
- One CVE from Wangle's release yesterday.
- One typo corrected in CVE-2018-6346 (the affected versions had overlapping ranges)
> Latest updates from Facebook CNA

- 2018/12xxx/CVE-2018-12547.json
- 2018/12xxx/CVE-2018-12549.json
For the Eclipse OpenJ9 Project.
> CVE-2018-12547 and CVE-2018-12549.

- 2014/3xxx/CVE-2014-3004.json
Added additional information to the product data (since it had no information). Added information about the impact of this open source vulnerability in Cisco product via CSCvm56811.
> Editing CVE-2014-3004

- 2018/18xxx/CVE-2018-18895.json
We (Cisco PSIRT) noticed the assignment of [CVE-2018-18895](https://github.com/CVEProject/cvelist/blob/d07fae782693caaecf0d08142d5e6a014e06b27a/2018/18xxx/CVE-2018-18895.json).
The vulnerability described in that CVE is the same as CVE-2014-3004 and it was properly documented as such in Cisco Bug ID CSSvm56811.
Cisco did not assign CVE-2018-18895 and request it be marked as invalid or somehow corrected to point to CVE-2014-3004.
I edited the CVE entry to include related information and also pointed to the older CVE. 
This is also documented in the following Issue: https://github.com/CVEProject/cvelist/issues/1570
Alternatively, this CVE should be invalidated. 
Thanks in advance! 
Omar
> Editing CVE-2018-18895

- 2019/5xxx/CVE-2019-5736.json
Updated CVE-2019-5736 which addresses a vulnerability in runc. Updated the product name, version values, as well as entered a reference to a security advisory addressing Cisco products affected by such vulnerabilities.
> Updating runc CVE-2019-5736

- 2018/9xxx/CVE-2018-9867.json
SonicOS administrators without full permissions can download imported certificates.
> CVE-2018-9867

- 2019/3xxx/CVE-2019-3582.json
Initial publication - the SB went live 1/2 hour ago.
> Publishing CVE-2019-3582

- 2018/9xxx/CVE-2018-9867.json
- 2019/7xxx/CVE-2019-7474.json
- 2019/7xxx/CVE-2019-7475.json
- 2019/7xxx/CVE-2019-7477.json
Updating CVE-2018-9867 by adding additional affected products. Adding CVE-2019-7474, 5 and 6 related to SonicWall SonicOS and SonicOSv vulnerabilities.
> CVE-2018-9867 update and CVE-2019-7474, 5 and 6 related to SonicWall SonicOS

- 2019/3xxx/CVE-2019-3566.json
This should have been noted in the original CVE but was incorrectly omitted.
> Update CVE-2019-3566 to reflect WhatsApp Business for Android affected versions

- 2019/1003xxx/CVE-2019-1003000.json
See https://jenkins.io/security/advisory/2019-01-08/#affected-versions
This resolves service request 660041 at Mitre, which I apparently am unable to respond to via email.
> Fix typo in CVE-2019-1003000

- 2019/11xxx/CVE-2019-11477.json
- 2019/11xxx/CVE-2019-11478.json
- 2019/11xxx/CVE-2019-11479.json
Hello, here's three CVE numbers that Ubuntu assigned for the Linux portions of Jonathan Looney's recent selective ack discoveries.
Thanks
> SACK Panic issues in Linux kernel

- 2019/3xxx/CVE-2019-3631.json
SB live
The description matches 3630 - they are distinct issues, any more details in the CVE description would allow an attacker to target the issue before our Customers will have updated.
> Publish 2019-3631

- 2019/10xxx/CVE-2019-10137.json
Sorry it took whole day, but can we please merge this update as the version 2.8 implying version 2.9 is safe is misleading users.
Thank you.
Marian
> Upstream did not merge fix in 2.9 so it is still affected

- 2019/10xxx/CVE-2019-10136.json
Sorry it took whole day, but can we please merge this update as the version 2.8 implying version 2.9 is safe is misleading users.
Thank you.
Marian
> Upstream did not merge fix in 2.9 so it is stil laffected.

- 2011/5xxx/CVE-2011-5057.json
- 2013/1xxx/CVE-2013-1965.json
- 2013/1xxx/CVE-2013-1966.json
- 2014/0xxx/CVE-2014-0094.json
- 2014/0xxx/CVE-2014-0112.json
- 2014/0xxx/CVE-2014-0113.json
- 2014/0xxx/CVE-2014-0116.json
- 2016/3xxx/CVE-2016-3081.json
- 2016/3xxx/CVE-2016-3087.json
- 2016/4xxx/CVE-2016-4438.json
- 2016/6xxx/CVE-2016-6795.json
- 2017/12xxx/CVE-2017-12611.json
- 2017/9xxx/CVE-2017-9791.json
- 2017/9xxx/CVE-2017-9793.json
- 2017/9xxx/CVE-2017-9805.json
A researcher reported a number of cases where Struts affected versions didn't match their research.  These have been updated in the various Struts advisories already.
This patch fixes the CVE entries to match the research and struts updated. advisories.
> Struts version number changes

- 2019/5xxx/CVE-2019-5632.json
- 2019/5xxx/CVE-2019-5633.json
- 2019/5xxx/CVE-2019-5634.json
- 2019/5xxx/CVE-2019-5635.json
A few notes to avoid confusion :-)
- The vendor did NOT confirm this issue, thus there's no CONFIRM link (may fail validation?). 
- Both Rapid7 and CERT/CC tried to get Hickory/Belwith to respond, but did not hear back. 
- We don’t have firmware version info for the ethernet bridge (CVE-2019-5635), only the model number, so used that. As noted in the description for that CVE, we didn't find any evidence of versioning in the firmware.
- Product links go to Hickory Hardware, but Belwith Products, LLC is listed as the vendor as they are the parent company for Hickory.
> JSON content for CVE-2019-5632, -5633, -5634, -5635

- 2019/11xxx/CVE-2019-11476.json
- 2019/7xxx/CVE-2019-7307.json
Hello, here's the two publicly used but not yet pushed CVEs that were flagged when requesting new CVE numbers for the Ubuntu CNA:
CVE Request 748394 for CNA Block Request
Thanks
> Add Ubuntu apport issues discovered by Kevin Backhouse

- 2019/10xxx/CVE-2019-10392.json
* 3.0.0-rc was accidentally published for a week in February, was installed by 10k users, and is also affected
* CWE-78, not -79
> Corrections for CVE-2019-10392

- 2019/16xxx/CVE-2019-16760.json
This is the first published CVE from GitHub CNA.
We are prototyping our submission flow currently, so this PR is a temporary process while we are still getting setup.
Please respond to this PR, or reach to `security-advisories@github.com` with any questions.
> Add CVE-2019015760

- 2019/10xxx/CVE-2019-10431.json
- 2019/10xxx/CVE-2019-10432.json
- 2019/10xxx/CVE-2019-10433.json
- 2019/10xxx/CVE-2019-10434.json
- 2019/10xxx/CVE-2019-10435.json
https://jenkins.io/security/advisory/2019-10-01/
**Note**: One of the plugins' names is *Jenkins Dingding[钉钉]* Plugin and it looks like the following in JSON:
Jenkins Dingding[\u9489\u9489] Plugin
I haven't found whether this is a problem for you, but if it is, we can remove it.
> Add CVEs for 2019-10-01 security advisory

- 2019/16xxx/CVE-2019-16760.json
This is an update for CVE-2019-16760
- It removes two irrelevant references
- Updates the description for accuracy and to be a bit more minimal.
This is the first GitHub submitted CVE to be updated, we are continuing are evaluation so please advise us at security-advisories@github.com if anything we can do to streamline the process.
> update references and description for CVE-2019-16760

- 2018/5xxx/CVE-2018-5732.json
- 2018/5xxx/CVE-2018-5743.json
- 2018/5xxx/CVE-2018-5744.json
- 2018/5xxx/CVE-2018-5745.json
- 2019/6xxx/CVE-2019-6465.json
- 2019/6xxx/CVE-2019-6467.json
- 2019/6xxx/CVE-2019-6468.json
- 2019/6xxx/CVE-2019-6469.json
- 2019/6xxx/CVE-2019-6471.json
Resubmitting (via github) previously-submitted CVE list updates that were rejected
because e-mail submission is no longer supported.
> [ISC] update vuln info for 9 CVEs from 2018 & 2019, processing backlog

- 2019/9xxx/CVE-2019-9536.json
This was made public in 2017, I forget the current year rules, but maybe change to a 2017 ID?
We have confirmed with the vendor CNA (Apple) that they do not intend to assign for this vulnerability.
Apple does intend to assign for checkm8 but has not yet.
> 2017 alloc8 vulnerability in iPhone 3GS

- 2019/16xxx/CVE-2019-16763.json
Adding this advisory: https://github.com/mpetroff/pannellum/security/advisories/GHSA-m52x-29pq-w3vv
This has been assigned CVE-2019-16763 by the GitHub CNA
> add CVE-2019-16763

- 2019/16xxx/CVE-2019-16766.json
add CVE-2019-16766 for https://github.com/labd/wagtail-2fa/security/advisories/GHSA-89px-ww3j-g2mm
> add CVE-2019-16766

- 2019/16xxx/CVE-2019-16771.json
Correcting a mistake in the github commit that was initially linked from CVE-2019-16771.
Now the CVE links to https://github.com/line/armeria/commit/b597f7a865a527a84ee3d6937075cfbb4470ed20 which is the correct fix commit for GHSA-35fr-h7jr-hh86.
Thanks `@JLLeitschuh` for notifying us about this innacuracy 🙇
> update CVE-2019-16771 with correct reference

- 2019/16xxx/CVE-2019-16786.json
add CVE-2019-16786 for GHSA-g2xc-35jw-c63p
> add CVE-2019-16786 for GHSA-g2xc-35jw-c63p

- 2019/16xxx/CVE-2019-16780.json
in the initial submission, the version value was "3.5.1".  This corrects it to 5.3.1.
> correct mistake in CVE-2019-16780 version_data

- 2020/2xxx/CVE-2020-2555.json
Oracle Critical Patch Update Advisory - January 2020 Rev 4.
On branch cna/Oracle/CPU2020JanRev4
modified:   2020/2xxx/CVE-2020-2555.json
> Bill Situ <Bill.Situ@Oracle.com>

- 2020/5xxx/CVE-2020-5207.json
add CVE-2020-5207 for GHSA-xrr9-rh8p-433v
> add CVE-2020-5207 for GHSA-xrr9-rh8p-433v

- 2019/16xxx/CVE-2019-16770.json
This updates description of CVE-2019-16770 to note the correct affected versions, and patched versions of the Puma package.
This is in response to a message from MITRE that someone noted the incorrect data.
> update description of CVE-2019-16770 with correct fix version

- 2017/3xxx/CVE-2017-3146.json
- 2017/3xxx/CVE-2017-3147.json
- 2017/3xxx/CVE-2017-3148.json
- 2017/3xxx/CVE-2017-3149.json
- 2018/5xxx/CVE-2018-5746.json
- 2019/6xxx/CVE-2019-6466.json
Rejecting 6 additional numbers allocated in 2017, 2018, and 2019
> ISC.org: reject additional unused allocated numbers

- 2020/5xxx/CVE-2020-5239.json
add CVE-2020-5239 for GHSA-2467-p5gv-58q6
> add CVE-2020-5239 for GHSA-2467-p5gv-58q6

- 2019/19xxx/CVE-2019-19757.json
- 2019/19xxx/CVE-2019-19758.json
- 2019/19xxx/CVE-2019-19762.json
- 2019/19xxx/CVE-2019-19763.json
- 2019/19xxx/CVE-2019-19764.json
- 2019/19xxx/CVE-2019-19765.json
- 2019/6xxx/CVE-2019-6190.json
- 2019/6xxx/CVE-2019-6193.json
- 2019/6xxx/CVE-2019-6194.json
- 2019/6xxx/CVE-2019-6195.json
Populated CVEs for February advisories and set unused 2019 CVEs to REJECT.
> 2020-02-14

- 2019/1xxx/CVE-2019-1950.json
The CVE entry was incorrect and was pointing to the wrong vulnerability.
> Updating Cisco CVE-2019-1950

- 2020/5xxx/CVE-2020-5234.json
update CVE-2020-5234 with correct fix versions
https://github.com/neuecc/MessagePack-CSharp/security/advisories/GHSA-7q36-4xx7-xcxf was updated with new info about fix versions.  This PR changes the CVE info so it has the latest info from the maintainer.
> update CVE-2020-5234 with correct fix versions

- 2020/5xxx/CVE-2020-5247.json
update description of CVE-2020-5247 - correct version
We received a request from a CVE user to update the description for CVE-2020-5247 to note the proper fix version in the description of 3.12.3.  This updates that description.
> update description of CVE-2020-5247 - correct version

- 2020/5xxx/CVE-2020-5258.json
add CVE-2020-5258 for GHSA-jxfh-8wgv-vfr2
> add CVE-2020-5258 for GHSA-jxfh-8wgv-vfr2

- 2019/1xxx/CVE-2019-1551.json
OpenSSL 1.1.1e/1.0.2u are now released so the "-dev" tag is no longer appropriate.
> Update the entry for CVE-2019-1551

- 2020/5xxx/CVE-2020-5261.json
The prior description failed to note that this vulnerability does not affect versions before 2.0.0.  This new description notes that, and also has some other wording changes for more readability.
> updated description for CVE-2020-5261

- 2020/8xxx/CVE-2020-8910.json
Committing CVE-2020-8910 on Closure-Library.
https://github.com/google/closure-library/releases/tag/v20200315
> Adding CVE-2020-8910

- 2020/5xxx/CVE-2020-5255.json
correct versions for CVE-2020-5255 / https://github.com/symfony/symfony/security/advisories/GHSA-mcx4-f5f5-4859
> correct versions for CVE-2020-5255

- 2020/8xxx/CVE-2020-8835.json
Signed-off-by: Steve Beattie <steve.beattie@canonical.com>
> Canonical CNA: add CVE-2020-8835 / linux kernel / USN-4313-1

- 2020/10xxx/CVE-2020-10889.json
- 2020/10xxx/CVE-2020-10890.json
- 2020/10xxx/CVE-2020-10891.json
- 2020/10xxx/CVE-2020-10892.json
- 2020/10xxx/CVE-2020-10893.json
- 2020/10xxx/CVE-2020-10894.json
- 2020/10xxx/CVE-2020-10895.json
- 2020/10xxx/CVE-2020-10896.json
- 2020/10xxx/CVE-2020-10897.json
- 2020/10xxx/CVE-2020-10898.json
- 2020/10xxx/CVE-2020-10899.json
- 2020/10xxx/CVE-2020-10900.json
- 2020/10xxx/CVE-2020-10901.json
- 2020/10xxx/CVE-2020-10902.json
- 2020/10xxx/CVE-2020-10903.json
- 2020/10xxx/CVE-2020-10904.json
- 2020/10xxx/CVE-2020-10905.json
- 2020/10xxx/CVE-2020-10906.json
- 2020/10xxx/CVE-2020-10907.json
- 2020/10xxx/CVE-2020-10908.json
- 2020/10xxx/CVE-2020-10909.json
- 2020/10xxx/CVE-2020-10910.json
- 2020/10xxx/CVE-2020-10911.json
- 2020/10xxx/CVE-2020-10912.json
- 2020/10xxx/CVE-2020-10913.json
- 2020/10xxx/CVE-2020-10914.json
- 2020/10xxx/CVE-2020-10915.json
- 2020/8xxx/CVE-2020-8867.json
All are Foxit except the last 3, as indicated below 
M 2020/10xxx/CVE-2020-10889.json
M 2020/10xxx/CVE-2020-10890.json
M 2020/10xxx/CVE-2020-10891.json
M 2020/10xxx/CVE-2020-10892.json
M 2020/10xxx/CVE-2020-10893.json
M 2020/10xxx/CVE-2020-10894.json
M 2020/10xxx/CVE-2020-10895.json
M 2020/10xxx/CVE-2020-10896.json
M 2020/10xxx/CVE-2020-10897.json
M 2020/10xxx/CVE-2020-10898.json
M 2020/10xxx/CVE-2020-10899.json
M 2020/10xxx/CVE-2020-10900.json
M 2020/10xxx/CVE-2020-10901.json
M 2020/10xxx/CVE-2020-10902.json
M 2020/10xxx/CVE-2020-10903.json
M 2020/10xxx/CVE-2020-10904.json
M 2020/10xxx/CVE-2020-10905.json
M 2020/10xxx/CVE-2020-10906.json
M 2020/10xxx/CVE-2020-10907.json
M 2020/10xxx/CVE-2020-10908.json
M 2020/10xxx/CVE-2020-10909.json
M 2020/10xxx/CVE-2020-10910.json
M …
> ZDI assigns the following CVEs:

- 2020/7xxx/CVE-2020-7350.json
Instead of "5.0.84 and prior," the requested terminology was "before 5.0.85."
See CVEProject/cvelist#3663 wherein @iamleot requested this change, which is fine by me.
> Clarify Metasploit version numbers

- 2019/15xxx/CVE-2019-15791.json
- 2019/15xxx/CVE-2019-15792.json
- 2019/15xxx/CVE-2019-15793.json
- 2019/15xxx/CVE-2019-15794.json
Add CVEs CVE-2019-15791, CVE-2019-15792, CVE-2019-15793, and CVE-2019-15794.
> Canonical CNAs: Ubuntu shiftfs cves

- 2020/11xxx/CVE-2020-11021.json
- 2020/12xxx/CVE-2020-12465.json
This adds a CVE for Trixbox CE, first disclosed by a Metasploit contributor
> Populate CVE-2020-7351

- 2012/0xxx/CVE-2012-0952.json
- 2012/0xxx/CVE-2012-0953.json
Hello, some of our old assignments are missing from the git tree; here's two nvidia linux kernel driver issues that the Ubuntu Security Team assigned numbers to.
Thanks
> add historical nvidia cves assigned by canonical

- 2020/3xxx/CVE-2020-3327.json
- 2020/3xxx/CVE-2020-3341.json
Adding two CVEs for the ClamAV 0.10.23 security patch.
- CVE-2020-3327.json
- CVE-2020-3341.json
> Adding two CVEs for the ClamAV 0.10.23 security patch

- 2020/1xxx/CVE-2020-1998.json
- 2020/2xxx/CVE-2020-2001.json
- 2020/2xxx/CVE-2020-2002.json
- 2020/2xxx/CVE-2020-2003.json
- 2020/2xxx/CVE-2020-2005.json
- 2020/2xxx/CVE-2020-2013.json
- 2020/2xxx/CVE-2020-2015.json
- 2020/2xxx/CVE-2020-2016.json
- 2020/2xxx/CVE-2020-2017.json
- 2020/2xxx/CVE-2020-2018.json
Updated description of CVE-2020-2016 to include affected versions.
Removed a version that is not generally available.
> Update affected version numbers

- 2020/11xxx/CVE-2020-11057.json
Per request from the security researcher and maintainer, this updates CVE-2020-11057 to have a reference to the [medium post](https://medium.com/@andrew.levkin/tews-4c47cfc011d1) made by the researcher, and also it changes the CVSS so it is now considered critical severity.
> update CVE-2020-11057 extra reference and cvss

- 2020/11xxx/CVE-2020-11078.json
add CVE-2020-11078 for GHSA-gg84-qgv9-w4pq
> add CVE-2020-11078 for GHSA-gg84-qgv9-w4pq

- 2020/10xxx/CVE-2020-10516.json
This PR adds CVE-2020-10516, the first published CVE from the GitHub Products CNA which covers issues in GitHub Enterprise Server. Feel free to reach out to product-cna@github.com or directly on this PR with any questions.
> Add CVE-2020-10516

- 2020/1xxx/CVE-2020-1703.json
This CVE is rejected. And will be removed from Red Hat pages once rejection is confirmed by Mitre.
> *REJECT* CVE-2020-1703

- 2020/11xxx/CVE-2020-11099.json
add CVE-2020-11099 for GHSA-977w-866x-4v5h
> add CVE-2020-11099 for GHSA-977w-866x-4v5h

- 2020/15xxx/CVE-2020-15087.json
add CVE-2020-15087 for GHSA-f6pc-crhh-cp96
> add CVE-2020-15087 for GHSA-f6pc-crhh-cp96

- 2020/4xxx/CVE-2020-4074.json
A typo was made on initial submission of CVE-2020-4074 where the version number was specified in several places as `1.7.7.6` instead of the correct `1.7.6.6`.  This PR corrects that.
Reference: https://github.com/PrestaShop/PrestaShop/security/advisories/GHSA-ccvh-jh5x-mpg4
> update CVE-2020-4074 to fix version number typo

- 2020/11xxx/CVE-2020-11074.json
A typo was made on initial submission of CVE-2020-11074 where the version number was specified in several places as `1.7.7.6` instead of the correct `1.7.6.6`.  This PR corrects that.
Reference: https://github.com/PrestaShop/PrestaShop/security/advisories/GHSA-v4pg-q2cv-f7x4
Also, this is exactly like the typo fixed for CVE-2020-4074 [here](https://github.com/CVEProject/cvelist/pull/4263)
> update CVE-2020-11074 to fix version number typo

- 2019/17xxx/CVE-2019-17639.json
> CVE-2019-17639

- 2020/3xxx/CVE-2020-3481.json
A vulnerability in the EGG archive parsing module in Clam AntiVirus (ClamAV) Software versions 0.102.0 - 0.102.3 could allow an unauthenticated, remote attacker to cause a denial of service condition on an affected device. The vulnerability is due to a null pointer dereference. An attacker could exploit this vulnerability by sending a crafted EGG file to an affected device. An exploit could allow the attacker to cause the ClamAV scanning process crash, resulting in a denial of service condition.
> Adding ClamAV CVE-2020-3481

- 2020/3xxx/CVE-2020-3442.json
The DuoConnect client enables users to establish SSH connections to hosts protected by a DNG instance. When a user initiates an SSH connection to a DNG-protected host for the first time using DuoConnect, the user’s browser is opened to a login screen in order to complete authentication determined by the contents of the '-relay' argument. If the ‘-relay’ is set to a URL beginning with \"http://\", then the browser will initially attempt to load the URL over an insecure HTTP connection, before being immediately redirected to HTTPS (in addition to standard redirect mechanisms, the DNG uses HTTP Strict Transport Security headers to enforce this). After successfully authenticating to a DNG, DuoConnect stores an authentication token in a local system cache, so users do not have to complete this …
> Adding Cisco DUO CVE-2020-3442

- 2020/8xxx/CVE-2020-8559.json
> Correct affected versions for cve-2020-8559

- 2020/15xxx/CVE-2020-15120.json
Thanks to @iamleot for for [noting in the original submission for CVE-2020-15120](https://github.com/CVEProject/cvelist/pull/4417#issuecomment-664885361) that the description did not name the affected software.  This update adds the affected software name, which happens to be ["I hate money"](https://github.com/spiral-project/ihatemoney) (which is an open source budgeting application).
> update CVE-2020-15120 so description names affected software

- 2020/15xxx/CVE-2020-15136.json
Add CVE-2020-15136 for GHSA-wr2v-9rpq-c35q
> Add CVE-2020-15136 for GHSA-wr2v-9rpq-c35q

- 2020/10xxx/CVE-2020-10289.json
Our team at @aliasrobotics identified and reported in RVD#2401 the use of
unsafe yaml load (aliasrobotics/RVD#2401).
After triaging the flaw we detected that it was exploitable and could lead to
local (or remote, based on certain common user interaction) code execution.
Specifically, the flaw itself is caused by an unsafe parsing of YAML values which
happens whenever an action message is processed to be sent, and allows for the
creation of Python objects. Through this flaw in ROS, an attacker could build a
malicious payload and execute arbitrary code in Python. A PoC is available but
have decided not to disclose it for now and until this is mitigated and debs are
available.
> Assign CVE-2020-10289

- 2020/10xxx/CVE-2020-10518.json
This PR adds CVE-2020-10518, which was patched and made public in the batch of GitHub Enterprise Server releases that were published yesterday, 8/26/20.
> Add CVE-2020-10518

- 2020/10xxx/CVE-2020-10517.json
This PR adds CVE-2020-10517, which was patched and made public in the batch of GitHub Enterprise Server releases that were published yesterday, 8/26/20.
> Add CVE-2020-10517

- 2020/15xxx/CVE-2020-15196.json
Add CVE-2020-15196 for GHSA-pg59-2f92-5cph
> Add CVE-2020-15196 for GHSA-pg59-2f92-5cph

- 2019/17xxx/CVE-2019-17444.json
Assigning CVE-2019-17444 for a default password vulnerability found by Palo Alto Networks Researchers on JFrog.
> CVE-2019-17444

- 2020/16xxx/CVE-2020-16124.json
Add json file for CVE-2020-16124.
> Update CVE-2020-16124: Integer overflow in ros:ros_comm

- 2020/15xxx/CVE-2020-15250.json
Per request from maintainer, the description for CVE-2020-15250 to note the floor version of 4.7.  See https://github.com/junit-team/junit4/issues/1676
> Update CVE-2020-15250 description

- 2020/15xxx/CVE-2020-15254.json
Add CVE-2020-15254 for GHSA-v5m7-53cv-f3hx
> Add CVE-2020-15254 for GHSA-v5m7-53cv-f3hx

- 2020/15xxx/CVE-2020-15264.json
Add CVE-2020-15264 for GHSA-rpgx-h675-r3jf
> Add CVE-2020-15264 for GHSA-rpgx-h675-r3jf

- 2020/15xxx/CVE-2020-15266.json
Add CVE-2020-15265 for GHSA-rrfp-j2mp-hq9c
> Add CVE-2020-15265 for GHSA-rrfp-j2mp-hq9c

- 2020/27xxx/CVE-2020-27216.json
> CVE-2020-27216
