CVEProject/cvelist

2020/5xxx/CVE-2020-5234.json

add CVE-2020-5234 for GHSA-7q36-4xx7-xcxf

add CVE-2020-5234 for GHSA-7q36-4xx7-xcxf

---

2019/4xxx/CVE-2019-4732.json
2020/4xxx/CVE-2020-4224.json

Added CVE-2020-4224 and CVE-2019-4732.

Ibm20200203 11443

---

2020/5xxx/CVE-2020-5235.json

add CVE-2020-5235 for GHSA-gcx3-7m76-287p

add CVE-2020-5235 for GHSA-gcx3-7m76-287p

---

2020/5xxx/CVE-2020-5236.json

add CVE-2020-5236 for GHSA-73m2-3pwg-5fgc

add CVE-2020-5236 for GHSA-73m2-3pwg-5fgc

---

2019/4xxx/CVE-2019-4451.json
2019/4xxx/CVE-2019-4540.json
2019/4xxx/CVE-2019-4541.json
2019/4xxx/CVE-2019-4548.json
2019/4xxx/CVE-2019-4550.json
2019/4xxx/CVE-2019-4551.json
2019/4xxx/CVE-2019-4562.json
2019/4xxx/CVE-2019-4674.json
2019/4xxx/CVE-2019-4675.json
2020/4xxx/CVE-2020-4163.json

Added CVE-2019-4548, CVE-2019-4541, CVE-2019-4540, CVE-2019-4451, CVE-2019-4674, CVE-2019-4550, CVE-2019-4562, CVE-2019-4551, CVE-2019-4675, and CVE-2020-4163.

Ibm20200204 114120

---

2019/5xxx/CVE-2019-5636.json
2019/5xxx/CVE-2019-5637.json

Per request in CVEProject#2750
Adds version info in the description.

Updating TwinCat vuln description

---

2020/5xxx/CVE-2020-5237.json

add CVE-2020-5237 for GHSA-x8wj-6m73-gfqp

add CVE-2020-5237 for GHSA-x8wj-6m73-gfqp

---

2020/5xxx/CVE-2020-5208.json

add CVE-2020-5208 for GHSA-g659-9qxw-p7cp

add CVE-2020-5208 for GHSA-g659-9qxw-p7cp

---

2019/4xxx/CVE-2019-4613.json
2019/4xxx/CVE-2019-4616.json
2019/4xxx/CVE-2019-4670.json

Added CVE-2019-4616, CVE-2019-4670, and CVE-2019-4613

Ibm20200205 10164

---

2019/11xxx/CVE-2019-11481.json
2019/11xxx/CVE-2019-11482.json
2019/11xxx/CVE-2019-11483.json
2019/11xxx/CVE-2019-11484.json
2019/11xxx/CVE-2019-11485.json

Hello, here's some of the outstanding 2019 CVEs from Ubuntu. Thanks.

apport and whoopsie issues from Kevin Backhouse and Sander Bos

---

2020/2xxx/CVE-2020-2109.json
2020/2xxx/CVE-2020-2110.json
2020/2xxx/CVE-2020-2111.json
2020/2xxx/CVE-2020-2112.json
2020/2xxx/CVE-2020-2113.json
2020/2xxx/CVE-2020-2114.json
2020/2xxx/CVE-2020-2115.json
2020/2xxx/CVE-2020-2116.json
2020/2xxx/CVE-2020-2117.json
2020/2xxx/CVE-2020-2118.json
2020/2xxx/CVE-2020-2119.json
2020/2xxx/CVE-2020-2120.json
2020/2xxx/CVE-2020-2121.json
2020/2xxx/CVE-2020-2122.json
2020/2xxx/CVE-2020-2123.json
2020/2xxx/CVE-2020-2124.json
2020/2xxx/CVE-2020-2125.json
2020/2xxx/CVE-2020-2126.json
2020/2xxx/CVE-2020-2127.json
2020/2xxx/CVE-2020-2128.json
2020/2xxx/CVE-2020-2129.json
2020/2xxx/CVE-2020-2130.json
2020/2xxx/CVE-2020-2131.json
2020/2xxx/CVE-2020-2132.json
2020/2xxx/CVE-2020-2133.json

https://jenkins.io/security/advisory/2020-02-12/

Add Jenkins 2020-02-12 CVEs

---

2019/1xxx/CVE-2019-1566.json
2020/1xxx/CVE-2020-1975.json
2020/1xxx/CVE-2020-1976.json
2020/1xxx/CVE-2020-1977.json

Newly published or updated CVEs.

Palo Alto Networks CVE updated Feb 12, 2020

---

2020/5xxx/CVE-2020-5241.json

add CVE-2020-5241 for GHSA-3jqw-vv45-mjhh

add CVE-2020-5241 for GHSA-3jqw-vv45-mjhh

---

2019/4xxx/CVE-2019-4592.json
2019/4xxx/CVE-2019-4666.json

Added CVE-2019-4666 and CVE-2019-4592.

Ibm20200213 103635

---

2020/7xxx/CVE-2020-7251.json

Publish CVE-2020-7251

---

2020/7xxx/CVE-2020-7252.json

Publish CVE-2020-7252

---

2019/4xxx/CVE-2019-4583.json
2019/4xxx/CVE-2019-4752.json

Added CVE-2019-4583 and CVE-2019-4752.

Ibm20200220 11403

---

2020/5xxx/CVE-2020-5242.json

add CVE-2020-5242 for GHSA-w698-693g-23hv

add CVE-2020-5242 for GHSA-w698-693g-23hv

---

2020/5xxx/CVE-2020-5243.json

add CVE-2020-5243 for GHSA-cmcx-xhr8-3w9p

add CVE-2020-5243 for GHSA-cmcx-xhr8-3w9p

---

2019/3xxx/CVE-2019-3670.json

CVE already Live

---

2019/4xxx/CVE-2019-4595.json
2019/4xxx/CVE-2019-4703.json
2019/4xxx/CVE-2019-4745.json
2020/4xxx/CVE-2020-4210.json
2020/4xxx/CVE-2020-4211.json
2020/4xxx/CVE-2020-4212.json
2020/4xxx/CVE-2020-4213.json
2020/4xxx/CVE-2020-4222.json

Added CVE-2019-4595, CVE-2019-4703, CVE-2019-4745, CVE-2020-4210, CVE-2020-4211, CVE-2020-4212, CVE-2020-4213, and CVE-2020-4222.

Ibm20200224 103332

---

2020/5xxx/CVE-2020-5244.json

add CVE-2020-5244 for GHSA-3j78-7m59-r7gv

add CVE-2020-5244 for GHSA-3j78-7m59-r7gv

---

2020/5xxx/CVE-2020-5245.json

add CVE-2020-5245 for GHSA-3mcp-9wr4-cjqf

add CVE-2020-5245 for GHSA-3mcp-9wr4-cjqf

---

2019/4xxx/CVE-2019-4557.json
2019/4xxx/CVE-2019-4672.json

Added CVE-2019-4557 and CVE-2019-4672.

Ibm20200225 8498

---

2019/4xxx/CVE-2019-4537.json
2019/4xxx/CVE-2019-4596.json
2019/4xxx/CVE-2019-4597.json
2019/4xxx/CVE-2019-4598.json
2019/4xxx/CVE-2019-4726.json

Added CVE-2019-4537, CVE-2019-4596, CVE-2019-4597, CVE-2019-4598, and CVE-2019-4726.

Ibm20200226 10530

---

2019/4xxx/CVE-2019-4669.json

Ibm20200227 11542

---

2020/5xxx/CVE-2020-5247.json

add CVE-2020-5247 for GHSA-84j7-475p-hp8v

add CVE-2020-5247 for GHSA-84j7-475p-hp8v

---

2020/4xxx/CVE-2020-4283.json
2020/4xxx/CVE-2020-4292.json

Added CVE-2020-4292, CVE-2020-4283.

Ibm20200302 85421

---

2020/5xxx/CVE-2020-5249.json

add CVE-2020-5249 for GHSA-33vf-4xgg-9r58

add CVE-2020-5249 for GHSA-33vf-4xgg-9r58

---

2020/1xxx/CVE-2020-1888.json
2020/1xxx/CVE-2020-1892.json
2020/1xxx/CVE-2020-1893.json

Pushing CVEs for latest HHVM release.

CVEs for latest HHVM release

---

2020/5xxx/CVE-2020-5535.json
2020/5xxx/CVE-2020-5536.json

- CVE-2020-5535
- CVE-2020-5536

JPCERT/CC 2020-03-04

---

2020/5xxx/CVE-2020-5251.json

add CVE-2020-5251 for GHSA-h4mf-75hf-67w4

add CVE-2020-5251 for GHSA-h4mf-75hf-67w4

---

2020/5xxx/CVE-2020-5250.json

add CVE-2020-5250 for GHSA-mhfc-6rhg-fxp3

add CVE-2020-5250 for GHSA-mhfc-6rhg-fxp3

---

2020/4xxx/CVE-2020-4217.json

Ibm20200309 103417

---

2020/2xxx/CVE-2020-2134.json
2020/2xxx/CVE-2020-2135.json
2020/2xxx/CVE-2020-2136.json
2020/2xxx/CVE-2020-2137.json
2020/2xxx/CVE-2020-2138.json
2020/2xxx/CVE-2020-2139.json
2020/2xxx/CVE-2020-2140.json
2020/2xxx/CVE-2020-2141.json
2020/2xxx/CVE-2020-2142.json
2020/2xxx/CVE-2020-2143.json
2020/2xxx/CVE-2020-2144.json
2020/2xxx/CVE-2020-2145.json
2020/2xxx/CVE-2020-2146.json
2020/2xxx/CVE-2020-2147.json
2020/2xxx/CVE-2020-2148.json
2020/2xxx/CVE-2020-2149.json
2020/2xxx/CVE-2020-2150.json
2020/2xxx/CVE-2020-2151.json
2020/2xxx/CVE-2020-2152.json
2020/2xxx/CVE-2020-2153.json
2020/2xxx/CVE-2020-2154.json
2020/2xxx/CVE-2020-2155.json
2020/2xxx/CVE-2020-2156.json
2020/2xxx/CVE-2020-2157.json
2020/2xxx/CVE-2020-2158.json
2020/2xxx/CVE-2020-2159.json

https://jenkins.io/security/advisory/2020-03-09/

Add CVEs for 2020-03-09 Jenkins security advisory

---

2020/5xxx/CVE-2020-5256.json

add CVE-2020-5256 for GHSA-g9rq-x4fj-f5hx

add CVE-2020-5256 for GHSA-g9rq-x4fj-f5hx

---

2019/4xxx/CVE-2019-4608.json
2020/4xxx/CVE-2020-4162.json

Added CVE-2019-4608 and CVE-2020-4162.

Ibm20200310 7506

---

2019/17xxx/CVE-2019-17636.json

CVE-2019-17636

---

2020/5xxx/CVE-2020-5253.json

add CVE-2020-5253 for GHSA-2c7p-3fj4-223m

add CVE-2020-5253 for GHSA-2c7p-3fj4-223m

---

2020/5xxx/CVE-2020-5254.json

add CVE-2020-5254 for GHSA-2ch6-6r8h-m2p9

add CVE-2020-5254 for GHSA-2ch6-6r8h-m2p9

---

2020/5xxx/CVE-2020-5259.json

add CVE-2020-5259 for GHSA-3hw5-q855-g6cw

add CVE-2020-5259 for GHSA-3hw5-q855-g6cw

---

2020/7xxx/CVE-2020-7253.json

Publish CVE-2020-7253

---

2020/7xxx/CVE-2020-7254.json

Publish CVE-2020-7254

---

2019/5xxx/CVE-2019-5648.json

Issue with Barracuda ADC Load Balancer.

Add info for CVE-2019-5648

---

2020/5xxx/CVE-2020-5257.json

add CVE-2020-5257 for GHSA-2p5p-m353-833w

add CVE-2020-5257 for GHSA-2p5p-m353-833w

---

2020/5xxx/CVE-2020-5240.json

add CVE-2020-5240 for GHSA-9gjv-6qq6-v7qm

add CVE-2020-5240 for GHSA-9gjv-6qq6-v7qm

---

2020/4xxx/CVE-2020-4203.json
2020/4xxx/CVE-2020-4205.json

Added CVE-2020-4205 and CVE-2020-4203.

Ibm20200319 9377

---

2020/5xxx/CVE-2020-5262.json

add CVE-2020-5262 for GHSA-2wx6-wc87-rmjm

add CVE-2020-5262 for GHSA-2wx6-wc87-rmjm

---

2020/5xxx/CVE-2020-5267.json

add CVE-2020-5267 for GHSA-65cv-r6x7-79hv

add CVE-2020-5267 for GHSA-65cv-r6x7-79hv

---

2020/8xxx/CVE-2020-8871.json
2020/8xxx/CVE-2020-8872.json
2020/8xxx/CVE-2020-8873.json
2020/8xxx/CVE-2020-8874.json
2020/8xxx/CVE-2020-8875.json
2020/8xxx/CVE-2020-8876.json

M  CVE-2020-8871.json
M  CVE-2020-8872.json
M  CVE-2020-8873.json
M  CVE-2020-8874.json
M  CVE-2020-8875.json
M  CVE-2020-8876.json

ZDI assigns the following Parallels CVEs:

---

2020/5xxx/CVE-2020-5252.json

add CVE-2020-5252 for GHSA-7q25-qrjw-6fg2

add CVE-2020-5252 for GHSA-7q25-qrjw-6fg2

---

2019/4xxx/CVE-2019-4553.json
2019/4xxx/CVE-2019-4681.json
2020/4xxx/CVE-2020-4253.json
2020/4xxx/CVE-2020-4309.json

Added CVE-2019-4681, CVE-2019-4553, CVE-2020-4253, and CVE-2020-4309.

Ibm20200324 111412

---

2020/5xxx/CVE-2020-5261.json

add CVE-2020-5261 for GHSA-g6j2-ch25-5mmv

add CVE-2020-5261 for GHSA-g6j2-ch25-5mmv

---

2020/5xxx/CVE-2020-5552.json
2020/5xxx/CVE-2020-5553.json
2020/5xxx/CVE-2020-5554.json
2020/5xxx/CVE-2020-5555.json
2020/5xxx/CVE-2020-5556.json
2020/5xxx/CVE-2020-5557.json
2020/5xxx/CVE-2020-5558.json
2020/5xxx/CVE-2020-5559.json
2020/5xxx/CVE-2020-5560.json
2020/5xxx/CVE-2020-5561.json

Changed paths:
M 2020/5xxx/CVE-2020-5552.json
M 2020/5xxx/CVE-2020-5553.json
M 2020/5xxx/CVE-2020-5554.json
M 2020/5xxx/CVE-2020-5555.json
M 2020/5xxx/CVE-2020-5556.json
M 2020/5xxx/CVE-2020-5557.json
M 2020/5xxx/CVE-2020-5558.json
M 2020/5xxx/CVE-2020-5559.json
M 2020/5xxx/CVE-2020-5560.json
M 2020/5xxx/CVE-2020-5561.json

JPCERT/CC 2020-03-25

---

2020/2xxx/CVE-2020-2160.json
2020/2xxx/CVE-2020-2161.json
2020/2xxx/CVE-2020-2162.json
2020/2xxx/CVE-2020-2163.json
2020/2xxx/CVE-2020-2164.json
2020/2xxx/CVE-2020-2165.json
2020/2xxx/CVE-2020-2166.json
2020/2xxx/CVE-2020-2167.json
2020/2xxx/CVE-2020-2168.json
2020/2xxx/CVE-2020-2169.json
2020/2xxx/CVE-2020-2170.json
2020/2xxx/CVE-2020-2171.json

https://jenkins.io/security/advisory/2020-03-25/

Add CVEs for 2020-03-25 Jenkins security advisory

---

2020/5xxx/CVE-2020-5280.json

add CVE-2020-5280 for GHSA-66q9-f7ff-mmx6

add CVE-2020-5280 for GHSA-66q9-f7ff-mmx6

---

2020/5xxx/CVE-2020-5281.json

add CVE-2020-5281 for GHSA-gj88-9q3f-72m3

add CVE-2020-5281 for GHSA-gj88-9q3f-72m3

---

2020/5xxx/CVE-2020-5282.json

add CVE-2020-5282 for GHSA-8xwp-r7pj-cgw3

add CVE-2020-5282 for GHSA-8xwp-r7pj-cgw3

---

2020/5xxx/CVE-2020-5277.json

add CVE-2020-5277 for GHSA-mmmv-m5q9-g3cm

add CVE-2020-5277 for GHSA-mmmv-m5q9-g3cm

---

2020/8xxx/CVE-2020-8923.json

Adding CVE for Google Dart Lang
https://github.com/dart-lang/sdk/security/advisories/GHSA-hfq3-v9pv-p627

CVE-2020-8923

---

2020/5xxx/CVE-2020-5129.json

SonicWall SMA1000 DoS vulnerability on Extraweb server

SonicWall SMA1000 DoS Vulnerability

---

2020/7xxx/CVE-2020-7260.json

Publish CVE-2020-7260.json

---

2019/15xxx/CVE-2019-15795.json
2019/15xxx/CVE-2019-15796.json

Hello, these are 2 python-apt CVEs from Ubuntu, thank you.

python-apt issues

---

2020/4xxx/CVE-2020-4276.json

Ibm20200326 91819

---

2020/7xxx/CVE-2020-7260.json

Update CVE-2020-7260 with acknowledgment

---

2020/5xxx/CVE-2020-5255.json

add CVE-2020-5255 for GHSA-mcx4-f5f5-4859

add CVE-2020-5255 for GHSA-mcx4-f5f5-4859

---

2020/5xxx/CVE-2020-5274.json

add CVE-2020-5274 for GHSA-m884-279h-32v2

add CVE-2020-5274 for GHSA-m884-279h-32v2

---

2020/5xxx/CVE-2020-5275.json

add CVE-2020-5275 for GHSA-g4m9-5hpf-hx72

add CVE-2020-5275 for GHSA-g4m9-5hpf-hx72

---

2020/5xxx/CVE-2020-5284.json

add CVE-2020-5284 for GHSA-fq77-7p7r-83rj

add CVE-2020-5284 for GHSA-fq77-7p7r-83rj

---

2020/5xxx/CVE-2020-5289.json

add CVE-2020-5289 for GHSA-2mxr-89gf-rc4v

add CVE-2020-5289 for GHSA-2mxr-89gf-rc4v

---

2020/5xxx/CVE-2020-5291.json

add CVE-2020-5291 for GHSA-j2qp-rvxj-43vj

add CVE-2020-5291 for GHSA-j2qp-rvxj-43vj

---

2020/5xxx/CVE-2020-5292.json

add CVE-2020-5292 for GHSA-ww6x-rhvp-55hp

add CVE-2020-5292 for GHSA-ww6x-rhvp-55hp

---

2020/7xxx/CVE-2020-7263.json

Publish CVE-2020-7263

---

2020/5xxx/CVE-2020-5290.json

add CVE-2020-5290 for GHSA-p5fh-2vhw-fvpq

add CVE-2020-5290 for GHSA-p5fh-2vhw-fvpq

---

2020/4xxx/CVE-2020-4303.json
2020/4xxx/CVE-2020-4304.json
2020/4xxx/CVE-2020-4325.json

Added CVE-2020-4303, CVE-2020-4304, and CVE-2020-4325.

Ibm20200402 101346

---

2020/1xxx/CVE-2020-1773.json

to make dependency to CVE-2020-1772.json more clear

Changed description of OSA-2020-10

---

2020/7xxx/CVE-2020-7009.json

Update the description based on the comment in 
https://github.com/CVEProject/cvelist/pull/3504#pullrequestreview-385026908

Update version descriptions

---

2020/7xxx/CVE-2020-7617.json

Add CVE-2020-7617 (https://snyk.io/vuln/SNYK-JS-INIPARSER-564122)

Add CVE-2020-7617

---

2020/5xxx/CVE-2020-5283.json

add CVE-2020-5283 for GHSA-xpxf-fvqv-7mfg

add CVE-2020-5283 for GHSA-xpxf-fvqv-7mfg

---

2020/4xxx/CVE-2020-4273.json

Ibm20200403 83339

---

2020/5xxx/CVE-2020-5300.json

add CVE-2020-5300 for GHSA-3p3g-vpw6-4w66

add CVE-2020-5300 for GHSA-3p3g-vpw6-4w66

---

2020/2xxx/CVE-2020-2172.json
2020/2xxx/CVE-2020-2173.json
2020/2xxx/CVE-2020-2174.json
2020/2xxx/CVE-2020-2175.json
2020/2xxx/CVE-2020-2176.json

https://jenkins.io/security/advisory/2020-04-07/

Add CVEs for Jenkins 2020-04-07 security advisory

---

2020/5xxx/CVE-2020-5302.json

add CVE-2020-5302 for GHSA-7hf3-wvp8-34r9

add CVE-2020-5302 for GHSA-7hf3-wvp8-34r9

---

2019/15xxx/CVE-2019-15789.json

Hello, this is CVE-2019-15789 for Microk8s from Ubuntu, thank you.

Microk8s issue

---

2019/4xxx/CVE-2019-4601.json
2019/4xxx/CVE-2019-4602.json
2019/4xxx/CVE-2019-4603.json
2019/4xxx/CVE-2019-4737.json
2019/4xxx/CVE-2019-4740.json
2019/4xxx/CVE-2019-4746.json
2020/4xxx/CVE-2020-4164.json
2020/4xxx/CVE-2020-4252.json
2020/4xxx/CVE-2020-4282.json
2020/4xxx/CVE-2020-4284.json
2020/4xxx/CVE-2020-4289.json
2020/4xxx/CVE-2020-4290.json
2020/4xxx/CVE-2020-4291.json

Added CVE-2019-4602, CVE-2019-4601, CVE-2019-4603, CVE-2019-4737, CVE-2019-4740, CVE-2019-4746, CVE-2020-4164, CVE-2020-4252, CVE-2020-4282, CVE-2020-4284, CVE-2020-4289, CVE-2020-4290, and CVE-2020-4291.

Ibm20200408 9595

---

2020/11xxx/CVE-2020-11000.json

add CVE-2020-11000 for GHSA-7x3j-7x5w-8g7w

add CVE-2020-11000 for GHSA-7x3j-7x5w-8g7w

---

2020/5xxx/CVE-2020-5302.json

update references in CVE-2020-5302

update references in CVE-2020-5302

---

2020/5xxx/CVE-2020-5263.json

add CVE-2020-5263 for GHSA-prfq-f66g-43mp

add CVE-2020-5263 for GHSA-prfq-f66g-43mp

---

2020/8xxx/CVE-2020-8834.json

Signed-off-by: Steve Beattie <steve.beattie@canonical.com>

Canonical CNA: add info for CVE-2020-8834

---

2020/8xxx/CVE-2020-8832.json

Signed-off-by: Steve Beattie <steve.beattie@canonical.com>

Canonical CNA: add info for CVE-2020-8832

---

2019/7xxx/CVE-2019-7305.json

Hello, this is CVE-2019-7305 from Ubuntu, thank you

CVE-2019-7305 - eXtplorer vulnerability

---

2020/5xxx/CVE-2020-5303.json

add CVE-2020-5303 for GHSA-v24h-pjjv-mcp6

add CVE-2020-5303 for GHSA-v24h-pjjv-mcp6

---

2020/11xxx/CVE-2020-11002.json

add CVE-2020-11002 for GHSA-8jpx-m2wh-2v34

add CVE-2020-11002 for GHSA-8jpx-m2wh-2v34

---

2020/4xxx/CVE-2020-4151.json

Ibm20200414 1173

---

2019/10xxx/CVE-2019-10934.json
2019/10xxx/CVE-2019-10936.json
2019/10xxx/CVE-2019-10939.json
2019/13xxx/CVE-2019-13940.json
2019/19xxx/CVE-2019-19282.json
2019/19xxx/CVE-2019-19300.json
2019/19xxx/CVE-2019-19301.json
2020/7xxx/CVE-2020-7574.json
2020/7xxx/CVE-2020-7575.json

See attached our Pull Request for Siemens AD-2020-04

Siemens CVE update for Siemens-AD-2020-04

---

2020/8xxx/CVE-2020-8316.json
2020/8xxx/CVE-2020-8318.json
2020/8xxx/CVE-2020-8319.json
2020/8xxx/CVE-2020-8324.json
2020/8xxx/CVE-2020-8327.json

Populating CVEs for April '20 Advisories.

Lenovo April '20 Advisories

---

2020/11xxx/CVE-2020-11005.json

add CVE-2020-11005 for GHSA-wvpv-ffcv-r6cw

add CVE-2020-11005 for GHSA-wvpv-ffcv-r6cw

---

2020/5xxx/CVE-2020-5260.json

add CVE-2020-5260 for GHSA-qm7j-c969-7j4q

add CVE-2020-5260 for GHSA-qm7j-c969-7j4q

---

2020/11xxx/CVE-2020-11001.json

add CVE-2020-11001 for GHSA-v2wc-pfq2-5cm6

add CVE-2020-11001 for GHSA-v2wc-pfq2-5cm6

---

2020/11xxx/CVE-2020-11003.json

add CVE-2020-11003 for GHSA-j438-45hc-vjhm

add CVE-2020-11003 for GHSA-j438-45hc-vjhm

---

2020/7xxx/CVE-2020-7278.json

Publish CVE-2020-7278

---

2020/7xxx/CVE-2020-7276.json

Publish CVE-2020-7276

---

2020/7xxx/CVE-2020-7277.json

Publish CVE-2020-7277

---

2020/7xxx/CVE-2020-7274.json

Publish CVE-2020-7274

---

2020/7xxx/CVE-2020-7275.json

Publish CVE-2020-7275

---

2020/7xxx/CVE-2020-7273.json

Publish CVE-2020-7273

---

2020/7xxx/CVE-2020-7261.json

Publish CVE-2020-7261

---

2020/7xxx/CVE-2020-7259.json

Publish CVE-2020-7259

---

2020/7xxx/CVE-2020-7257.json

Publish CVE-2020-7257

---

2020/7xxx/CVE-2020-7250.json

Publish CVE-2020-7250

---

2020/7xxx/CVE-2020-7255.json

Publish CVE-2020-7255

---

2020/2xxx/CVE-2020-2177.json
2020/2xxx/CVE-2020-2178.json
2020/2xxx/CVE-2020-2179.json
2020/2xxx/CVE-2020-2180.json

https://jenkins.io/security/advisory/2020-04-16/

Add CVE IDs for 2020-04-16 Jenkins security advisory

---

2016/1xxx/CVE-2016-1421.json

Updating this old CVE from 2016 and adding additional information.

Updating Cisco CVE-2016-1421

---

2020/11xxx/CVE-2020-11007.json

add CVE-2020-11007 for GHSA-w8rc-pgxq-x2cj

add CVE-2020-11007 for GHSA-w8rc-pgxq-x2cj

---

2020/5xxx/CVE-2020-5266.json

Add CVE-2020-5266 for GHSA-vr7g-vqp5-966j

Add CVE-2020-5266 for GHSA-vr7g-vqp5-966j

---

2020/5xxx/CVE-2020-5273.json

Add CVE-2020-5273 for GHSA-cx2r-mf6x-55rx

Add CVE-2020-5273 for GHSA-cx2r-mf6x-55rx

---

2020/5xxx/CVE-2020-5294.json

Add CVE-2020-5294 for GHSA-774w-fg8p-7c8w

Add CVE-2020-5294 for GHSA-774w-fg8p-7c8w

---

2019/4xxx/CVE-2019-4446.json
2019/4xxx/CVE-2019-4644.json
2019/4xxx/CVE-2019-4749.json
2020/4xxx/CVE-2020-4277.json

Added CVE-2019-4446, CVE-2019-4644, CVE-2019-4749, and CVE-2020-4277.

Ibm20200417 92346

---

2020/5xxx/CVE-2020-5265.json

add CVE-2020-5265 for GHSA-7fmr-5vcc-329j

add CVE-2020-5265 for GHSA-7fmr-5vcc-329j

---

2020/5xxx/CVE-2020-5264.json

add CVE-2020-5264 for GHSA-48vj-vvr6-jj4f

add CVE-2020-5264 for GHSA-48vj-vvr6-jj4f

---

2020/5xxx/CVE-2020-5270.json

add CVE-2020-5270 for GHSA-375w-q56h-h7qc

add CVE-2020-5270 for GHSA-375w-q56h-h7qc

---

2020/5xxx/CVE-2020-5269.json

add CVE-2020-5269 for GHSA-87jh-7xpg-6v93

add CVE-2020-5269 for GHSA-87jh-7xpg-6v93

---

2020/5xxx/CVE-2020-5285.json

add CVE-2020-5285 for GHSA-j3r6-33hf-m8wh

add CVE-2020-5285 for GHSA-j3r6-33hf-m8wh

---

2020/5xxx/CVE-2020-5279.json

add CVE-2020-5279 for GHSA-74vp-ww64-w2gm

add CVE-2020-5279 for GHSA-74vp-ww64-w2gm

---

2020/5xxx/CVE-2020-5278.json

add CVE-2020-5278 for GHSA-mrpj-67mq-3fr5

add CVE-2020-5278 for GHSA-mrpj-67mq-3fr5

---

2020/5xxx/CVE-2020-5276.json

add CVE-2020-5276 for GHSA-q6pr-42v5-v97q

add CVE-2020-5276 for GHSA-q6pr-42v5-v97q

---

2020/5xxx/CVE-2020-5272.json

add CVE-2020-5272 for GHSA-rpg3-f23r-jmqv

add CVE-2020-5272 for GHSA-rpg3-f23r-jmqv

---

2020/5xxx/CVE-2020-5271.json

add CVE-2020-5271 for GHSA-m2x6-c2c6-pjrx

add CVE-2020-5271 for GHSA-m2x6-c2c6-pjrx

---

2020/5xxx/CVE-2020-5293.json

add CVE-2020-5293 for GHSA-cvjj-grfv-f56w

add CVE-2020-5293 for GHSA-cvjj-grfv-f56w

---

2020/5xxx/CVE-2020-5288.json

add CVE-2020-5288 for GHSA-4wxg-33h3-3w5r

add CVE-2020-5288 for GHSA-4wxg-33h3-3w5r

---

2020/5xxx/CVE-2020-5287.json

add CVE-2020-5287 for GHSA-r6rp-6gv6-r9hq

add CVE-2020-5287 for GHSA-r6rp-6gv6-r9hq

---

2020/5xxx/CVE-2020-5286.json

add CVE-2020-5286 for GHSA-98j8-hvjv-x47j

add CVE-2020-5286 for GHSA-98j8-hvjv-x47j

---

2020/11xxx/CVE-2020-11010.json

Add CVE-2020-11010 for GHSA-9j2c-x8qm-qmjq

Add CVE-2020-11010 for GHSA-9j2c-x8qm-qmjq

---

2020/1xxx/CVE-2020-1967.json

Segmentation fault in SSL_check_chain

Update details for CVE-2020-1967 (OpenSSL)

---

2020/5xxx/CVE-2020-5268.json

add CVE-2020-5268 for GHSA-9475-xg6m-j7pw

add CVE-2020-5268 for GHSA-9475-xg6m-j7pw

---

2020/5xxx/CVE-2020-5569.json

I committed incomplete description in #3627 . Please merge this update.

fix: incomplete description.

---

2020/8xxx/CVE-2020-8895.json

CVE-2020-8895 for Google Earth

---

2020/11xxx/CVE-2020-11008.json

add CVE-2020-11008 for GHSA-hjc9-x69f-jqj7

add CVE-2020-11008 for GHSA-hjc9-x69f-jqj7

---

2020/5xxx/CVE-2020-5301.json

add CVE-2020-5301 for GHSA-24m3-w8g9-jwpq

add CVE-2020-5301 for GHSA-24m3-w8g9-jwpq

---

2019/20xxx/CVE-2019-20102.json

Please let me know if any additional information is required.

Registering CVE-2019-20102 for an XSS in Confluence Server.

---

2020/2xxx/CVE-2020-2555.json

On branch cna/Oracle/CPU2020JanRev7
modified:   2020/2xxx/CVE-2020-2555.json

Bill Situ <Bill.Situ>

---

2020/11xxx/CVE-2020-11011.json

Add CVE-2020-11011 for GHSA-4j97-6w6q-gxjx

Add CVE-2020-11011 for GHSA-4j97-6w6q-gxjx

---

2020/8xxx/CVE-2020-8831.json
2020/8xxx/CVE-2020-8833.json

Hello,
These are CVEs CVE-2020-8831 and CVE-2020-8833 from Ubuntu
Thank you

Apport vulns

---

2020/11xxx/CVE-2020-11012.json

add CVE-2020-11012 for GHSA-xv4r-vccv-mg4w

add CVE-2020-11012 for GHSA-xv4r-vccv-mg4w

---

2019/4xxx/CVE-2019-4750.json
2019/4xxx/CVE-2019-4751.json
2020/4xxx/CVE-2020-4267.json

Added CVE-2019-4750, CVE-2019-4751, and CVE-2020-4267.

Ibm20200424 11488

---

2020/11xxx/CVE-2020-11013.json

add CVE-2020-11013 for GHSA-q8q8-93cv-v6h8

add CVE-2020-11013 for GHSA-q8q8-93cv-v6h8

---

2020/11xxx/CVE-2020-11004.json

add CVE-2020-11004 for GHSA-qh57-rcff-gx54

add CVE-2020-11004 for GHSA-qh57-rcff-gx54

---

2019/4xxx/CVE-2019-4729.json

Ibm20200427 92422

---

2020/7xxx/CVE-2020-7066.json
2020/7xxx/CVE-2020-7067.json

Also fix typo in CVE-2020-7066

Add PHP April 2020 CVE

---

2019/15xxx/CVE-2019-15790.json

Hello,
This is CVE-2019-15790 from Ubuntu.
Thank you

CVE-2019-15790 in Apport

---

2020/5xxx/CVE-2020-5570.json

Changed paths:
M 2020/5xxx/CVE-2020-5570.json

JPCERT/CC CVE-2020-5570

---

2020/4xxx/CVE-2020-4329.json

Ibm20200428 92427

---

2020/1xxx/CVE-2020-1774.json

OSA-2020-11

---

2020/11xxx/CVE-2020-11014.json

add CVE-2020-11014 for GHSA-cchm-grx2-g873

add CVE-2020-11014 for GHSA-cchm-grx2-g873

---

2019/4xxx/CVE-2019-4286.json
2019/4xxx/CVE-2019-4288.json

Added CVE-2019-4286, and CVE-2019-4288.

Ibm20200429 9448

---

2020/11xxx/CVE-2020-11009.json

add CVE-2020-11009 for GHSA-5679-7qrc-5m7j

add CVE-2020-11009 for GHSA-5679-7qrc-5m7j

---

2020/11xxx/CVE-2020-11020.json

add CVE-2020-11020 for GHSA-qpg4-4w7w-2mq5

add CVE-2020-11020 for GHSA-qpg4-4w7w-2mq5

---

2020/11xxx/CVE-2020-11021.json

add CVE-2020-11021 for GHSA-9w6v-m7wp-jwg4

add CVE-2020-11021 for GHSA-9w6v-m7wp-jwg4

---

2020/11xxx/CVE-2020-11024.json

Add CVE-2020-11024 for GHSA-g298-gp8q-h6j3

Add CVE-2020-11024 for GHSA-g298-gp8q-h6j3

---

2020/11xxx/CVE-2020-11023.json

Add CVE-2020-11023 for GHSA-jpcq-cgw6-v4j6

Add CVE-2020-11023 for GHSA-jpcq-cgw6-v4j6

---

2020/11xxx/CVE-2020-11022.json

Add CVE-2020-11022 for GHSA-gxr4-xjj5-5px2

Add CVE-2020-11022 for GHSA-gxr4-xjj5-5px2

---

2020/11xxx/CVE-2020-11022.json

Update version numbers for CVE-2020-11022

Update version numbers for CVE-2020-11022

---

2020/5xxx/CVE-2020-5237.json

- Description improved in collaboration with maintainer
- reference added, per request from maintainer
- CVSS vector adjusted in collaboration with maintainer

Update CVE-2020-5237 per request from maintainer

---

2020/11xxx/CVE-2020-11015.json

add CVE-2020-11015 for GHSA-5x54-39xq-cwvc

add CVE-2020-11015 for GHSA-5x54-39xq-cwvc

---

2020/11xxx/CVE-2020-11025.json

add CVE-2020-11025 for GHSA-4mhg-j6fx-5g3c

add CVE-2020-11025 for GHSA-4mhg-j6fx-5g3c

---

2020/11xxx/CVE-2020-11030.json

add CVE-2020-11030 for GHSA-vccm-6gmc-qhjh

add CVE-2020-11030 for GHSA-vccm-6gmc-qhjh

---

2020/11xxx/CVE-2020-11029.json

add CVE-2020-11029 for GHSA-568w-8m88-8g2c

add CVE-2020-11029 for GHSA-568w-8m88-8g2c

---

2020/11xxx/CVE-2020-11028.json

add CVE-2020-11028 for GHSA-xhx9-759f-6p2w

add CVE-2020-11028 for GHSA-xhx9-759f-6p2w

---

2020/11xxx/CVE-2020-11027.json

add CVE-2020-11027 for GHSA-ww7v-jg8c-q6jw

add CVE-2020-11027 for GHSA-ww7v-jg8c-q6jw

---

2020/11xxx/CVE-2020-11026.json

add CVE-2020-11026 for GHSA-3gw2-4656-pfr2

add CVE-2020-11026 for GHSA-3gw2-4656-pfr2

---

2020/11xxx/CVE-2020-11037.json

Add CVE-2020-11037 for GHSA-jjjr-3jcw-f8v6

Add CVE-2020-11037 for GHSA-jjjr-3jcw-f8v6

---

2020/11xxx/CVE-2020-11016.json

add CVE-2020-11016 for GHSA-rrhh-rcgp-q2m2

add CVE-2020-11016 for GHSA-rrhh-rcgp-q2m2

---

2020/11xxx/CVE-2020-11023.json

Update version numbers for CVE-2020-11023

Update version numbers for CVE-2020-11023

---

2020/1xxx/CVE-2020-1631.json

Hello,
Could you please approve the pull request

committing  JSA11021

---

2019/11xxx/CVE-2019-11823.json

Synology-SA-20:11

---

2020/4xxx/CVE-2020-4209.json

Ibm20200504 92750

---

2020/8xxx/CVE-2020-8895.json
2020/8xxx/CVE-2020-8896.json

CVE-2020-8896 for Google Earth Pro

---

2020/11xxx/CVE-2020-11051.json

Add CVE-2020-11051 for GHSA-vj72-c9vq-qxrv

Add CVE-2020-11051 for GHSA-vj72-c9vq-qxrv

---

2020/11xxx/CVE-2020-11032.json

Add CVE-2020-11032 for GHSA-344w-34h9-wwhh

Add CVE-2020-11032 for GHSA-344w-34h9-wwhh

---

2020/11xxx/CVE-2020-11033.json

Add CVE-2020-11033 for GHSA-rf54-3r4w-4h55

Add CVE-2020-11033 for GHSA-rf54-3r4w-4h55

---

2020/11xxx/CVE-2020-11034.json

Add CVE-2020-11034 for GHSA-gxv6-xq9q-37hg

Add CVE-2020-11034 for GHSA-gxv6-xq9q-37hg

---

2020/11xxx/CVE-2020-11035.json

Add CVE-2020-11035 for GHSA-w7q8-58qp-vmpf

Add CVE-2020-11035 for GHSA-w7q8-58qp-vmpf

---

2020/11xxx/CVE-2020-11036.json

Add CVE-2020-11036 for GHSA-3g3h-rwhr-7385

Add CVE-2020-11036 for GHSA-3g3h-rwhr-7385

---

2020/2xxx/CVE-2020-2181.json
2020/2xxx/CVE-2020-2182.json
2020/2xxx/CVE-2020-2183.json
2020/2xxx/CVE-2020-2184.json
2020/2xxx/CVE-2020-2185.json
2020/2xxx/CVE-2020-2186.json
2020/2xxx/CVE-2020-2187.json
2020/2xxx/CVE-2020-2188.json
2020/2xxx/CVE-2020-2189.json

https://www.jenkins.io/security/advisory/2020-05-06/

Add CVEs for 2020-05-06 Jenkins security advisory

---

2020/11xxx/CVE-2020-11042.json

Add CVE-2020-11042 for GHSA-9jp6-5vf2-cx2q

Add CVE-2020-11042 for GHSA-9jp6-5vf2-cx2q

---

2020/11xxx/CVE-2020-11044.json

Add CVE-2020-11044 for GHSA-cgqh-p732-6x2w

Add CVE-2020-11044 for GHSA-cgqh-p732-6x2w

---

2020/11xxx/CVE-2020-11045.json

Add CVE-2020-11045 for GHSA-3x39-248q-f4q6

Add CVE-2020-11045 for GHSA-3x39-248q-f4q6

---

2020/11xxx/CVE-2020-11046.json

Add CVE-2020-11046 for GHSA-hx48-wmmm-mr5q

Add CVE-2020-11046 for GHSA-hx48-wmmm-mr5q

---

2020/4xxx/CVE-2020-4427.json
2020/4xxx/CVE-2020-4428.json
2020/4xxx/CVE-2020-4429.json
2020/4xxx/CVE-2020-4430.json

Added CVE-2020-4430, CVE-2020-4427, CVE-2020-4428, and CVE-2020-4429.

Ibm20200507 151653

---

2020/11xxx/CVE-2020-11047.json

Add CVE-2020-11047 for GHSA-9fw6-m2q8-h5pw

Add CVE-2020-11047 for GHSA-9fw6-m2q8-h5pw

---

2020/11xxx/CVE-2020-11048.json

Add CVE-2020-11048 for GHSA-hv8w-f2hx-5gcv

Add CVE-2020-11048 for GHSA-hv8w-f2hx-5gcv

---

2020/11xxx/CVE-2020-11049.json

Add CVE-2020-11049 for GHSA-wwh7-r2r8-xjpr

Add CVE-2020-11049 for GHSA-wwh7-r2r8-xjpr

---

2020/11xxx/CVE-2020-11050.json

Add CVE-2020-11050 for GHSA-gw55-jm4h-x339

Add CVE-2020-11050 for GHSA-gw55-jm4h-x339

---

2020/11xxx/CVE-2020-11052.json

Add CVE-2020-11052 for GHSA-jc8m-cxhj-668x

Add CVE-2020-11052 for GHSA-jc8m-cxhj-668x

---

2020/11xxx/CVE-2020-11053.json

Add CVE-2020-11053 for GHSA-j7px-6hwj-hpjg

Add CVE-2020-11053 for GHSA-j7px-6hwj-hpjg

---

2020/11xxx/CVE-2020-11054.json

Add CVE-2020-11054 for GHSA-4rcq-jv2f-898j

Add CVE-2020-11054 for GHSA-4rcq-jv2f-898j

---

2020/11xxx/CVE-2020-11055.json

Add CVE-2020-11055 for GHSA-5vf7-q87h-pg6w

Add CVE-2020-11055 for GHSA-5vf7-q87h-pg6w

---

2020/11xxx/CVE-2020-11056.json

Add CVE-2020-11056 for GHSA-px8v-hxxx-2rgh

Add CVE-2020-11056 for GHSA-px8v-hxxx-2rgh

---

2015/7xxx/CVE-2015-7946.json

Hello,
This is CVE-2015-7946 from Ubuntu.
Thank you

Unity8 (Ubuntu) vulnerability

---

2014/1xxx/CVE-2014-1423.json

Signed-off-by: Steve Beattie <steve.beattie@canonical.com>

Canonical CNA: add CVE-2014-1423 online-accounts signond

---

2020/7xxx/CVE-2020-7264.json

Publish CVE-2020-7264.json

---

2020/7xxx/CVE-2020-7265.json

Publish CVE-2020-7265.json

---

2020/7xxx/CVE-2020-7266.json

Publish -2020-7266

---

2020/7xxx/CVE-2020-7267.json

Publish CVE-2020-7267

---

2020/7xxx/CVE-2020-7286.json

Publish CVE-2020-7286

---

2020/7xxx/CVE-2020-7285.json

Publish CVE-2020-7285

---

2020/7xxx/CVE-2020-7289.json

Publish CVE-2020-7289

---

2020/7xxx/CVE-2020-7288.json

Publish CVE-2020-7288

---

2020/7xxx/CVE-2020-7287.json

Publish CVE-2020-7287

---

2020/7xxx/CVE-2020-7291.json

Publish CVE-2020-7291

---

2020/7xxx/CVE-2020-7290.json

Publish CVE-2020-7290

---

2020/11xxx/CVE-2020-11006.json

Add CVE-2020-11006 for GHSA-8pc4-gvfw-634p

Add CVE-2020-11006 for GHSA-8pc4-gvfw-634p

---

2019/4xxx/CVE-2019-4667.json

Ibm20200511 131718

---

2017/14xxx/CVE-2017-14200.json
2020/10xxx/CVE-2020-10019.json
2020/10xxx/CVE-2020-10021.json
2020/10xxx/CVE-2020-10022.json
2020/10xxx/CVE-2020-10023.json
2020/10xxx/CVE-2020-10024.json
2020/10xxx/CVE-2020-10025.json
2020/10xxx/CVE-2020-10026.json
2020/10xxx/CVE-2020-10027.json
2020/10xxx/CVE-2020-10028.json
2020/10xxx/CVE-2020-10058.json
2020/10xxx/CVE-2020-10059.json
2020/10xxx/CVE-2020-10060.json
2020/10xxx/CVE-2020-10067.json

Updates numerous CVEs that have left embargo on the Zephyr Project.

2020 May Updates for the ZephyrProject

---

2020/11xxx/CVE-2020-11071.json

add CVE-2020-11071 for GHSA-jc83-cpf9-q7c6

add CVE-2020-11071 for GHSA-jc83-cpf9-q7c6

---

2020/11xxx/CVE-2020-11072.json

add CVE-2020-11072 for GHSA-4w97-57v2-3w44

add CVE-2020-11072 for GHSA-4w97-57v2-3w44

---

2019/4xxx/CVE-2019-4478.json
2020/4xxx/CVE-2020-4195.json
2020/4xxx/CVE-2020-4346.json

Added CVE-2019-4478, CVE-2020-4195, and CVE-2020-4346.

Ibm20200512 93650

---

2020/5xxx/CVE-2020-5248.json

add CVE-2020-5248 for GHSA-j222-j9mf-h6j9

add CVE-2020-5248 for GHSA-j222-j9mf-h6j9

---

2020/11xxx/CVE-2020-11062.json

add CVE-2020-11062 for GHSA-3xxh-f5p2-jg3h

add CVE-2020-11062 for GHSA-3xxh-f5p2-jg3h

---

2020/11xxx/CVE-2020-11060.json

add CVE-2020-11060 for GHSA-cvvq-3fww-5v6f

add CVE-2020-11060 for GHSA-cvvq-3fww-5v6f

---

2020/11xxx/CVE-2020-11058.json

add CVE-2020-11058 for GHSA-wjg2-2f82-466g

add CVE-2020-11058 for GHSA-wjg2-2f82-466g

---

2020/11xxx/CVE-2020-11057.json

add CVE-2020-11057 for GHSA-rmp6-jjg8-9424

add CVE-2020-11057 for GHSA-rmp6-jjg8-9424

---

2020/4xxx/CVE-2020-4312.json

Ibm20200513 83045

---

2020/11xxx/CVE-2020-11070.json

Add CVE-2020-11070 for GHSA-59cf-m7v5-wh5w

Add CVE-2020-11070 for GHSA-59cf-m7v5-wh5w

---

2020/11xxx/CVE-2020-11073.json

Add CVE-2020-11073 for GHSA-h8wm-cqq6-957q

Add CVE-2020-11073 for GHSA-h8wm-cqq6-957q

---

2020/11xxx/CVE-2020-11063.json

Add CVE-2020-11063 for GHSA-347x-877p-hcwx

Add CVE-2020-11063 for GHSA-347x-877p-hcwx

---

2020/11xxx/CVE-2020-11064.json

Add CVE-2020-11064 for GHSA-43gj-mj2w-wh46

Add CVE-2020-11064 for GHSA-43gj-mj2w-wh46

---

2020/11xxx/CVE-2020-11066.json

Add CVE-2020-11066 for GHSA-2rxh-h6h9-qrqc

Add CVE-2020-11066 for GHSA-2rxh-h6h9-qrqc

---

2020/11xxx/CVE-2020-11067.json

Add CVE-2020-11067 for GHSA-2wj9-434x-9hvp

Add CVE-2020-11067 for GHSA-2wj9-434x-9hvp

---

2020/11xxx/CVE-2020-11069.json

Add CVE-2020-11069 for GHSA-pqg8-crx9-g8m4

Add CVE-2020-11069 for GHSA-pqg8-crx9-g8m4

---

2020/3xxx/CVE-2020-3810.json

Signed-off-by: Salvatore Bonaccorso <carnil@debian.org>

Add CVE-2020-3810/apt

---

2020/4xxx/CVE-2020-4345.json

Ibm20200517 95628

---

2020/4xxx/CVE-2020-4286.json
2020/4xxx/CVE-2020-4298.json
2020/4xxx/CVE-2020-4411.json
2020/4xxx/CVE-2020-4412.json

Added CVE-2020-4286, CVE-2020-4411, CVE-2020-4412, CVE-2020-4298.

Ibm20200519 91145

---

2020/8xxx/CVE-2020-8616.json
2020/8xxx/CVE-2020-8617.json

[ISC] document BIND9 CVE-2020-8616, CVE-2020-8617

---

2019/5xxx/CVE-2019-5997.json
2020/5xxx/CVE-2020-5579.json

Changed paths:
M 2019/5xxx/CVE-2019-5997.json
M 2020/5xxx/CVE-2020-5579.json

JPCERT/CC CVE-2020-5579, CVE-2019-5997

---

2020/4xxx/CVE-2020-4461.json

Ibm20200520 83229

---

2020/11xxx/CVE-2020-11076.json

add CVE-2020-11076 for GHSA-x7jg-6pwg-fx5h

add CVE-2020-11076 for GHSA-x7jg-6pwg-fx5h

---

2020/11xxx/CVE-2020-11077.json

add CVE-2020-11077 for GHSA-w64w-qqph-5gxm

add CVE-2020-11077 for GHSA-w64w-qqph-5gxm

---

2020/5xxx/CVE-2020-5537.json

Changed paths:
M 2020/5xxx/CVE-2020-5537.json

JPCERT/CC CVE-2020-5537

---

2020/11xxx/CVE-2020-11059.json

Add CVE-2020-11059 for GHSA-qfcv-5whw-7pcw

Add CVE-2020-11059 for GHSA-qfcv-5whw-7pcw

---

2020/11xxx/CVE-2020-11075.json

Add CVE-2020-11075 for GHSA-w4rm-w22x-h7m5

Add CVE-2020-11075 for GHSA-w4rm-w22x-h7m5

---

2020/8xxx/CVE-2020-8603.json
2020/8xxx/CVE-2020-8604.json
2020/8xxx/CVE-2020-8605.json
2020/8xxx/CVE-2020-8606.json

Trend Micro CVE-2020-8603,8604,8065,8066

Trend Micro CVE-2020-8603,8604,8065,8066

---

2020/4xxx/CVE-2020-4231.json
2020/4xxx/CVE-2020-4232.json
2020/4xxx/CVE-2020-4233.json
2020/4xxx/CVE-2020-4244.json
2020/4xxx/CVE-2020-4245.json
2020/4xxx/CVE-2020-4246.json
2020/4xxx/CVE-2020-4249.json
2020/4xxx/CVE-2020-4419.json

Added CVE-2020-4249, CVE-2020-4232, CVE-2020-4244, CVE-2020-4419, CVE-2020-4245, CVE-2020-4231, CVE-2020-4246, and CVE-2020-4233.

Ibm20200528 103829

---

2020/4xxx/CVE-2020-4248.json

Ibm20200528 112041

---

2020/11xxx/CVE-2020-11079.json

Add CVE-2020-11079 for GHSA-wh69-wc6q-7888

Add CVE-2020-11079 for GHSA-wh69-wc6q-7888

---

2020/4xxx/CVE-2020-4306.json
2020/4xxx/CVE-2020-4352.json
2020/4xxx/CVE-2020-4490.json

Added CVE-2020-4306, CVE-2020-4352, and CVE-2020-4490.

Ibm20200529 9643

---

2020/11xxx/CVE-2020-11017.json

Add CVE-2020-11017 for GHSA-q5c8-fm29-q57c

Add CVE-2020-11017 for GHSA-q5c8-fm29-q57c

---

2020/11xxx/CVE-2020-11018.json

Add CVE-2020-11018 for GHSA-8cvc-vcw7-6mfw

Add CVE-2020-11018 for GHSA-8cvc-vcw7-6mfw

---

2020/11xxx/CVE-2020-11038.json

Add CVE-2020-11038 for GHSA-h25x-cqr6-fp6g

Add CVE-2020-11038 for GHSA-h25x-cqr6-fp6g

---

2020/11xxx/CVE-2020-11039.json

Add CVE-2020-11039 for GHSA-mx9p-f6q8-mqwq

Add CVE-2020-11039 for GHSA-mx9p-f6q8-mqwq

---

2020/11xxx/CVE-2020-11041.json

Add CVE-2020-11041 for GHSA-w67c-26c4-2h9w

Add CVE-2020-11041 for GHSA-w67c-26c4-2h9w

---

2020/11xxx/CVE-2020-11040.json

Add CVE-2020-11040 for GHSA-x4wq-m7c9-rjgr

Add CVE-2020-11040 for GHSA-x4wq-m7c9-rjgr

---

2020/11xxx/CVE-2020-11043.json

Add CVE-2020-11043 for GHSA-5mr4-28w3-rc84

Add CVE-2020-11043 for GHSA-5mr4-28w3-rc84

---

2020/11xxx/CVE-2020-11085.json

Add CVE-2020-11085 for GHSA-2j4w-v45m-95hf

Add CVE-2020-11085 for GHSA-2j4w-v45m-95hf

---

2020/11xxx/CVE-2020-11086.json

Add CVE-2020-11086 for GHSA-fg8v-w34r-c974

Add CVE-2020-11086 for GHSA-fg8v-w34r-c974

---

2020/11xxx/CVE-2020-11087.json

Add CVE-2020-11087 for GHSA-84vj-g73m-chw7

Add CVE-2020-11087 for GHSA-84vj-g73m-chw7

---

2020/11xxx/CVE-2020-11088.json

Add CVE-2020-11088 for GHSA-xh4f-fh87-43hp

Add CVE-2020-11088 for GHSA-xh4f-fh87-43hp

---

2020/11xxx/CVE-2020-11089.json

Add CVE-2020-11089 for GHSA-hfc7-c5gv-8c2h

Add CVE-2020-11089 for GHSA-hfc7-c5gv-8c2h

---

2020/10xxx/CVE-2020-10136.json

VU#636397 IP-in-IP

---

2020/4xxx/CVE-2020-4360.json
2020/4xxx/CVE-2020-4366.json
2020/4xxx/CVE-2020-4367.json
2020/4xxx/CVE-2020-4431.json
2020/4xxx/CVE-2020-4503.json

Added CVE-2020-4360, CVE-2020-4366, CVE-2020-4367, CVE-2020-4431, and CVE-2020-4503.

Ibm20200602 9393

---

2020/2xxx/CVE-2020-2190.json
2020/2xxx/CVE-2020-2191.json
2020/2xxx/CVE-2020-2192.json
2020/2xxx/CVE-2020-2193.json
2020/2xxx/CVE-2020-2194.json
2020/2xxx/CVE-2020-2195.json
2020/2xxx/CVE-2020-2196.json
2020/2xxx/CVE-2020-2197.json
2020/2xxx/CVE-2020-2198.json
2020/2xxx/CVE-2020-2199.json
2020/2xxx/CVE-2020-2200.json

https://www.jenkins.io/security/advisory/2020-06-03/

Add CVEs for 2020-06-03 Jenkins security advisory

---

2020/4xxx/CVE-2020-4035.json

add CVE-2020-4035 for GHSA-38f9-m297-6q9g
❗ Note: This is our first submission using the CVE-2020-4030-CVE-2020-4099 block we were assigned.

add CVE-2020-4035 for GHSA-38f9-m297-6q9g

---

2020/5xxx/CVE-2020-5295.json

add CVE-2020-5295 for GHSA-r23f-c2j5-rx2f

add CVE-2020-5295 for GHSA-r23f-c2j5-rx2f

---

2020/5xxx/CVE-2020-5298.json

add CVE-2020-5298 for GHSA-gg6x-xx78-448c

add CVE-2020-5298 for GHSA-gg6x-xx78-448c

---

2020/5xxx/CVE-2020-5297.json

add CVE-2020-5297 for GHSA-9722-rr68-rfpg

add CVE-2020-5297 for GHSA-9722-rr68-rfpg

---

2020/5xxx/CVE-2020-5296.json

add CVE-2020-5296 for GHSA-jv6v-fvvx-4932

add CVE-2020-5296 for GHSA-jv6v-fvvx-4932

---

2020/5xxx/CVE-2020-5299.json

add CVE-2020-5299 for GHSA-4rhm-m2fp-hx7q

add CVE-2020-5299 for GHSA-4rhm-m2fp-hx7q

---

2020/11xxx/CVE-2020-11080.json

add CVE-2020-11080 for GHSA-q5wr-xfw9-q7xr

add CVE-2020-11080 for GHSA-q5wr-xfw9-q7xr

---

2020/11xxx/CVE-2020-11091.json

add CVE-2020-11091 for GHSA-59qg-grp7-5r73

add CVE-2020-11091 for GHSA-59qg-grp7-5r73

---

2020/11xxx/CVE-2020-11094.json

add CVE-2020-11094 for GHSA-c8wh-6jw4-2h79

add CVE-2020-11094 for GHSA-c8wh-6jw4-2h79

---

2020/4xxx/CVE-2020-4229.json
2020/4xxx/CVE-2020-4448.json
2020/4xxx/CVE-2020-4449.json
2020/4xxx/CVE-2020-4450.json

Added CVE-2020-4229, CVE-2020-4448, CVE-2020-4450, and CVE-2020-4449.

Ibm20200605 85241

---

2020/10xxx/CVE-2020-10019.json
2020/10xxx/CVE-2020-10021.json
2020/10xxx/CVE-2020-10022.json
2020/10xxx/CVE-2020-10023.json
2020/10xxx/CVE-2020-10024.json
2020/10xxx/CVE-2020-10027.json
2020/10xxx/CVE-2020-10028.json
2020/10xxx/CVE-2020-10058.json
2020/10xxx/CVE-2020-10059.json
2020/10xxx/CVE-2020-10060.json
2020/10xxx/CVE-2020-10061.json
2020/10xxx/CVE-2020-10062.json
2020/10xxx/CVE-2020-10063.json
2020/10xxx/CVE-2020-10067.json
2020/10xxx/CVE-2020-10068.json
2020/10xxx/CVE-2020-10070.json
2020/10xxx/CVE-2020-10071.json

CVE updates for Zephyr project for issues newly leaving embargo.

Update 2020 05 26

---

2020/4xxx/CVE-2020-4529.json

Ibm20200608 85339

---

2020/1xxx/CVE-2020-1775.json

added OSA-2020-12 (CVE-2020-1775)

OTRS Security Announcement 2020-06-08

---

2020/4xxx/CVE-2020-4038.json

add CVE-2020-4038 for GHSA-4852-vrh7-28rf

add CVE-2020-4038 for GHSA-4852-vrh7-28rf

---

2020/4xxx/CVE-2020-4041.json

add CVE-2020-4041 for GHSA-68q3-7wjp-7q3j

add CVE-2020-4041 for GHSA-68q3-7wjp-7q3j

---

2019/6xxx/CVE-2019-6173.json
2019/6xxx/CVE-2019-6196.json
2020/8xxx/CVE-2020-8320.json
2020/8xxx/CVE-2020-8321.json
2020/8xxx/CVE-2020-8322.json
2020/8xxx/CVE-2020-8323.json
2020/8xxx/CVE-2020-8331.json
2020/8xxx/CVE-2020-8334.json
2020/8xxx/CVE-2020-8336.json
2020/8xxx/CVE-2020-8337.json

Population of CVEs for June advisories.

June Advisories

---

2019/3xxx/CVE-2019-3617.json

TS already live

---

2019/3xxx/CVE-2019-3613.json

Publish CVE-2019-3613

---

2020/7xxx/CVE-2020-7279.json

Publish CVE-2020-7279

---

2019/3xxx/CVE-2019-3585.json

Publish CVE-2019-3585

---

2019/3xxx/CVE-2019-3588.json

CVE-2019-3588

---

2020/7xxx/CVE-2020-7280.json

Publish CVE-2020-7280

---

2020/11xxx/CVE-2020-11090.json

add CVE-2020-11090 for GHSA-3gw4-m5w7-v89c

add CVE-2020-11090 for GHSA-3gw4-m5w7-v89c

---

2020/4xxx/CVE-2020-4380.json

Ibm20200611 893

---

2020/4xxx/CVE-2020-4045.json

add CVE-2020-4045 for GHSA-mpgr-2cx9-327h

add CVE-2020-4045 for GHSA-mpgr-2cx9-327h

---

2020/4xxx/CVE-2020-4251.json

Ibm20200612 9844

---

2020/4xxx/CVE-2020-4046.json

add CVE-2020-4046 for GHSA-rpwf-hrh2-39jf

add CVE-2020-4046 for GHSA-rpwf-hrh2-39jf

---

2020/4xxx/CVE-2020-4050.json

add CVE-2020-4050 for GHSA-4vpv-fgg2-gcqc

add CVE-2020-4050 for GHSA-4vpv-fgg2-gcqc

---

2020/4xxx/CVE-2020-4049.json

add CVE-2020-4049 for GHSA-87h4-phjv-rm6p

add CVE-2020-4049 for GHSA-87h4-phjv-rm6p

---

2020/4xxx/CVE-2020-4048.json

add CVE-2020-4048 for GHSA-q6pw-gvf4-5fj5

add CVE-2020-4048 for GHSA-q6pw-gvf4-5fj5

---

2020/4xxx/CVE-2020-4047.json

add CVE-2020-4047 for GHSA-8q2w-5m27-wm27

add CVE-2020-4047 for GHSA-8q2w-5m27-wm27

---

2020/4xxx/CVE-2020-4216.json
2020/4xxx/CVE-2020-4406.json
2020/4xxx/CVE-2020-4469.json
2020/4xxx/CVE-2020-4470.json
2020/4xxx/CVE-2020-4471.json
2020/4xxx/CVE-2020-4477.json
2020/4xxx/CVE-2020-4494.json

Added CVE-2020-4216, CVE-2020-4406, CVE-2020-4469, CVE-2020-4470, CVE-2020-4471, CVE-2020-4477, and CVE-2020-4494.

Ibm20200615 92122

---

2020/4xxx/CVE-2020-4051.json

Add CVE-2020-4051 for GHSA-cxjc-r2fp-7mq6

Add CVE-2020-4051 for GHSA-cxjc-r2fp-7mq6

---

2020/12xxx/CVE-2020-12494.json

initial CVE-2020-12493 entry

---

2020/4xxx/CVE-2020-4310.json
2020/4xxx/CVE-2020-4320.json

Added CVE-2020-4310 and CVE-2020-4320.

Ibm20200616 94329

---

2020/4xxx/CVE-2020-4052.json

add CVE-2020-4052 for GHSA-9jgg-4xj2-vjjj

add CVE-2020-4052 for GHSA-9jgg-4xj2-vjjj

---

2020/4xxx/CVE-2020-4053.json

add CVE-2020-4053 for GHSA-qq3j-xp49-j73f

add CVE-2020-4053 for GHSA-qq3j-xp49-j73f

---

2020/4xxx/CVE-2020-4054.json

add CVE-2020-4054 for GHSA-p4x4-rw2p-8j8m

add CVE-2020-4054 for GHSA-p4x4-rw2p-8j8m

---

2020/4xxx/CVE-2020-4532.json

Ibm20200617 133911

---

2020/4xxx/CVE-2020-4059.json

add CVE-2020-4059 for GHSA-qjg4-w4c6-f6c6

add CVE-2020-4059 for GHSA-qjg4-w4c6-f6c6

---

2020/4xxx/CVE-2020-4281.json
2020/4xxx/CVE-2020-4295.json
2020/4xxx/CVE-2020-4297.json

Added CVE-2020-4281, CVE-2020-4295, and CVE-2020-4297.

Ibm20200619 12415

---

2020/7xxx/CVE-2020-7262.json

Publish CVE-2020-7262

---

2020/4xxx/CVE-2020-4062.json

add CVE-2020-4062 for GHSA-mg2m-623j-wpxw

add CVE-2020-4062 for GHSA-mg2m-623j-wpxw

---

2020/4xxx/CVE-2020-4066.json

add CVE-2020-4066 for GHSA-77qv-gh6f-pgh4

add CVE-2020-4066 for GHSA-77qv-gh6f-pgh4

---

2020/4xxx/CVE-2020-4068.json

add CVE-2020-4068 for GHSA-qh2w-vjxg-mjcg

add CVE-2020-4068 for GHSA-qh2w-vjxg-mjcg

---

2020/4xxx/CVE-2020-4070.json

add CVE-2020-4070 for GHSA-wf36-7w73-rh8c

add CVE-2020-4070 for GHSA-wf36-7w73-rh8c

---

2020/4xxx/CVE-2020-4060.json

add CVE-2020-4060 for GHSA-v9ph-r496-4m2j

add CVE-2020-4060 for GHSA-v9ph-r496-4m2j

---

2020/8xxx/CVE-2020-8619.json

This is a trial of richer version information, as requested by @iamleot.  I'd like to confirm that this is what you're  looking for before I update additional issues.

[ISC] Richer version information for CVE-2020-8619

---

2020/11xxx/CVE-2020-11098.json

add CVE-2020-11098 for GHSA-jr57-f58x-hjmv

add CVE-2020-11098 for GHSA-jr57-f58x-hjmv

---

2020/11xxx/CVE-2020-11097.json

add CVE-2020-11097 for GHSA-c8x2-c3c9-9r3f

add CVE-2020-11097 for GHSA-c8x2-c3c9-9r3f

---

2020/11xxx/CVE-2020-11096.json

add CVE-2020-11096 for GHSA-mjw7-3mq2-996x

add CVE-2020-11096 for GHSA-mjw7-3mq2-996x

---

2020/11xxx/CVE-2020-11095.json

add CVE-2020-11095 for GHSA-563r-pvh7-4fw2

add CVE-2020-11095 for GHSA-563r-pvh7-4fw2

---

2020/4xxx/CVE-2020-4033.json

add CVE-2020-4033 for GHSA-7rhj-856w-82p8

add CVE-2020-4033 for GHSA-7rhj-856w-82p8

---

2020/4xxx/CVE-2020-4032.json

add CVE-2020-4032 for GHSA-3898-mc89-x2vc

add CVE-2020-4032 for GHSA-3898-mc89-x2vc

---

2020/4xxx/CVE-2020-4031.json

add CVE-2020-4031 for GHSA-gwcq-hpq2-m74g

add CVE-2020-4031 for GHSA-gwcq-hpq2-m74g

---

2020/4xxx/CVE-2020-4030.json

add CVE-2020-4030 for GHSA-fjr5-97f5-qq98

add CVE-2020-4030 for GHSA-fjr5-97f5-qq98

---

2020/5xxx/CVE-2020-5594.json

Changed paths:
M 2020/5xxx/CVE-2020-5594.json

JPCERT/CC CVE-2020-5594

---

2020/4xxx/CVE-2020-4026.json
2020/4xxx/CVE-2020-4028.json

CVE-2020-4026 , CVE-2020-4028 (sync with external)

Sync with external cvelist

---

2020/11xxx/CVE-2020-11068.json

add CVE-2020-11068 for GHSA-559p-6xgm-fpv9

add CVE-2020-11068 for GHSA-559p-6xgm-fpv9

---

2020/4xxx/CVE-2020-4071.json

add CVE-2020-4071 for GHSA-m38j-pmg3-v5x5

add CVE-2020-4071 for GHSA-m38j-pmg3-v5x5

---

2020/4xxx/CVE-2020-4322.json
2020/4xxx/CVE-2020-4323.json
2020/4xxx/CVE-2020-4327.json
2020/4xxx/CVE-2020-4341.json
2020/4xxx/CVE-2020-4342.json
2020/4xxx/CVE-2020-4413.json

Added CVE-2020-4322, CVE-2020-4323, CVE-2020-4327, CVE-2020-4341, CVE-2020-4342, and CVE-2020-4413.

Ibm20200624 1069

---

2020/5xxx/CVE-2020-5963.json
2020/5xxx/CVE-2020-5964.json
2020/5xxx/CVE-2020-5965.json

NVIDIA CVE

---

2020/4xxx/CVE-2020-4072.json

add CVE-2020-4072 for GHSA-pfxf-wh96-fvjc

add CVE-2020-4072 for GHSA-pfxf-wh96-fvjc

---

2020/5xxx/CVE-2020-5966.json
2020/5xxx/CVE-2020-5967.json

NVIDIA GPU Driver CVE-2020-5966, CVE-2020-5967

---

2019/4xxx/CVE-2019-4650.json
2020/4xxx/CVE-2020-4223.json
2020/4xxx/CVE-2020-4565.json

Added CVE-2019-4650, CVE-2020-4223, and CVE-2020-4565.

Ibm20200626 93932

---

2020/4xxx/CVE-2020-4452.json

Ibm20200629 92853

---

2020/4xxx/CVE-2020-4557.json

Ibm20200629 95529

---

2020/4xxx/CVE-2020-4037.json

add CVE-2020-4037 for GHSA-5m6c-jp6f-2vcv

add CVE-2020-4037 for GHSA-5m6c-jp6f-2vcv

---

2020/4xxx/CVE-2020-4067.json

add CVE-2020-4067 for GHSA-c8r8-8vp5-6gcm

add CVE-2020-4067 for GHSA-c8r8-8vp5-6gcm

---

2020/4xxx/CVE-2020-4044.json

add CVE-2020-4044 for GHSA-j9fv-6fwf-p3g4

add CVE-2020-4044 for GHSA-j9fv-6fwf-p3g4

---

2020/15xxx/CVE-2020-15084.json

add CVE-2020-15084 for GHSA-6g6m-m6h5-w9gf

add CVE-2020-15084 for GHSA-6g6m-m6h5-w9gf

---

2020/15xxx/CVE-2020-15085.json

add CVE-2020-15085 for GHSA-4279-h39w-2jqm

add CVE-2020-15085 for GHSA-4279-h39w-2jqm

---

2020/5xxx/CVE-2020-5968.json
2020/5xxx/CVE-2020-5969.json
2020/5xxx/CVE-2020-5970.json
2020/5xxx/CVE-2020-5971.json
2020/5xxx/CVE-2020-5972.json
2020/5xxx/CVE-2020-5973.json

NVIDIA vGPU CVEs June 2020

---

2020/12xxx/CVE-2020-12497.json
2020/12xxx/CVE-2020-12498.json

Add two CVEs

---

2020/5xxx/CVE-2020-5238.json

add CVE-2020-5238 for GHSA-7gc6-9qr5-hc85

add CVE-2020-5238 for GHSA-7gc6-9qr5-hc85

---

2020/15xxx/CVE-2020-15087.json

per request from maintainer, this reference is not a complete fix for the issue and is causing some confusion

remove pull request reference from CVE-2020-15087

---

2020/2xxx/CVE-2020-2201.json
2020/2xxx/CVE-2020-2202.json
2020/2xxx/CVE-2020-2203.json
2020/2xxx/CVE-2020-2204.json
2020/2xxx/CVE-2020-2205.json
2020/2xxx/CVE-2020-2206.json
2020/2xxx/CVE-2020-2207.json
2020/2xxx/CVE-2020-2208.json
2020/2xxx/CVE-2020-2209.json
2020/2xxx/CVE-2020-2210.json
2020/2xxx/CVE-2020-2211.json
2020/2xxx/CVE-2020-2212.json
2020/2xxx/CVE-2020-2213.json
2020/2xxx/CVE-2020-2214.json
2020/2xxx/CVE-2020-2215.json
2020/2xxx/CVE-2020-2216.json
2020/2xxx/CVE-2020-2217.json
2020/2xxx/CVE-2020-2218.json
2020/2xxx/CVE-2020-2219.json

https://www.jenkins.io/security/advisory/2020-07-02/

Add CVEs for Jenkins 2020-07-02 security advisory

---

2020/15xxx/CVE-2020-15081.json

add CVE-2020-15081 for GHSA-997j-f42g-x57c

add CVE-2020-15081 for GHSA-997j-f42g-x57c

---

2020/15xxx/CVE-2020-15080.json

add CVE-2020-15080 for GHSA-492w-2pp5-xhvg

add CVE-2020-15080 for GHSA-492w-2pp5-xhvg

---

2020/11xxx/CVE-2020-11074.json

add CVE-2020-11074 for GHSA-v4pg-q2cv-f7x4

add CVE-2020-11074 for GHSA-v4pg-q2cv-f7x4

---

2020/15xxx/CVE-2020-15083.json

add CVE-2020-15083 for GHSA-qgh4-95j7-p3vj

add CVE-2020-15083 for GHSA-qgh4-95j7-p3vj

---

2020/15xxx/CVE-2020-15082.json

add CVE-2020-15082 for GHSA-mc98-xjm3-c4fm

add CVE-2020-15082 for GHSA-mc98-xjm3-c4fm

---

2020/4xxx/CVE-2020-4061.json

add CVE-2020-4061 for GHSA-3pc2-fm7p-q2vg

add CVE-2020-4061 for GHSA-3pc2-fm7p-q2vg

---

2020/15xxx/CVE-2020-15091.json

add CVE-2020-15091 for GHSA-6jqj-f58p-mrw3

add CVE-2020-15091 for GHSA-6jqj-f58p-mrw3

---

2020/4xxx/CVE-2020-4074.json

add CVE-2020-4074 for GHSA-ccvh-jh5x-mpg4

add CVE-2020-4074 for GHSA-ccvh-jh5x-mpg4

---

2020/4xxx/CVE-2020-4077.json

add CVE-2020-4077 for GHSA-h9jc-284h-533g

add CVE-2020-4077 for GHSA-h9jc-284h-533g

---

2020/4xxx/CVE-2020-4076.json

add CVE-2020-4076 for GHSA-m93v-9qjc-3g79

add CVE-2020-4076 for GHSA-m93v-9qjc-3g79

---

2020/4xxx/CVE-2020-4075.json

add CVE-2020-4075 for GHSA-f9mq-jph6-9mhm

add CVE-2020-4075 for GHSA-f9mq-jph6-9mhm

---

2020/15xxx/CVE-2020-15096.json

add CVE-2020-15096 for GHSA-6vrv-94jv-crrg

add CVE-2020-15096 for GHSA-6vrv-94jv-crrg

---

2020/15xxx/CVE-2020-15095.json

Add CVE-2020-15095 for GHSA-93f3-23rq-pjfp

Add CVE-2020-15095 for GHSA-93f3-23rq-pjfp

---

2020/1xxx/CVE-2020-1982.json
2020/2xxx/CVE-2020-2030.json
2020/2xxx/CVE-2020-2031.json
2020/2xxx/CVE-2020-2034.json

CVEs assigned in Palo Alto Networks Security Advisories for July 2020 Patch Wednesday.

CVEs assigned in Palo Alto Networks Security Advisories for July 2020

---

2020/5xxx/CVE-2020-5974.json

CVE-2020-5974.json

---

2020/5xxx/CVE-2020-5604.json

Changed paths:
M 2020/5xxx/CVE-2020-5604.json

JPCERT/CC CVE-2020-5604

---

2019/17xxx/CVE-2019-17638.json

CVE-2019-17638

---

2020/15xxx/CVE-2020-15092.json

add CVE-2020-15092 for GHSA-2jpm-827p-j44g

add CVE-2020-15092 for GHSA-2jpm-827p-j44g

---

2020/15xxx/CVE-2020-15093.json

add CVE-2020-15093 for GHSA-5q2r-92f9-4m49

add CVE-2020-15093 for GHSA-5q2r-92f9-4m49

---

2020/5xxx/CVE-2020-5607.json

Changed paths:
M 2020/5xxx/CVE-2020-5607.json

JPCERT/CC CVE-2020-5607

---

2020/11xxx/CVE-2020-11081.json

add CVE-2020-11081 for GHSA-2xwp-8fv7-c5pm

add CVE-2020-11081 for GHSA-2xwp-8fv7-c5pm

---

2020/11xxx/CVE-2020-11061.json

add CVE-2020-11061 for GHSA-mm45-cg35-54j4

add CVE-2020-11061 for GHSA-mm45-cg35-54j4

---

2020/4xxx/CVE-2020-4042.json

add CVE-2020-4042 for GHSA-vqpj-2vhj-h752

add CVE-2020-4042 for GHSA-vqpj-2vhj-h752

---

2020/15xxx/CVE-2020-15105.json

add CVE-2020-15105 for GHSA-vhr6-pvjm-9qwf

add CVE-2020-15105 for GHSA-vhr6-pvjm-9qwf

---

2020/4xxx/CVE-2020-4364.json
2020/4xxx/CVE-2020-4510.json
2020/4xxx/CVE-2020-4511.json
2020/4xxx/CVE-2020-4512.json
2020/4xxx/CVE-2020-4513.json

Added CVE-2020-4513, CVE-2020-4510, CVE-2020-4511, CVE-2020-4364, and CVE-2020-4512.

Ibm20200714 9533

---

2020/15xxx/CVE-2020-15100.json

Add CVE-2020-15100 for GHSA-9cfv-9463-8gqv

Add CVE-2020-15100 for GHSA-9cfv-9463-8gqv

---

2020/5xxx/CVE-2020-5246.json

add CVE-2020-5246 for GHSA-v955-7g22-2p49

add CVE-2020-5246 for GHSA-v955-7g22-2p49

---

2020/11xxx/CVE-2020-11083.json

add CVE-2020-11083 for GHSA-w4pj-7p68-3vgv

add CVE-2020-11083 for GHSA-w4pj-7p68-3vgv

---

2020/11xxx/CVE-2020-11084.json

add CVE-2020-11084 for GHSA-4xvp-35fx-hjjj

add CVE-2020-11084 for GHSA-4xvp-35fx-hjjj

---

2020/15xxx/CVE-2020-15101.json

add CVE-2020-15101 for GHSA-7pmh-vrww-25xx

add CVE-2020-15101 for GHSA-7pmh-vrww-25xx

---

2020/15xxx/CVE-2020-15104.json

add CVE-2020-15104 for GHSA-w5f5-6qhq-hhrg

add CVE-2020-15104 for GHSA-w5f5-6qhq-hhrg

---

2020/14xxx/CVE-2020-14172.json

-- as we found it didn't affect the 8.5.x versions.

Updating the affected version ranges on CVE-2020-14172

---

2019/17xxx/CVE-2019-17637.json

CVE-2019-17637

---

2020/2xxx/CVE-2020-2220.json
2020/2xxx/CVE-2020-2221.json
2020/2xxx/CVE-2020-2222.json
2020/2xxx/CVE-2020-2223.json
2020/2xxx/CVE-2020-2224.json
2020/2xxx/CVE-2020-2225.json
2020/2xxx/CVE-2020-2226.json
2020/2xxx/CVE-2020-2227.json
2020/2xxx/CVE-2020-2228.json

https://www.jenkins.io/security/advisory/2020-07-15/

Add CVEs for Jenkins 2020-07-15 security advisory

---

2020/15xxx/CVE-2020-15117.json

Add CVE-2020-15117 for GHSA-chfm-333q-gfpp

Add CVE-2020-15117 for GHSA-chfm-333q-gfpp

---

2020/15xxx/CVE-2020-15602.json
2020/15xxx/CVE-2020-15603.json

CVE-2020-15602 and CVE-2020-15603

CVE-2020-15602 and CVE-2020-15603

---

2020/15xxx/CVE-2020-15107.json

Add CVE-2020-15107 for GHSA-7wjx-wcwg-w999

Add CVE-2020-15107 for GHSA-7wjx-wcwg-w999

---

2020/10xxx/CVE-2020-10288.json

Similar to https://github.com/CVEProject/cvelist/pull/4320, this ticket reflects the results of our research and interactions with ABB's security team. Flaw was confirmed.

Assign CVE-2020-10288

---

2020/10xxx/CVE-2020-10287.json

This issue was first discussed with ABB and after interactions, we indicated our intention of filing the ticket which they did not reject. Here it is correspondingly.

Assign CVE-2020-10287

---

2020/5xxx/CVE-2020-5130.json
2020/5xxx/CVE-2020-5131.json

SSLVPN LDAP login external interaction vulnerability 
SonicWall NetExtender Windows client arbitrary file write vulnerability

CVE-2020-5130 and CVE-2020-5131

---

2020/1xxx/CVE-2020-1640.json
2020/1xxx/CVE-2020-1641.json
2020/1xxx/CVE-2020-1643.json
2020/1xxx/CVE-2020-1644.json
2020/1xxx/CVE-2020-1645.json
2020/1xxx/CVE-2020-1646.json
2020/1xxx/CVE-2020-1647.json
2020/1xxx/CVE-2020-1648.json
2020/1xxx/CVE-2020-1649.json
2020/1xxx/CVE-2020-1650.json
2020/1xxx/CVE-2020-1651.json
2020/1xxx/CVE-2020-1652.json
2020/1xxx/CVE-2020-1653.json
2020/1xxx/CVE-2020-1654.json
2020/1xxx/CVE-2020-1655.json

For Juniper 2020-07-08 CVE Publication.

juniper 2020-07-08

---

2020/15xxx/CVE-2020-15108.json

Add CVE-2020-15108 for GHSA-qv6w-68gq-wx2v

Add CVE-2020-15108 for GHSA-qv6w-68gq-wx2v

---

2020/15xxx/CVE-2020-15110.json

Add CVE-2020-15110 for GHSA-v7m9-9497-p9gr

Add CVE-2020-15110 for GHSA-v7m9-9497-p9gr

---

2020/4xxx/CVE-2020-4361.json
2020/4xxx/CVE-2020-4466.json
2020/4xxx/CVE-2020-4527.json

Added CVE-2020-4466, CVE-2020-4361, and CVE-2020-4527.

Ibm20200720 10039

---

2020/15xxx/CVE-2020-15123.json

add CVE-2020-15123 for GHSA-xp63-6vf5-xf3v

add CVE-2020-15123 for GHSA-xp63-6vf5-xf3v

---

2020/15xxx/CVE-2020-15111.json

add CVE-2020-15111 for GHSA-9cx9-x2gp-9qvh

add CVE-2020-15111 for GHSA-9cx9-x2gp-9qvh

---

2020/15xxx/CVE-2020-15118.json

add CVE-2020-15118 for GHSA-2473-9hgq-j7xw

add CVE-2020-15118 for GHSA-2473-9hgq-j7xw

---

2020/15xxx/CVE-2020-15121.json

add CVE-2020-15121 for GHSA-r552-vp94-9358

add CVE-2020-15121 for GHSA-r552-vp94-9358

---

2020/1xxx/CVE-2020-1776.json

OSA-2020-13

---

2019/20xxx/CVE-2019-20417.json

This PR supersedes https://github.com/CVEProject/cvelist/pull/4238 .

Registering an accidentally-duplicated issue.

---

2020/15xxx/CVE-2020-15102.json

add CVE-2020-15102 for GHSA-6292-4qpg-hvfg

add CVE-2020-15102 for GHSA-6292-4qpg-hvfg

---

2020/15xxx/CVE-2020-15124.json

add CVE-2020-15124 for GHSA-7gwq-xqw3-cr63

add CVE-2020-15124 for GHSA-7gwq-xqw3-cr63

---

2014/1xxx/CVE-2014-1422.json

Hello, this is CVE-2014-1422 from Ubuntu
Thank you

trust-store (Ubuntu) vulnerability

---

2020/3xxx/CVE-2020-3452.json

A vulnerability in the web services interface of Cisco Adaptive Security Appliance (ASA) Software and Cisco Firepower Threat Defense (FTD) Software could allow an unauthenticated, remote attacker to conduct directory traversal attacks and read sensitive files on a targeted system.
The vulnerability is due to a lack of proper input validation of URLs in HTTP requests processed by an affected device. An attacker could exploit this vulnerability by sending a crafted HTTP request containing directory traversal character sequences to an affected device. A successful exploit could allow the attacker to view arbitrary files within the web services file system on the targeted device.
The web services file system is enabled when the affected device is configured with either WebVPN or AnyConnect …

Adding Cisco CVE-2020-3452

---

2020/4xxx/CVE-2020-4369.json
2020/4xxx/CVE-2020-4371.json
2020/4xxx/CVE-2020-4372.json
2020/4xxx/CVE-2020-4385.json
2020/4xxx/CVE-2020-4397.json
2020/4xxx/CVE-2020-4399.json
2020/4xxx/CVE-2020-4400.json

Added CVE-2020-4397, CVE-2020-4371, CVE-2020-4369, CVE-2020-4400, CVE-2020-4399, CVE-2020-4372, and CVE-2020-4385.

Ibm20200722 162355

---

2020/15xxx/CVE-2020-15126.json

add CVE-2020-15126 for GHSA-236h-rqv8-8q73

add CVE-2020-15126 for GHSA-236h-rqv8-8q73

---

2020/4xxx/CVE-2020-4447.json

Ibm20200723 12219

---

2020/8xxx/CVE-2020-8317.json
2020/8xxx/CVE-2020-8326.json

July CVE submission

---

2020/4xxx/CVE-2020-4405.json
2020/4xxx/CVE-2020-4408.json
2020/4xxx/CVE-2020-4498.json

Added CVE-2020-4498, CVE-2020-4405, and CVE-2020-4408.

Ibm20200727 9272

---

2020/15xxx/CVE-2020-15103.json

add CVE-2020-15103 for GHSA-4r38-6hq7-j3j9

add CVE-2020-15103 for GHSA-4r38-6hq7-j3j9

---

2020/15xxx/CVE-2020-15120.json

add CVE-2020-15120 for GHSA-67j9-c52g-w2q9

add CVE-2020-15120 for GHSA-67j9-c52g-w2q9

---

2019/4xxx/CVE-2019-4731.json
2020/4xxx/CVE-2020-4317.json
2020/4xxx/CVE-2020-4318.json
2020/4xxx/CVE-2020-4319.json
2020/4xxx/CVE-2020-4375.json
2020/4xxx/CVE-2020-4465.json

Added CVE-2020-4465, CVE-2020-4375, CVE-2020-4317, CVE-2020-4318, CVE-2019-4731, and CVE-2020-4319.

Ibm20200728 75955

---

2020/15xxx/CVE-2020-15418.json
2020/15xxx/CVE-2020-15419.json

M  2020/15xxx/CVE-2020-15418.json
M  2020/15xxx/CVE-2020-15419.json

Correcting CNA mapping issue

---

2020/4xxx/CVE-2020-4463.json
2020/4xxx/CVE-2020-4567.json
2020/4xxx/CVE-2020-4569.json
2020/4xxx/CVE-2020-4572.json
2020/4xxx/CVE-2020-4573.json
2020/4xxx/CVE-2020-4574.json
2020/4xxx/CVE-2020-4644.json
2020/4xxx/CVE-2020-4645.json

Added CVE-2020-4569, CVE-2020-4644, CVE-2020-4573, CVE-2020-4463, CVE-2020-4567, CVE-2020-4574, CVE-2020-4645, and CVE-2020-4572.

Ibm20200729 10141

---

2020/15xxx/CVE-2020-15099.json

add CVE-2020-15099 for GHSA-3x94-fv5h-5q2c

add CVE-2020-15099 for GHSA-3x94-fv5h-5q2c

---

2020/11xxx/CVE-2020-11933.json
2020/11xxx/CVE-2020-11934.json

Hello,
These are CVEs CVE-2020-11933 and CVE-2020-11934 from Ubuntu.
Thank you

snapd and core vuln details

---

2020/15xxx/CVE-2020-15098.json

add CVE-2020-15098 for GHSA-m5vr-3m74-jwxp

add CVE-2020-15098 for GHSA-m5vr-3m74-jwxp

---

2020/15xxx/CVE-2020-15086.json

add CVE-2020-15086 for GHSA-4h44-w6fm-548g

add CVE-2020-15086 for GHSA-4h44-w6fm-548g

---

2020/15xxx/CVE-2020-15125.json

add CVE-2020-15125 for GHSA-5jpf-pj32-xx53

add CVE-2020-15125 for GHSA-5jpf-pj32-xx53

---

2020/15xxx/CVE-2020-15705.json
2020/15xxx/CVE-2020-15706.json
2020/15xxx/CVE-2020-15707.json

Hello,
These are CVEs CVE-2020-15705, CVE-2020-15706 and CVE-2020-15707 from Ubuntu.
Thank you

GRUB2 vulnerability details

---

2020/4xxx/CVE-2020-4185.json
2020/4xxx/CVE-2020-4186.json

Added CVE-2020-4185 and CVE-2020-4186.

Ibm20200730 84941

---

2020/15xxx/CVE-2020-15131.json

add CVE-2020-15131 for GHSA-6jmr-jfh7-xg3h

add CVE-2020-15131 for GHSA-6jmr-jfh7-xg3h

---

2020/15xxx/CVE-2020-15130.json

add CVE-2020-15130 for GHSA-cc2p-4jhr-xhhx

add CVE-2020-15130 for GHSA-cc2p-4jhr-xhhx

---

2020/15xxx/CVE-2020-15129.json

add CVE-2020-15129 for GHSA-6qq8-5wq3-86rp

add CVE-2020-15129 for GHSA-6qq8-5wq3-86rp

---

2020/15xxx/CVE-2020-15134.json

add CVE-2020-15134 for GHSA-3q49-h8f9-9fr9

add CVE-2020-15134 for GHSA-3q49-h8f9-9fr9

---

2020/15xxx/CVE-2020-15133.json

add CVE-2020-15133 for GHSA-2v5c-755p-p4gv

add CVE-2020-15133 for GHSA-2v5c-755p-p4gv

---

2020/15xxx/CVE-2020-15128.json

add CVE-2020-15128 for GHSA-55mm-5399-7r63

add CVE-2020-15128 for GHSA-55mm-5399-7r63

---

2019/4xxx/CVE-2019-4366.json
2019/4xxx/CVE-2019-4589.json
2020/4xxx/CVE-2020-4328.json
2020/4xxx/CVE-2020-4377.json
2020/4xxx/CVE-2020-4534.json
2020/4xxx/CVE-2020-4549.json
2020/4xxx/CVE-2020-4550.json
2020/4xxx/CVE-2020-4551.json
2020/4xxx/CVE-2020-4552.json
2020/4xxx/CVE-2020-4553.json
2020/4xxx/CVE-2020-4554.json
2020/4xxx/CVE-2020-4560.json

Added CVE-2020-4553, CVE-2020-4554, CVE-2020-4550, CVE-2020-4560, CVE-2020-4534, CVE-2019-4589, CVE-2020-4549, CVE-2020-4551, CVE-2019-4366, CVE-2020-4552, CVE-2020-4328, and CVE-2020-4377.

Ibm20200803 82947

---

2020/4xxx/CVE-2020-4396.json
2020/4xxx/CVE-2020-4410.json
2020/4xxx/CVE-2020-4459.json
2020/4xxx/CVE-2020-4525.json
2020/4xxx/CVE-2020-4542.json
2020/4xxx/CVE-2020-4631.json

Added CVE-2020-4396, CVE-2020-4542, CVE-2020-4410, CVE-2020-4459, CVE-2020-4525, and CVE-2020-4631.

Ibm20200804 11595

---

2020/15xxx/CVE-2020-15135.json

Add CVE-2020-15135 for GHSA-wwrj-35w6-77ff

Add CVE-2020-15135 for GHSA-wwrj-35w6-77ff

---

2020/15xxx/CVE-2020-15109.json

Add CVE-2020-15109 for GHSA-3mvg-rrrw-m7ph

Add CVE-2020-15109 for GHSA-3mvg-rrrw-m7ph

---

2020/8xxx/CVE-2020-8607.json

Trend Micro CVE-2020-8607

---

2020/15xxx/CVE-2020-15106.json

Add CVE-2020-15106 for GHSA-p4g4-wgrh-qrg2

Add CVE-2020-15106 for GHSA-p4g4-wgrh-qrg2

---

2020/15xxx/CVE-2020-15113.json

Add CVE-2020-15113 for GHSA-chh6-ppwq-jh92

Add CVE-2020-15113 for GHSA-chh6-ppwq-jh92

---

2020/15xxx/CVE-2020-15112.json

Add CVE-2020-15112 for GHSA-m332-53r6-2w93

Add CVE-2020-15112 for GHSA-m332-53r6-2w93

---

2020/15xxx/CVE-2020-15127.json

Add CVE-2020-15127 for GHSA-mjp8-x484-pm3r

Add CVE-2020-15127 for GHSA-mjp8-x484-pm3r

---

2020/15xxx/CVE-2020-15132.json

Add CVE-2020-15132 for GHSA-wfm4-pq59-wg6r

Add CVE-2020-15132 for GHSA-wfm4-pq59-wg6r

---

2020/15xxx/CVE-2020-15115.json

Add CVE-2020-15115 for GHSA-4993-m7g5-r9hh

Add CVE-2020-15115 for GHSA-4993-m7g5-r9hh

---

2020/15xxx/CVE-2020-15114.json

Add CVE-2020-15114 for GHSA-2xhq-gv6c-p224

Add CVE-2020-15114 for GHSA-2xhq-gv6c-p224

---

2020/11xxx/CVE-2020-11937.json
2020/15xxx/CVE-2020-15701.json
2020/15xxx/CVE-2020-15702.json

Hello,
These are CVEs CVE-2020-11937, CVE-2020-15701 and CVE-2020-15702 from Ubuntu
Thank you

Whoopsie and apport vulnerabilities

---

2020/15xxx/CVE-2020-15138.json

Add CVE-2020-15138 for GHSA-wvhm-4hhf-97x9

Add CVE-2020-15138 for GHSA-wvhm-4hhf-97x9

---

2020/4xxx/CVE-2020-4533.json
2020/4xxx/CVE-2020-4539.json
2020/4xxx/CVE-2020-4541.json

Added CVE-2020-4533, CVE-2020-4539, and CVE-2020-4541.

Ibm20200810 83244

---

2020/15xxx/CVE-2020-15139.json

add CVE-2020-15139 for GHSA-37h7-vfv6-f8rj

add CVE-2020-15139 for GHSA-37h7-vfv6-f8rj

---

2020/4xxx/CVE-2020-4485.json
2020/4xxx/CVE-2020-4486.json

Added CVE-2020-4485 and CVE-2020-4486.

Ibm20200811 841

---

2020/8xxx/CVE-2020-8911.json
2020/8xxx/CVE-2020-8912.json

CVE-2020-8911 and 8912 for AWS Crypto SDK for GoLang

---

2020/2xxx/CVE-2020-2229.json
2020/2xxx/CVE-2020-2230.json
2020/2xxx/CVE-2020-2231.json
2020/2xxx/CVE-2020-2232.json
2020/2xxx/CVE-2020-2233.json
2020/2xxx/CVE-2020-2234.json
2020/2xxx/CVE-2020-2235.json
2020/2xxx/CVE-2020-2236.json
2020/2xxx/CVE-2020-2237.json

https://www.jenkins.io/security/advisory/2020-08-12/

Add CVEs for 2020-08-12 Jenkins security advisory

---

2020/15xxx/CVE-2020-15137.json

add CVE-2020-15137 for GHSA-8q4r-m3rh-57jx

add CVE-2020-15137 for GHSA-8q4r-m3rh-57jx

---

2020/2xxx/CVE-2020-2035.json

Published CVE-2020-2035 as part of Palo Alto Networks August 2020 patch Wednesday.

Published CVE-2020-2035

---

2020/7xxx/CVE-2020-7374.json

Added CVE info from Vulnogram (updated with feedback from @todb-r7 )

Updated CVE-2020-7374.

---

2020/15xxx/CVE-2020-15142.json

add CVE-2020-15142 for GHSA-9x4c-63pf-525f

add CVE-2020-15142 for GHSA-9x4c-63pf-525f

---

2020/15xxx/CVE-2020-15141.json

add CVE-2020-15141 for GHSA-7wgr-7666-7pwj

add CVE-2020-15141 for GHSA-7wgr-7666-7pwj

---

2020/15xxx/CVE-2020-15145.json

add CVE-2020-15145 for GHSA-wgrx-r3qv-332c

add CVE-2020-15145 for GHSA-wgrx-r3qv-332c

---

2020/15xxx/CVE-2020-15152.json

Add CVE-2020-15152 for GHSA-jw37-5gqr-cf9j

Add CVE-2020-15152 for GHSA-jw37-5gqr-cf9j

---

2020/4xxx/CVE-2020-4381.json
2020/4xxx/CVE-2020-4648.json
2020/4xxx/CVE-2020-4653.json

Added CVE-2020-4381, CVE-2020-4653, and CVE-2020-4648.

Ibm20200819 82952

---

2020/15xxx/CVE-2020-15149.json

Add CVE-2020-15149 for GHSA-hr66-c8pg-5mg7

Add CVE-2020-15149 for GHSA-hr66-c8pg-5mg7

---

2020/15xxx/CVE-2020-15151.json

Add CVE-2020-15151 for GHSA-crf2-xm6x-46p6

Add CVE-2020-15151 for GHSA-crf2-xm6x-46p6

---

2020/15xxx/CVE-2020-15146.json

Add CVE-2020-15146 for GHSA-h6m7-j4h3-9rf5

Add CVE-2020-15146 for GHSA-h6m7-j4h3-9rf5

---

2020/15xxx/CVE-2020-15143.json

Add CVE-2020-15143 for GHSA-p4pj-9g59-4ppv

Add CVE-2020-15143 for GHSA-p4pj-9g59-4ppv

---

2020/15xxx/CVE-2020-15119.json

Add CVE-2020-15119 for GHSA-6gg3-pmm7-97xc

Add CVE-2020-15119 for GHSA-6gg3-pmm7-97xc

---

2020/4xxx/CVE-2020-4548.json
2020/4xxx/CVE-2020-4687.json

Added CVE-2020-4548 and CVE-2020-4687.

Ibm20200820 115257

---

2018/1xxx/CVE-2018-1985.json
2020/4xxx/CVE-2020-4165.json
2020/4xxx/CVE-2020-4170.json
2020/4xxx/CVE-2020-4382.json
2020/4xxx/CVE-2020-4383.json
2020/4xxx/CVE-2020-4587.json
2020/4xxx/CVE-2020-4593.json
2020/4xxx/CVE-2020-4598.json

Added CVE-2018-1985, CVE-2020-4165, CVE-2020-4170, CVE-2020-4382, CVE-2020-4383, CVE-2020-4587, CVE-2020-4593, and CVE-2020-4598.

Ibm20200824 112817

---

2020/7xxx/CVE-2020-7309.json

Publish CVE-2020-7309.json

---

2020/15xxx/CVE-2020-15158.json

Add CVE-2020-15158 for GHSA-pq77-fmf7-hjw8

Add CVE-2020-15158 for GHSA-pq77-fmf7-hjw8

---

2018/1xxx/CVE-2018-1501.json
2019/4xxx/CVE-2019-4686.json
2019/4xxx/CVE-2019-4688.json
2019/4xxx/CVE-2019-4689.json
2019/4xxx/CVE-2019-4691.json
2019/4xxx/CVE-2019-4692.json
2019/4xxx/CVE-2019-4693.json
2019/4xxx/CVE-2019-4694.json
2019/4xxx/CVE-2019-4697.json
2019/4xxx/CVE-2019-4698.json
2019/4xxx/CVE-2019-4699.json
2019/4xxx/CVE-2019-4701.json
2019/4xxx/CVE-2019-4713.json

Added CVE-2019-4694, CVE-2019-4697, CVE-2019-4713, CVE-2019-4686, CVE-2019-4698, CVE-2019-4688, CVE-2019-4701, CVE-2019-4691, CVE-2019-4693, CVE-2019-4689, CVE-2019-4692, CVE-2018-1501, and CVE-2019-4699.

Ibm20200826 145745

---

2020/15xxx/CVE-2020-15156.json

Add CVE-2020-15156 for GHSA-43m5-c88r-cjvv

Add CVE-2020-15156 for GHSA-43m5-c88r-cjvv

---

2019/4xxx/CVE-2019-4695.json

Ibm20200826 151054

---

2020/4xxx/CVE-2020-4174.json

Ibm20200827 83827

---

2020/15xxx/CVE-2020-15601.json
2020/15xxx/CVE-2020-15605.json
2020/8xxx/CVE-2020-8602.json

Trend Micro CVE-2020-8602, 15601, 15605

Trend Micro CVE-2020-8602, 15601, 15605

---

2020/5xxx/CVE-2020-5621.json
2020/5xxx/CVE-2020-5623.json
2020/5xxx/CVE-2020-5624.json
2020/5xxx/CVE-2020-5625.json

Changed paths:
M 2020/5xxx/CVE-2020-5621.json
M 2020/5xxx/CVE-2020-5623.json
M 2020/5xxx/CVE-2020-5624.json
M 2020/5xxx/CVE-2020-5625.json

JPCERT/CC 2020-08-28

---

2019/4xxx/CVE-2019-4533.json
2019/4xxx/CVE-2019-4579.json
2020/4xxx/CVE-2020-4559.json
2020/4xxx/CVE-2020-4591.json

Added CVE-2019-4533, CVE-2020-4591, CVE-2019-4579, and CVE-2020-4559.

Ibm20200828 103242

---

2020/15xxx/CVE-2020-15164.json

add CVE-2020-15164 for GHSA-8fq5-g4m5-6j43

add CVE-2020-15164 for GHSA-8fq5-g4m5-6j43

---

2020/15xxx/CVE-2020-15165.json

add CVE-2020-15165 for GHSA-8q77-7hq8-f7g6

add CVE-2020-15165 for GHSA-8q77-7hq8-f7g6

---

2020/15xxx/CVE-2020-15154.json

Add CVE-2020-15154 for GHSA-cpxc-67rc-c775

Add CVE-2020-15154 for GHSA-cpxc-67rc-c775

---

2020/15xxx/CVE-2020-15155.json

Add CVE-2020-15155 for GHSA-4r3m-j6x5-48m3

Add CVE-2020-15155 for GHSA-4r3m-j6x5-48m3

---

2020/15xxx/CVE-2020-15159.json

Add CVE-2020-15159 for GHSA-673x-f5wx-fxpw

Add CVE-2020-15159 for GHSA-673x-f5wx-fxpw

---

2020/10xxx/CVE-2020-10289.json

Update version in CVE-2020-10289

---

2017/7xxx/CVE-2017-7876.json

Update following information,
- CWE 
- CVSSv3 score 
- product version

Update CWE CVSSv3 score and product version information

---

2020/15xxx/CVE-2020-15704.json

Hello,
This is CVE CVE-2020-15704 from Ubuntu
Thank you

ppp vulnerability info

---

2017/7xxx/CVE-2017-7876.json

update url of security advisory and release notes
update CWE and CVSSv3 score

CVE-2017-7876 update url of security advisory

---

2020/2xxx/CVE-2020-2238.json
2020/2xxx/CVE-2020-2239.json
2020/2xxx/CVE-2020-2240.json
2020/2xxx/CVE-2020-2241.json
2020/2xxx/CVE-2020-2242.json
2020/2xxx/CVE-2020-2243.json
2020/2xxx/CVE-2020-2244.json
2020/2xxx/CVE-2020-2245.json
2020/2xxx/CVE-2020-2246.json
2020/2xxx/CVE-2020-2247.json
2020/2xxx/CVE-2020-2248.json
2020/2xxx/CVE-2020-2249.json
2020/2xxx/CVE-2020-2250.json
2020/2xxx/CVE-2020-2251.json

https://www.jenkins.io/security/advisory/2020-09-01/

Add CVEs for 2020-09-01 Jenkins security advisory

---

2020/15xxx/CVE-2020-15150.json

add CVE-2020-15150 for GHSA-w98m-2xqg-9cvj

add CVE-2020-15150 for GHSA-w98m-2xqg-9cvj

---

2020/24xxx/CVE-2020-24556.json
2020/24xxx/CVE-2020-24557.json
2020/24xxx/CVE-2020-24558.json
2020/24xxx/CVE-2020-24559.json

Trend Micro CVE-2020-24556 through 24559

Trend Micro CVE-2020-24556 through 24559

---

2020/8xxx/CVE-2020-8335.json
2020/8xxx/CVE-2020-8341.json

lenovo_2020-09-01

---

2020/15xxx/CVE-2020-15094.json

Add CVE-2020-15094 for GHSA-754h-5r27-7x3r

Add CVE-2020-15094 for GHSA-754h-5r27-7x3r

---

2020/15xxx/CVE-2020-15167.json

Add CVE-2020-15167 for GHSA-mw2v-4q78-j2cw

Add CVE-2020-15167 for GHSA-mw2v-4q78-j2cw

---

2020/4xxx/CVE-2020-4337.json
2020/4xxx/CVE-2020-4638.json

Added CVE-2020-4638 and CVE-2020-4337.

Ibm20200903 95237

---

2020/4xxx/CVE-2020-4545.json
2020/4xxx/CVE-2020-4632.json
2020/4xxx/CVE-2020-4702.json

Added CVE-2020-4545, CVE-2020-4632, and CVE-2020-4702.

Ibm20200904 93226

---

2020/7xxx/CVE-2020-7299.json

Publish CVE-2020-7299.json

---

2020/4xxx/CVE-2020-4516.json
2020/4xxx/CVE-2020-4698.json

Added CVE-2020-4516 and CVE-2020-4698.

Ibm20200908 102744

---

2020/7xxx/CVE-2020-7320.json

Publish CVE-2020-7320.json

---

2020/7xxx/CVE-2020-7319.json

Publish the CVE please as SB is live

Publish CVE-2020-7319.json

---

2020/7xxx/CVE-2020-7322.json

Publish CVE-2020-7322.json

---

2020/7xxx/CVE-2020-7323.json

Publish CVE-2020-7323.json

---

2020/7xxx/CVE-2020-7324.json

Publish CVE-2020-7324.json

---

2020/7xxx/CVE-2020-7325.json

Publish CVE-2020-7325.json

---

2020/2xxx/CVE-2020-2036.json
2020/2xxx/CVE-2020-2037.json
2020/2xxx/CVE-2020-2038.json
2020/2xxx/CVE-2020-2039.json
2020/2xxx/CVE-2020-2040.json
2020/2xxx/CVE-2020-2041.json
2020/2xxx/CVE-2020-2042.json
2020/2xxx/CVE-2020-2043.json
2020/2xxx/CVE-2020-2044.json

PANW CVE assignments on September 9, 2020 Patch Wednesday.

PANW CVE assignments on September 9, 2020 Patch Wednesday.

---

2020/15xxx/CVE-2020-15163.json

Add CVE-2020-15163 for GHSA-f8mr-jv2c-v8mg

Add CVE-2020-15163 for GHSA-f8mr-jv2c-v8mg

---

2020/15xxx/CVE-2020-15173.json

Add CVE-2020-15173 for GHSA-rr68-fchr-69vf

Add CVE-2020-15173 for GHSA-rr68-fchr-69vf

---

2020/7xxx/CVE-2020-7312.json

Publish CVE-2020-7312.json

---

2020/7xxx/CVE-2020-7311.json

Publish CVE-2020-7311.json

---

2020/4xxx/CVE-2020-4578.json

Ibm20200910 12473

---

2020/15xxx/CVE-2020-15168.json

Add CVE-2020-15168 for GHSA-w7rc-rwvf-8q5r

Add CVE-2020-15168 for GHSA-w7rc-rwvf-8q5r

---

2020/15xxx/CVE-2020-15170.json

Add CVE-2020-15170 for GHSA-xpmx-h7xq-xffh

Add CVE-2020-15170 for GHSA-xpmx-h7xq-xffh

---

2020/15xxx/CVE-2020-15171.json

Add CVE-2020-15171 for GHSA-7qw5-pqhc-xm4g

Add CVE-2020-15171 for GHSA-7qw5-pqhc-xm4g

---

2014/1xxx/CVE-2014-1420.json

Hello,
This is CVE-2014-1420 from Ubuntu
Thank you

Ubuntu UI Toolkit CVE

---

2020/15xxx/CVE-2020-15166.json

Add CVE-2020-15166 for GHSA-25wp-cf8g-938m

Add CVE-2020-15166 for GHSA-25wp-cf8g-938m

---

2020/15xxx/CVE-2020-15169.json

Add CVE-2020-15169 for GHSA-cfjv-5498-mph5

Add CVE-2020-15169 for GHSA-cfjv-5498-mph5

---

2020/8xxx/CVE-2020-8339.json
2020/8xxx/CVE-2020-8340.json
2020/8xxx/CVE-2020-8342.json
2020/8xxx/CVE-2020-8346.json

2020-09 CVE population

---

2020/15xxx/CVE-2020-15178.json

Add CVE-2020-15178 for GHSA-95hx-62rh-gg96

Add CVE-2020-15178 for GHSA-95hx-62rh-gg96

---

2020/15xxx/CVE-2020-15179.json

Add CVE-2020-15179 for GHSA-gp9v-pg9f-vmp6

Add CVE-2020-15179 for GHSA-gp9v-pg9f-vmp6

---

2020/15xxx/CVE-2020-15148.json

Add CVE-2020-15148 for GHSA-699q-wcff-g9mj

Add CVE-2020-15148 for GHSA-699q-wcff-g9mj

---

2020/15xxx/CVE-2020-15172.json

Add CVE-2020-15172 for GHSA-rm7m-j4xp-rv2p

Add CVE-2020-15172 for GHSA-rm7m-j4xp-rv2p

---

2020/24xxx/CVE-2020-24561.json

Trend Micro CVE-2020-24561

---

2020/2xxx/CVE-2020-2252.json
2020/2xxx/CVE-2020-2253.json
2020/2xxx/CVE-2020-2254.json
2020/2xxx/CVE-2020-2255.json
2020/2xxx/CVE-2020-2256.json
2020/2xxx/CVE-2020-2257.json
2020/2xxx/CVE-2020-2258.json
2020/2xxx/CVE-2020-2259.json
2020/2xxx/CVE-2020-2260.json
2020/2xxx/CVE-2020-2261.json
2020/2xxx/CVE-2020-2262.json
2020/2xxx/CVE-2020-2263.json
2020/2xxx/CVE-2020-2264.json
2020/2xxx/CVE-2020-2265.json
2020/2xxx/CVE-2020-2266.json
2020/2xxx/CVE-2020-2267.json
2020/2xxx/CVE-2020-2268.json
2020/2xxx/CVE-2020-2269.json
2020/2xxx/CVE-2020-2270.json
2020/2xxx/CVE-2020-2271.json
2020/2xxx/CVE-2020-2272.json
2020/2xxx/CVE-2020-2273.json
2020/2xxx/CVE-2020-2274.json
2020/2xxx/CVE-2020-2275.json
2020/2xxx/CVE-2020-2276.json
2020/2xxx/CVE-2020-2277.json
2020/2xxx/CVE-2020-2278.json

https://www.jenkins.io/security/advisory/2020-09-16/

Add CVEs for 2020-09-16 Jenkins security advisory

---

2020/4xxx/CVE-2020-4409.json
2020/4xxx/CVE-2020-4708.json

Added CVE-2020-4708 and CVE-2020-4409.

Ibm20200916 115310

---

2020/2xxx/CVE-2020-2255.json

https://github.com/jenkins-infra/jenkins.io/pull/3704

[SECURITY-1961] Fix CWE

---

2020/15xxx/CVE-2020-15182.json

Add CVE-2020-15182 for GHSA-j2qw-747j-mfv4

Add CVE-2020-15182 for GHSA-j2qw-747j-mfv4

---

2020/15xxx/CVE-2020-15183.json

Add CVE-2020-15183 for GHSA-33q6-4xmp-2f48

Add CVE-2020-15183 for GHSA-33q6-4xmp-2f48

---

2020/15xxx/CVE-2020-15184.json

Add CVE-2020-15184 for GHSA-9vp5-m38w-j776

Add CVE-2020-15184 for GHSA-9vp5-m38w-j776

---

2020/15xxx/CVE-2020-15185.json

Add CVE-2020-15185 for GHSA-jm56-5h66-w453

Add CVE-2020-15185 for GHSA-jm56-5h66-w453

---

2020/15xxx/CVE-2020-15186.json

Add CVE-2020-15186 for GHSA-m54r-vrmv-hw33

Add CVE-2020-15186 for GHSA-m54r-vrmv-hw33

---

2020/15xxx/CVE-2020-15187.json

Add CVE-2020-15187 for GHSA-c52f-pq47-2r9j

Add CVE-2020-15187 for GHSA-c52f-pq47-2r9j

---

2020/5xxx/CVE-2020-5976.json

NVIDIA CVE-2020-5976

---

2020/15xxx/CVE-2020-15188.json

Add CVE-2020-15188 for GHSA-hrrx-m22r-p9jp

Add CVE-2020-15188 for GHSA-hrrx-m22r-p9jp

---

2020/15xxx/CVE-2020-15189.json

Add CVE-2020-15189 for GHSA-6r2f-p68g-m433

Add CVE-2020-15189 for GHSA-6r2f-p68g-m433

---

2020/15xxx/CVE-2020-15181.json

Add CVE-2020-15181 for GHSA-xrc8-fjp4-h4fv

Add CVE-2020-15181 for GHSA-xrc8-fjp4-h4fv

---

2020/15xxx/CVE-2020-15182.json

Update CVE-2020-15182 links and CWEs

Update CVE-2020-15182 links and CWEs

---

2020/4xxx/CVE-2020-4643.json

Ibm20200921 13620

---

2020/4xxx/CVE-2020-4611.json
2020/4xxx/CVE-2020-4612.json
2020/4xxx/CVE-2020-4613.json
2020/4xxx/CVE-2020-4614.json
2020/4xxx/CVE-2020-4615.json
2020/4xxx/CVE-2020-4616.json
2020/4xxx/CVE-2020-4617.json
2020/4xxx/CVE-2020-4618.json
2020/4xxx/CVE-2020-4619.json
2020/4xxx/CVE-2020-4620.json
2020/4xxx/CVE-2020-4621.json
2020/4xxx/CVE-2020-4622.json

Added CVE-2020-4618, CVE-2020-4621, CVE-2020-4622, CVE-2020-4614, CVE-2020-4613, CVE-2020-4619, CVE-2020-4612, CVE-2020-4620, CVE-2020-4616, CVE-2020-4611, CVE-2020-4617, and CVE-2020-4615.

Ibm20200922 94851

---

2020/2xxx/CVE-2020-2279.json
2020/2xxx/CVE-2020-2280.json
2020/2xxx/CVE-2020-2281.json
2020/2xxx/CVE-2020-2282.json
2020/2xxx/CVE-2020-2283.json
2020/2xxx/CVE-2020-2284.json
2020/2xxx/CVE-2020-2285.json

https://www.jenkins.io/security/advisory/2020-09-23/

Add 2020-09-23 Jenkins security advisory

---

2020/4xxx/CVE-2020-4324.json
2020/4xxx/CVE-2020-4340.json

Added CVE-2020-4340 and CVE-2020-4324.

Ibm20200923 93924

---

2020/11xxx/CVE-2020-11031.json

Add CVE-2020-11031 for GHSA-7xwm-4vjr-jvqh

Add CVE-2020-11031 for GHSA-7xwm-4vjr-jvqh

---

2020/15xxx/CVE-2020-15223.json

Add CVE-2020-15223 for GHSA-7mqr-2v3q-v2wm

Add CVE-2020-15223 for GHSA-7mqr-2v3q-v2wm

---

2020/15xxx/CVE-2020-15222.json

Add CVE-2020-15222 for GHSA-v3q9-2p3m-7g43

Add CVE-2020-15222 for GHSA-v3q9-2p3m-7g43

---

2020/8xxx/CVE-2020-8325.json
2020/8xxx/CVE-2020-8328.json
2020/8xxx/CVE-2020-8333.json
2020/8xxx/CVE-2020-8343.json
2020/8xxx/CVE-2020-8344.json
2020/8xxx/CVE-2020-8347.json
2020/8xxx/CVE-2020-8348.json

2020-09-24

---

2020/15xxx/CVE-2020-15161.json

Add CVE-2020-15161 for GHSA-5cp2-r794-w37w

Add CVE-2020-15161 for GHSA-5cp2-r794-w37w

---

2020/15xxx/CVE-2020-15160.json

Add CVE-2020-15160 for GHSA-fghq-8h87-826g

Add CVE-2020-15160 for GHSA-fghq-8h87-826g

---

2020/15xxx/CVE-2020-15162.json

Add CVE-2020-15162 for GHSA-rc8c-v7rq-q392

Add CVE-2020-15162 for GHSA-rc8c-v7rq-q392

---

2020/15xxx/CVE-2020-15190.json

Add CVE-2020-15190 for GHSA-4g9f-63rx-5cw4

Add CVE-2020-15190 for GHSA-4g9f-63rx-5cw4

---

2020/15xxx/CVE-2020-15200.json

Add CVE-2020-15200 for GHSA-x7rp-74x2-mjf3

Add CVE-2020-15200 for GHSA-x7rp-74x2-mjf3

---

2020/15xxx/CVE-2020-15199.json

Add CVE-2020-15199 for GHSA-x5cp-9pcf-pp3h

Add CVE-2020-15199 for GHSA-x5cp-9pcf-pp3h

---

2020/15xxx/CVE-2020-15198.json

Add CVE-2020-15198 for GHSA-jc87-6vpp-7ff3

Add CVE-2020-15198 for GHSA-jc87-6vpp-7ff3

---

2020/15xxx/CVE-2020-15197.json

Add CVE-2020-15197 for GHSA-qc53-44cj-vfvx

Add CVE-2020-15197 for GHSA-qc53-44cj-vfvx

---

2020/15xxx/CVE-2020-15195.json

Add CVE-2020-15195 for GHSA-63xm-rx5p-xvqr

Add CVE-2020-15195 for GHSA-63xm-rx5p-xvqr

---

2020/15xxx/CVE-2020-15194.json

Add CVE-2020-15194 for GHSA-9mqp-7v2h-2382

Add CVE-2020-15194 for GHSA-9mqp-7v2h-2382

---

2020/15xxx/CVE-2020-15193.json

Add CVE-2020-15193 for GHSA-rjjg-hgv6-h69v

Add CVE-2020-15193 for GHSA-rjjg-hgv6-h69v

---

2020/15xxx/CVE-2020-15192.json

Add CVE-2020-15192 for GHSA-8fxw-76px-3rxv

Add CVE-2020-15192 for GHSA-8fxw-76px-3rxv

---

2020/15xxx/CVE-2020-15191.json

Add CVE-2020-15191 for GHSA-q8qj-fc9q-cphr

Add CVE-2020-15191 for GHSA-q8qj-fc9q-cphr

---

2020/15xxx/CVE-2020-15211.json

Add CVE-2020-15211 for GHSA-cvpc-8phh-8f45

Add CVE-2020-15211 for GHSA-cvpc-8phh-8f45

---

2020/15xxx/CVE-2020-15210.json

Add CVE-2020-15210 for GHSA-x9j7-x98r-r4w2

Add CVE-2020-15210 for GHSA-x9j7-x98r-r4w2

---

2020/15xxx/CVE-2020-15209.json

Add CVE-2020-15209 for GHSA-qh32-6jjc-qprm

Add CVE-2020-15209 for GHSA-qh32-6jjc-qprm

---

2020/15xxx/CVE-2020-15208.json

Add CVE-2020-15208 for GHSA-mxjj-953w-2c2v

Add CVE-2020-15208 for GHSA-mxjj-953w-2c2v

---

2020/15xxx/CVE-2020-15207.json

Add CVE-2020-15207 for GHSA-q4qf-3fc6-8x34

Add CVE-2020-15207 for GHSA-q4qf-3fc6-8x34

---

2020/15xxx/CVE-2020-15206.json

Add CVE-2020-15206 for GHSA-w5gh-2wr2-pm6g

Add CVE-2020-15206 for GHSA-w5gh-2wr2-pm6g

---

2020/15xxx/CVE-2020-15205.json

Add CVE-2020-15205 for GHSA-g7p5-5759-qv46

Add CVE-2020-15205 for GHSA-g7p5-5759-qv46

---

2020/15xxx/CVE-2020-15204.json

Add CVE-2020-15204 for GHSA-q8gv-q7wr-9jf8

Add CVE-2020-15204 for GHSA-q8gv-q7wr-9jf8

---

2020/15xxx/CVE-2020-15203.json

Add CVE-2020-15203 for GHSA-xmq7-7fxm-rr79

Add CVE-2020-15203 for GHSA-xmq7-7fxm-rr79

---

2020/15xxx/CVE-2020-15202.json

Add CVE-2020-15202 for GHSA-h6fg-mjxg-hqq4

Add CVE-2020-15202 for GHSA-h6fg-mjxg-hqq4

---

2020/15xxx/CVE-2020-15201.json

Add CVE-2020-15201 for GHSA-p5f8-gfw5-33w4

Add CVE-2020-15201 for GHSA-p5f8-gfw5-33w4

---

2020/15xxx/CVE-2020-15214.json

Add CVE-2020-15214 for GHSA-p2cq-cprg-frvm

Add CVE-2020-15214 for GHSA-p2cq-cprg-frvm

---

2020/15xxx/CVE-2020-15213.json

Add CVE-2020-15213 for GHSA-hjmq-236j-8m87

Add CVE-2020-15213 for GHSA-hjmq-236j-8m87

---

2020/15xxx/CVE-2020-15212.json

Add CVE-2020-15212 for GHSA-hx2x-85gr-wrpq

Add CVE-2020-15212 for GHSA-hx2x-85gr-wrpq

---

2020/15xxx/CVE-2020-15216.json

Add CVE-2020-15216 for GHSA-q547-gmf8-8jr7

Add CVE-2020-15216 for GHSA-q547-gmf8-8jr7

---

2020/15xxx/CVE-2020-15228.json

Add CVE-2020-15228 for GHSA-mfwh-5m23-j46w

Add CVE-2020-15228 for GHSA-mfwh-5m23-j46w

---

2020/15xxx/CVE-2020-15227.json

Add CVE-2020-15227 for GHSA-8gv3-3j7f-wg94

Add CVE-2020-15227 for GHSA-8gv3-3j7f-wg94

---

2020/10xxx/CVE-2020-10060.json

Add links to fixes in upstream repository.

Update CVE-2020-10060 with links to fixes

---

2020/7xxx/CVE-2020-7068.json
2020/7xxx/CVE-2020-7069.json
2020/7xxx/CVE-2020-7070.json

Also fix version in CVE-2020-7068

Document fresh PHP CVEs

---

2020/5xxx/CVE-2020-5979.json
2020/5xxx/CVE-2020-5980.json
2020/5xxx/CVE-2020-5981.json
2020/5xxx/CVE-2020-5982.json

NVIDIA CVEs GPU Sept 2020

---

2020/15xxx/CVE-2020-15230.json

Add CVE-2020-15230 for GHSA-vcvg-xgr8-p5gq

Add CVE-2020-15230 for GHSA-vcvg-xgr8-p5gq

---

2020/15xxx/CVE-2020-15231.json

Add CVE-2020-15231 for GHSA-w534-q4xf-h5v2

Add CVE-2020-15231 for GHSA-w534-q4xf-h5v2

---

2020/15xxx/CVE-2020-15232.json

Add CVE-2020-15232 for GHSA-vjv6-gq77-3mjw

Add CVE-2020-15232 for GHSA-vjv6-gq77-3mjw

---

2020/15xxx/CVE-2020-15234.json

Add CVE-2020-15234 for GHSA-grfp-q2mm-hfp6

Add CVE-2020-15234 for GHSA-grfp-q2mm-hfp6

---

2020/15xxx/CVE-2020-15233.json

Add CVE-2020-15233 for GHSA-rfq3-w54c-f9q5

Add CVE-2020-15233 for GHSA-rfq3-w54c-f9q5

---

2020/5xxx/CVE-2020-5983.json
2020/5xxx/CVE-2020-5984.json
2020/5xxx/CVE-2020-5985.json
2020/5xxx/CVE-2020-5986.json
2020/5xxx/CVE-2020-5987.json
2020/5xxx/CVE-2020-5988.json
2020/5xxx/CVE-2020-5989.json

NVIDIA CVEs-vGPU Driver-Sept-2020

NVIDIA CVEs-vGPU Driver-Sept-2020

---

2020/4xxx/CVE-2020-4493.json

Ibm20201005 92026

---

2020/15xxx/CVE-2020-15236.json

Add CVE-2020-15236 for GHSA-whpv-5xg2-w527

Add CVE-2020-15236 for GHSA-whpv-5xg2-w527

---

2020/15xxx/CVE-2020-15235.json

Add CVE-2020-15235 for GHSA-ph67-c355-52vm

Add CVE-2020-15235 for GHSA-ph67-c355-52vm

---

2020/15xxx/CVE-2020-15237.json

Add CVE-2020-15237 for GHSA-5jjv-x4fq-qjwp

Add CVE-2020-15237 for GHSA-5jjv-x4fq-qjwp

---

2020/25xxx/CVE-2020-25802.json

CVE-2020-25802: https://docs.craftercms.org/en/3.1/security/advisory.html#cv-2020080101

CVE-2020-25802

---

2020/25xxx/CVE-2020-25803.json

CVE-2020-25803: https://docs.craftercms.org/en/3.1/security/advisory.html#cv-2020080102

CVE-2020-25803

---

2019/4xxx/CVE-2019-4725.json
2020/4xxx/CVE-2020-4528.json

Added CVE-2020-4528 and CVE-2019-4725.

Ibm20201006 114222

---

2020/15xxx/CVE-2020-15174.json

Add CVE-2020-15174 for GHSA-2q4g-w47c-4674

Add CVE-2020-15174 for GHSA-2q4g-w47c-4674

---

2020/15xxx/CVE-2020-15215.json

Add CVE-2020-15215 for GHSA-56pc-6jqp-xqj8

Add CVE-2020-15215 for GHSA-56pc-6jqp-xqj8

---

2020/15xxx/CVE-2020-15239.json

Add CVE-2020-15239 for GHSA-hwv5-w8gm-fq9f

Add CVE-2020-15239 for GHSA-hwv5-w8gm-fq9f

---

2020/15xxx/CVE-2020-15175.json

Add CVE-2020-15175 for GHSA-rm52-jx9h-rwcp

Add CVE-2020-15175 for GHSA-rm52-jx9h-rwcp

---

2020/15xxx/CVE-2020-15176.json

Add CVE-2020-15176 for GHSA-x93w-64x9-58qw

Add CVE-2020-15176 for GHSA-x93w-64x9-58qw

---

2020/15xxx/CVE-2020-15177.json

Add CVE-2020-15177 for GHSA-prvh-9m4h-4m79

Add CVE-2020-15177 for GHSA-prvh-9m4h-4m79

---

2020/15xxx/CVE-2020-15217.json

Add CVE-2020-15217 for GHSA-x9hg-j29f-wvvv

Add CVE-2020-15217 for GHSA-x9hg-j29f-wvvv

---

2020/15xxx/CVE-2020-15226.json

Add CVE-2020-15226 for GHSA-jwpv-7m4h-5gvc

Add CVE-2020-15226 for GHSA-jwpv-7m4h-5gvc

---

2020/2xxx/CVE-2020-2286.json
2020/2xxx/CVE-2020-2287.json
2020/2xxx/CVE-2020-2288.json
2020/2xxx/CVE-2020-2289.json
2020/2xxx/CVE-2020-2290.json
2020/2xxx/CVE-2020-2291.json
2020/2xxx/CVE-2020-2292.json
2020/2xxx/CVE-2020-2293.json
2020/2xxx/CVE-2020-2294.json
2020/2xxx/CVE-2020-2295.json
2020/2xxx/CVE-2020-2296.json
2020/2xxx/CVE-2020-2297.json
2020/2xxx/CVE-2020-2298.json

https://www.jenkins.io/security/advisory/2020-10-08/

Add CVEs for Jenkins 2020-10-08 security advisory

---

2019/4xxx/CVE-2019-4545.json
2020/4xxx/CVE-2020-4280.json
2020/4xxx/CVE-2020-4799.json

Added CVE-2020-4799, CVE-2020-4280, and CVE-2019-4545.

Ibm20201008 91428

---

2020/15xxx/CVE-2020-15242.json

Add CVE-2020-15242 for GHSA-x56p-c8cg-q435

Add CVE-2020-15242 for GHSA-x56p-c8cg-q435

---

2020/15xxx/CVE-2020-15241.json

Add CVE-2020-15241 for GHSA-7733-hjv6-4h47

Add CVE-2020-15241 for GHSA-7733-hjv6-4h47

---

2020/15xxx/CVE-2020-15243.json

Add CVE-2020-15243 for GHSA-8g9m-jx26-qp4h

Add CVE-2020-15243 for GHSA-8g9m-jx26-qp4h

---

2020/5xxx/CVE-2020-5133.json
2020/5xxx/CVE-2020-5134.json
2020/5xxx/CVE-2020-5135.json
2020/5xxx/CVE-2020-5136.json
2020/5xxx/CVE-2020-5137.json
2020/5xxx/CVE-2020-5138.json
2020/5xxx/CVE-2020-5139.json
2020/5xxx/CVE-2020-5140.json
2020/5xxx/CVE-2020-5141.json
2020/5xxx/CVE-2020-5142.json
2020/5xxx/CVE-2020-5143.json

Submitting all vulnerabilitiy CVE files 2020-5133 to 2020-5143 and performing commit to master.

Modified all CVE files and submitting

---

2020/4xxx/CVE-2020-4660.json
2020/4xxx/CVE-2020-4661.json
2020/4xxx/CVE-2020-4699.json
2020/4xxx/CVE-2020-4772.json
2020/4xxx/CVE-2020-4773.json
2020/4xxx/CVE-2020-4774.json
2020/4xxx/CVE-2020-4775.json
2020/4xxx/CVE-2020-4776.json
2020/4xxx/CVE-2020-4778.json
2020/4xxx/CVE-2020-4779.json
2020/4xxx/CVE-2020-4780.json
2020/4xxx/CVE-2020-4781.json

Added CVE-2020-4699, CVE-2020-4779, CVE-2020-4778, CVE-2020-4772, CVE-2020-4781, CVE-2020-4780, CVE-2020-4775, CVE-2020-4773, CVE-2020-4660, CVE-2020-4776, CVE-2020-4774, and CVE-2020-4661.

Ibm20201012 9225

---

2020/4xxx/CVE-2020-4302.json
2020/4xxx/CVE-2020-4388.json
2020/4xxx/CVE-2020-4678.json
2020/4xxx/CVE-2020-4679.json
2020/4xxx/CVE-2020-4680.json
2020/4xxx/CVE-2020-4681.json
2020/4xxx/CVE-2020-4689.json
2020/4xxx/CVE-2020-4740.json
2020/4xxx/CVE-2020-4741.json

Added CVE-2020-4689, CVE-2020-4679, CVE-2020-4678, CVE-2020-4388, CVE-2020-4302, CVE-2020-4741, CVE-2020-4740, CVE-2020-4681, and CVE-2020-4680.

Ibm20201012 91546

---

2020/15xxx/CVE-2020-15250.json

Add CVE-2020-15250 for GHSA-269g-pwp5-87pp

Add CVE-2020-15250 for GHSA-269g-pwp5-87pp

---

2020/17xxx/CVE-2020-17406.json
2020/17xxx/CVE-2020-17407.json
2020/17xxx/CVE-2020-17409.json
2020/17xxx/CVE-2020-17410.json
2020/17xxx/CVE-2020-17411.json
2020/17xxx/CVE-2020-17412.json
2020/17xxx/CVE-2020-17413.json
2020/17xxx/CVE-2020-17414.json
2020/17xxx/CVE-2020-17415.json
2020/17xxx/CVE-2020-17416.json
2020/17xxx/CVE-2020-17417.json

ZDI assigns the following CVEs:
M  2020/17xxx/CVE-2020-17406.json
M  2020/17xxx/CVE-2020-17407.json
M  2020/17xxx/CVE-2020-17409.json
M  2020/17xxx/CVE-2020-17410.json
M  2020/17xxx/CVE-2020-17411.json
M  2020/17xxx/CVE-2020-17412.json
M  2020/17xxx/CVE-2020-17413.json
M  2020/17xxx/CVE-2020-17414.json
M  2020/17xxx/CVE-2020-17415.json
M  2020/17xxx/CVE-2020-17416.json
M  2020/17xxx/CVE-2020-17417.json

ZDI assigns the following CVEs

---

2020/15xxx/CVE-2020-15251.json

Add CVE-2020-15251 for GHSA-j257-jfvv-h3x5

Add CVE-2020-15251 for GHSA-j257-jfvv-h3x5

---

2020/15xxx/CVE-2020-15253.json

Add CVE-2020-15253 for GHSA-7f37-2fjr-v9p7

Add CVE-2020-15253 for GHSA-7f37-2fjr-v9p7

---

2020/15xxx/CVE-2020-15224.json

Add CVE-2020-15224 for GHSA-525h-wxcc-f66m

Add CVE-2020-15224 for GHSA-525h-wxcc-f66m

---

2020/15xxx/CVE-2020-15229.json

Add CVE-2020-15229 for GHSA-7gcp-w6ww-2xv9

Add CVE-2020-15229 for GHSA-7gcp-w6ww-2xv9

---

2020/8xxx/CVE-2020-8332.json
2020/8xxx/CVE-2020-8338.json
2020/8xxx/CVE-2020-8345.json
2020/8xxx/CVE-2020-8349.json
2020/8xxx/CVE-2020-8350.json

2020-10-13_CVEs

---

2020/5xxx/CVE-2020-5642.json

Changed paths:
M 2020/5xxx/CVE-2020-5642.json

JPCERT/CC CVE-2020-5642

---

2020/7xxx/CVE-2020-7334.json

SB is live. There are some pending changes to the SB. They will be done today

Publish CVE-2020-7334.json

---

2020/7xxx/CVE-2020-7326.json

Publish CVE-2020-7326.json

---

2020/7xxx/CVE-2020-7327.json

Publish CVE-2020-7327.json

---

2019/4xxx/CVE-2019-4552.json
2020/4xxx/CVE-2020-4499.json

Added CVE-2019-4552 and CVE-2020-4499.

Ibm20201015 82452

---

2020/15xxx/CVE-2020-15251.json

Per request from the software maintainer, the description and reference list of CVE-2020-15251 is updated.

Update CVE-2020-15251 description and references

---

2019/17xxx/CVE-2019-17640.json

CVE-2019-17640

---

2020/15xxx/CVE-2020-15255.json

Add CVE-2020-15255 for GHSA-prjf-9mgh-8fpv

Add CVE-2020-15255 for GHSA-prjf-9mgh-8fpv

---

2020/4xxx/CVE-2020-4254.json
2020/4xxx/CVE-2020-4636.json

Added CVE-2020-4254 and CVE-2020-4636.

Ibm20201016 123712

---

2020/15xxx/CVE-2020-15258.json

Add CVE-2020-15258 for GHSA-5gpx-9976-ggpm

Add CVE-2020-15258 for GHSA-5gpx-9976-ggpm

---

2020/15xxx/CVE-2020-15252.json

Add CVE-2020-15252 for GHSA-5hv6-mh8q-q9v8

Add CVE-2020-15252 for GHSA-5hv6-mh8q-q9v8

---

2020/3xxx/CVE-2020-3427.json

Updating CVE-2020-3427

---

2020/15xxx/CVE-2020-15262.json

Add CVE-2020-15262 for GHSA-4fc4-chg7-h8gh

Add CVE-2020-15262 for GHSA-4fc4-chg7-h8gh

---

2020/15xxx/CVE-2020-15263.json

Add CVE-2020-15263 for GHSA-589w-hccm-265x

Add CVE-2020-15263 for GHSA-589w-hccm-265x

---

2020/15xxx/CVE-2020-15245.json

Add CVE-2020-15245 for GHSA-6gw4-x63h-5499

Add CVE-2020-15245 for GHSA-6gw4-x63h-5499

---

2020/15xxx/CVE-2020-15256.json

Add CVE-2020-15256 for GHSA-cwx2-736x-mf6w

Add CVE-2020-15256 for GHSA-cwx2-736x-mf6w

---

2020/15xxx/CVE-2020-15261.json

Add CVE-2020-15261 for GHSA-c8cc-x786-hqqp

Add CVE-2020-15261 for GHSA-c8cc-x786-hqqp

---

2020/4xxx/CVE-2020-4254.json
2020/4xxx/CVE-2020-4636.json

Added CVE-2020-4254 and CVE-2020-4636.

Ibm20201019 111037

---

2019/4xxx/CVE-2019-4680.json
2020/4xxx/CVE-2020-4491.json
2020/4xxx/CVE-2020-4564.json
2020/4xxx/CVE-2020-4748.json
2020/4xxx/CVE-2020-4749.json
2020/4xxx/CVE-2020-4755.json
2020/4xxx/CVE-2020-4756.json

Added CVE-2020-4756, CVE-2019-4680, CVE-2020-4749, CVE-2020-4748, CVE-2020-4491, CVE-2020-4755, and CVE-2020-4564.

Ibm20201020 101214

---

2020/15xxx/CVE-2020-15269.json

Add CVE-2020-15269 for GHSA-f8cm-364f-q9qh

Add CVE-2020-15269 for GHSA-f8cm-364f-q9qh

---

2020/15xxx/CVE-2020-15240.json

Add CVE-2020-15240 for GHSA-58r4-h6v8-jcvm

Add CVE-2020-15240 for GHSA-58r4-h6v8-jcvm

---

2020/15xxx/CVE-2020-15244.json

Add CVE-2020-15244 for GHSA-jrgf-vfw2-hj26

Add CVE-2020-15244 for GHSA-jrgf-vfw2-hj26

---

2020/15xxx/CVE-2020-15265.json

Add CVE-2020-15265 for GHSA-rrfp-j2mp-hq9c

Add CVE-2020-15265 for GHSA-rrfp-j2mp-hq9c

---

2020/15xxx/CVE-2020-15270.json

Add CVE-2020-15270 for GHSA-2xm2-xj2q-qgpj

Add CVE-2020-15270 for GHSA-2xm2-xj2q-qgpj

---

2020/1xxx/CVE-2020-1682.json

Hello Mitre,
We just updated CVE-2020-1682
could you please approve this pull request?
many thanks,
Omar

Updating CVE-2020-1682

---

2020/5xxx/CVE-2020-5977.json
2020/5xxx/CVE-2020-5978.json
2020/5xxx/CVE-2020-5990.json

NVIDIA GFE - CVEs for October 2020 - CVE‑2020‑5977, CVE‑2020‑5978, CVE‑2020‑5990

NVIDIA GFE - CVEs for October 2020 - CVE‑2020‑5977, CVE‑2020‑5978, CVE‑2020‑5990

---

2020/15xxx/CVE-2020-15271.json

Add CVE-2020-15271 for GHSA-c84h-w6cr-5v8q

Add CVE-2020-15271 for GHSA-c84h-w6cr-5v8q

---

2020/15xxx/CVE-2020-15272.json

Add CVE-2020-15272 for GHSA-hgx2-4pp9-357g

Add CVE-2020-15272 for GHSA-hgx2-4pp9-357g

---

2020/15xxx/CVE-2020-15274.json

Add CVE-2020-15274 for GHSA-pgjv-84m7-62q7

Add CVE-2020-15274 for GHSA-pgjv-84m7-62q7

---

2020/15xxx/CVE-2020-15238.json

Add CVE-2020-15238 for GHSA-jpc9-mgw6-2xwx

Add CVE-2020-15238 for GHSA-jpc9-mgw6-2xwx

---

2020/5xxx/CVE-2020-5144.json
2020/5xxx/CVE-2020-5145.json

Submitting two SonicWall Global VPN Client vulnerabilities, CVE-2020-5144 and CVE-2020-5145

SonicWall Global VPN Client vulnerabilities

---

2020/15xxx/CVE-2020-15278.json

Add CVE-2020-15278 for GHSA-mp9m-g7qj-6vqr

Add CVE-2020-15278 for GHSA-mp9m-g7qj-6vqr

---

2018/19xxx/CVE-2018-19943.json
2018/19xxx/CVE-2018-19949.json
2018/19xxx/CVE-2018-19953.json

The link of security advisory is at https://www.qnap.com/zh-tw/security-advisory/qsa-20-01

Update CVE-2018-19943, CVE-2018-19949, and CVE-2018-19953

---

2020/11xxx/CVE-2020-11483.json
2020/11xxx/CVE-2020-11484.json
2020/11xxx/CVE-2020-11485.json
2020/11xxx/CVE-2020-11486.json
2020/11xxx/CVE-2020-11487.json
2020/11xxx/CVE-2020-11488.json
2020/11xxx/CVE-2020-11489.json
2020/11xxx/CVE-2020-11615.json
2020/11xxx/CVE-2020-11616.json

CVEs for NVIDIA-DGX-October-2020

NVIDIA-DGX-October-2020

---

2020/27xxx/CVE-2020-27649.json
2020/27xxx/CVE-2020-27651.json
2020/27xxx/CVE-2020-27653.json
2020/27xxx/CVE-2020-27654.json
2020/27xxx/CVE-2020-27655.json
2020/27xxx/CVE-2020-27657.json
2020/27xxx/CVE-2020-27658.json

Added CVE-2020-27649, CVE-2020-27651, CVE-2020-27653, CVE-2020-27654, CVE-2020-27655, CVE-2020-27657, and CVE-2020-27658.

Synology-SA-20:14

---

2020/27xxx/CVE-2020-27648.json
2020/27xxx/CVE-2020-27650.json
2020/27xxx/CVE-2020-27652.json
2020/27xxx/CVE-2020-27656.json

Added CVE-2020-27648, CVE-2020-27650, CVE-2020-27652, and CVE-2020-27656.

Synology-SA-20:18

---

2019/4xxx/CVE-2019-4547.json
2019/4xxx/CVE-2019-4563.json
2020/4xxx/CVE-2020-4721.json
2020/4xxx/CVE-2020-4722.json
2020/4xxx/CVE-2020-4723.json
2020/4xxx/CVE-2020-4724.json
2020/4xxx/CVE-2020-4864.json

Added CVE-2020-4723, CVE-2020-4722, CVE-2020-4864, CVE-2020-4721, CVE-2019-4547, CVE-2019-4563, and CVE-2020-4724.

Ibm20201029 114755

---

2020/26xxx/CVE-2020-26205.json

Add CVE-2020-26205 per request from maintainer

Add CVE-2020-26205 per request from maintainer

---

2020/7xxx/CVE-2020-7326.json

CWE has been updated. Correct CWE added

Update this CVE

---

2020/4xxx/CVE-2020-4584.json
2020/4xxx/CVE-2020-4588.json

Added CVE-2020-4588 and CVE-2020-4584.

Ibm20201030 9497

---

2020/15xxx/CVE-2020-15276.json

Add CVE-2020-15276 for GHSA-fw5q-j9p4-3vxg

Add CVE-2020-15276 for GHSA-fw5q-j9p4-3vxg

---

2020/15xxx/CVE-2020-15273.json

Add CVE-2020-15273 for GHSA-wpww-4jf4-4hx8

Add CVE-2020-15273 for GHSA-wpww-4jf4-4hx8

---

2020/5xxx/CVE-2020-5991.json

CVE-2020-5991 for CUDA-Toolkit-October 2020

CVE-2020-5991 for CUDA-Toolkit-October 2020

---

2020/14xxx/CVE-2020-14750.json

modified:   2020/14xxx/CVE-2020-14750.json

 On branch cna/Oracle/AlertCVE-2020-14750
